//! Everything between the generated C and a running binary: where the runtime is,
//! what clang is invoked with, and what is cached where (design.md §3.1, panel
//! 020).
//!
//! **Finding the runtime is a search, and the search is why the stamp exists.**
//! An installed compiler has no repository above it, so there are three places to
//! look — and the second one, `runtime/` under the working directory, is a hazard:
//! `runtime` is one of the commonest directory names in a source tree. The panel's
//! ffi-pragmatist put a decoy there and the generated C compiled with **zero
//! warnings under `-Weverything`** and printed `0x1e` where `30` was expected. Every
//! generated unit therefore `_Static_assert`s `HERO_RUNTIME_ABI`, which turns that
//! silence into `error: use of undeclared identifier`. The search is kept, and the
//! silence is not.
//!
//! **The compiler itself is in the key**, and it was not until 2026-08-12: the key
//! carried `heroes::VERSION`, a string that does not move when the emitter does, so
//! rebuilding the compiler and re-running a program reused artifacts generated by
//! the *previous* one. Two debugging detours in one milestone were stale output
//! read as real — the symptom is a correct fix that appears not to work, which is
//! the most expensive shape a build system has. See `compiler_fingerprint`.
//!
//! **The cache key is the whole configuration**, not the source. Measured: with
//! `hero_print_int` changed and `runtime.o` not recompiled, the relink succeeded
//! silently and printed the old bytes. And without the optimisation level in the
//! key, the two-configuration golden harness would be one configuration run twice —
//! measuring nothing while looking thorough. So the key covers the source, the
//! compiler's version, the level, and the contents of both runtime files.
//!
//! One `.o` is correct across `-O0`, `-O2`, `-flto` and the sanitisers (measured, all
//! four link and run), so the object is keyed on the runtime's own configuration and
//! shared between programs rather than copied per build directory.

use std::path::{Path, PathBuf};
use std::process::Command;

use super::libraries::{Libraries, in_the_c_runtime, resolve_packages};

/// What identifies **this** compiler, for a cache key.
///
/// The version string plus the executable's own length and modification time —
/// a change *detector*, deliberately, not a content hash. Digesting a debug
/// binary on every invocation would cost more than every build this cache saves,
/// and the two failure modes are not symmetric: a false miss recompiles, a false
/// hit hands back the previous compiler's output and lets a green test pass for
/// the wrong reason. That is what happened, twice, in one milestone.
///
/// If the executable cannot be located the version alone is used, which is the
/// old behaviour and is stated rather than silent.
fn compiler_fingerprint() -> String {
    let Ok(exe) = std::env::current_exe() else { return heroes::VERSION.to_string() };
    let Ok(meta) = std::fs::metadata(&exe) else { return heroes::VERSION.to_string() };
    let stamp = meta
        .modified()
        .ok()
        .and_then(|t| t.duration_since(std::time::UNIX_EPOCH).ok())
        .map(|d| d.as_nanos())
        .unwrap_or(0);
    format!("{}\u{1}{}\u{1}{stamp}", heroes::VERSION, meta.len())
}

/// CLAUDE.md §7's set, in one place. `-Werror=uninitialized` is the net under the
/// emitter's hoisted prologue: a slot read on a path that never wrote it is a
/// *lowering* bug, and this is what makes it a compile error instead of a wrong
/// answer.
///
/// **`-Wconditional-uninitialized` is `-Werror=` because the corpus said so.** Panel
/// 020 adopted it with a falsifiable disposition — zero fires across the whole
/// `run/`+`emit/` corpus at both levels promotes it; one fire is a lowering bug that
/// gets a case named after it (CLAUDE.md §9) — and the measurement came back zero on
/// the first run, with clang's warnings forwarded rather than swallowed so that they
/// could. It is the strictest warning in the set and the one most likely to catch a
/// join slot the lowering forgot to write on one arm.
pub const FLAGS: [&str; 11] = [
    // **`gnu11`, not `c11`, and the difference is one predefined macro** (panel
    // 047, ratification pending). `-std=c11` defines `__STRICT_ANSI__`, and on
    // glibc that is the *only* thing it does: it hides `M_PI`, `strdup`,
    // `fileno`, `popen`, `setenv`, `newlocale`, `clock_gettime` — most of what
    // §1.11 says a program binds — while Darwin's headers do not guard them at
    // all. The same `.hero` file compiled here and failed on Linux, which is the
    // failure §4.19 exists to prevent arriving through the flags instead of
    // through the types.
    //
    // What the emitter *writes* is unchanged and still C11. Measured across the
    // two: identical LLVM IR for the runtime and for a generated unit at both
    // levels, 16 glibc struct layouts unchanged, and 63 of 63 `run/` goldens
    // cross-compiling for `x86_64-linux-gnu` — against 62 of 63 under `c11`.
    //
    // The dialect is **named** rather than left to clang's default (`gnu17`
    // today, `gnu11` before Clang 11) because a project whose acceptance is a
    // byte-identical fixpoint cannot let it drift — the same argument that
    // pinned `rust-toolchain.toml` the same day.
    "-std=gnu11",
    // **The third platform hides `M_PI` too, and for a third reason.** Panel 047
    // moved to `gnu11` because glibc guards the `math.h` constants behind
    // `__USE_MISC`, which `-std=c11` switches off. MSVC guards the same constants
    // behind `_USE_MATH_DEFINES`, which nothing switches on by default — so a
    // binding that compiles on Darwin and Linux failed on Windows with the very
    // diagnostic panel 047 was convened about (measured, the third CI leg,
    // 2026-08-14). This is Microsoft's documented switch for exactly that, and it
    // is passed everywhere because it names a macro no other platform reads.
    "-D_USE_MATH_DEFINES",
    // **The second platform switch, and the same argument as the first.** MSVC
    // deprecates `getenv`, `fopen`, `strcpy` and most of what §1.11 says a program
    // binds, in favour of `_s` variants no other platform has — so a binding that
    // is correct everywhere else fails the corpus harness's zero-warning bar on
    // Windows alone. `runtime.c` already defines this for its own compilation; the
    // generated unit needs it for the author's bindings. Named here rather than
    // discovered, like `-std=gnu11` and `_USE_MATH_DEFINES` (panel 047's class).
    "-D_CRT_SECURE_NO_WARNINGS",
    "-Wall",
    "-Werror=return-type",
    "-Werror=uninitialized",
    "-Werror=format",
    "-Werror=conditional-uninitialized",
    "-fno-strict-aliasing",
    "-Werror=shorten-64-to-32",
    "-Werror=sign-conversion",
];

pub struct Toolchain {
    /// The directory holding `heroes_runtime.h` and `runtime.c`.
    pub runtime: PathBuf,
    /// Where derived files go. Everything under it is reproducible from the inputs.
    pub build: PathBuf,
}

impl Toolchain {
    /// Locate the runtime, or say all three places it looked. A message that names
    /// only the failure would make the fix a source-reading exercise.
    pub fn find() -> Result<Toolchain, String> {
        let mut candidates: Vec<PathBuf> = Vec::new();
        if let Ok(from_env) = std::env::var("HEROES_RUNTIME") {
            candidates.push(PathBuf::from(from_env));
        }
        candidates.push(PathBuf::from("runtime"));
        if let Ok(exe) = std::env::current_exe() {
            for ancestor in exe.ancestors() {
                candidates.push(ancestor.join("runtime"));
            }
        }
        for candidate in &candidates {
            if candidate.join("heroes_runtime.h").is_file() && candidate.join("runtime.c").is_file()
            {
                return Ok(Toolchain {
                    runtime: candidate.clone(),
                    build: PathBuf::from("build"),
                });
            }
        }
        Err(format!(
            "cannot find the Heroes runtime (heroes_runtime.h and runtime.c).\n  \
             looked in: $HEROES_RUNTIME, ./runtime, and runtime/ beside the compiler\n  \
             set HEROES_RUNTIME=<dir> to say where it is (searched {} places)",
            candidates.len()
        ))
    }

    /// The runtime's whole contents, which are half of every cache key.
    ///
    /// **Every file, not the two entry points.** `runtime.c` is one translation
    /// unit assembled from `runtime/parts/`, so hashing only the file clang is
    /// handed would let a part be edited with the cached object still used — and
    /// a stale relink is silent, which is the one thing standing between a golden
    /// test and passing for the wrong reason.
    ///
    /// Sorted, so the key is a function of the contents and not of readdir order.
    fn runtime_text(&self) -> String {
        let mut files: Vec<PathBuf> = Vec::new();
        collect_sources(&self.runtime, &mut files);
        files.sort();
        let mut text = String::new();
        for file in &files {
            text.push_str(&std::fs::read_to_string(file).unwrap_or_default());
            text.push('\u{1}');
        }
        text
    }

    /// Where this program's artifacts live: `build/<hash>/`.
    ///
    /// design.md §3.1's own shape. The hash is what makes two files with the same
    /// stem, or the same file at two optimisation levels, different builds.
    pub fn dir_for(
        &self,
        source: &str,
        text: &str,
        level: &str,
        sanitize: bool,
        search: &str,
    ) -> Result<PathBuf, String> {
        let key = digest(&format!(
            "{}\u{1}{}{}\u{1}{}\u{1}{}\u{1}{}{}",
            compiler_fingerprint(),
            level,
            if sanitize { "+san" } else { "" },
            source,
            text,
            self.runtime_text(),
            // **The search paths, and they are here because a build without them
            // is a different build** (panel 055, measured on the prototype: two
            // configurations shared one artifact path and the second silently
            // reused the first). Empty when neither flag was given, so every
            // directory that existed before this keeps its name.
            search
        ));
        let dir = self.build.join(&key);
        std::fs::create_dir_all(&dir).map_err(|e| format!("cannot create {}: {e}", dir.display()))?;
        Ok(dir)
    }

    /// Compile the runtime once and cache it, keyed on its own contents and the
    /// level. A stale relink is silent, so the key is the only thing standing
    /// between a golden test and passing for the wrong reason.
    pub fn runtime_object(&self, level: &str, sanitize: bool) -> Result<PathBuf, String> {
        let key = digest(&format!(
            "{}\u{1}{level}\u{1}{sanitize}\u{1}{}",
            compiler_fingerprint(),
            self.runtime_text()
        ));
        std::fs::create_dir_all(&self.build)
            .map_err(|e| format!("cannot create {}: {e}", self.build.display()))?;
        let object = self.build.join(format!("runtime-{key}.o"));
        if object.is_file() {
            return Ok(object);
        }
        // **Written beside it and renamed into place**, because `is_file()` above
        // is a *published* flag and clang writing to `object` directly would raise
        // it while the file was still half a file. Two `heroes` processes on a cold
        // cache is not a hypothetical: `cargo test` runs the test binaries in
        // parallel and each one builds programs, and the failure it produced was a
        // link against a truncated object — once, in one run out of several, which
        // is the worst way for a defect to present itself. A rename inside one
        // directory is atomic on POSIX, so a reader sees no file or a whole one.
        //
        // The temporary carries the process id so two compilers never share it. If
        // another process wins the rename, its object is byte-for-byte ours — the
        // key covers the compiler, the level, the sanitiser and the runtime's whole
        // contents — so losing the race costs nothing and is not reported.
        let staged = self.build.join(format!("runtime-{key}.o.{}.tmp", std::process::id()));
        let mut clang = Command::new("clang");
        clang.args(FLAGS).arg(level).args(sanitizers(sanitize)).arg("-c");
        clang.arg(self.runtime.join("runtime.c"));
        clang.arg("-I").arg(&self.runtime);
        clang.arg("-o").arg(&staged);
        run(clang, "compiling the runtime")?;
        publish(&staged, &object)?;
        Ok(object)
    }

    /// Compile one generated translation unit and link it with the runtime.
    ///
    /// **`include` comes after the runtime's own `-I`** (§4.19, panel 036). The
    /// generated unit includes `<header.h>` for every `extern` group, and the
    /// author's own header sits beside their `.hero` file rather than beside the
    /// translation unit, which lives under `build/<hash>/`. Ordering matters in
    /// one direction only: a source directory that happens to contain a file
    /// named `heroes_runtime.h` must not win over the real one.
    ///
    /// `libraries` are the `link "…"` strings, passed as `-l<name>`. They are
    /// **names, not flags**: the value is quoted in the source and reaches clang
    /// with `-l` prefixed here, so no `.hero` file can hand clang an arbitrary
    /// argument.
    #[allow(clippy::too_many_arguments)] // PORT-DEBT: one call site, seven facts
    pub fn link(
        &self,
        c_file: &Path,
        object: &Path,
        binary: &Path,
        level: &str,
        sanitize: bool,
        include: Option<&Path>,
        libraries: &Libraries,
    ) -> Result<(), String> {
        // Asked before clang runs, so a package that is not installed is reported
        // as itself rather than as a header clang could not find.
        let from_packages = resolve_packages(&libraries.packages)?;
        let mut clang = Command::new("clang");
        clang.args(FLAGS).arg(level).args(sanitizers(sanitize));
        // **Before the package's own flags**, so that where the two disagree about
        // a version the author's answer wins — which is the direction the author
        // can act on. Each path is its own argv word, which is what makes the
        // absence of an allow-list safe (see `Libraries::search`).
        for directory in &libraries.search.include {
            clang.arg("-I").arg(directory);
        }
        for directory in &libraries.search.library {
            clang.arg("-L").arg(directory);
        }
        clang.arg(c_file).arg(object);
        clang.arg("-I").arg(&self.runtime);
        if let Some(directory) = include {
            clang.arg("-I").arg(directory);
        }
        // **Before the names.** A package answers with `-I` and `-L` as well as
        // `-l`, and a search path that arrives after the library it is for is a
        // path the linker has already stopped needing.
        clang.args(&from_packages);
        for library in &libraries.link {
            if in_the_c_runtime(library) {
                continue;
            }
            clang.arg(format!("-l{library}"));
        }
        // **Written beside it and renamed into place**, for the reason the runtime
        // object already is: `build/<hash>/` is content-addressed, so two `heroes`
        // processes compiling the same program agree on the path — and `cargo
        // test` runs its binaries in parallel, so a third one can be *executing*
        // that path while this one truncates it. It failed three times over two
        // days, never twice in a row, which is the signature of a race and the
        // worst way for a defect to present itself. A rename inside one directory
        // is atomic on POSIX; losing it costs nothing, because the key covers the
        // whole configuration and the winner's binary is ours.
        let staged = binary.with_extension(format!("{}.tmp", std::process::id()));
        clang.arg("-o").arg(&staged);
        run(clang, "compiling the generated C")?;
        publish(&staged, binary)
    }
}

/// Move a freshly compiled artifact onto its content-addressed path, **and treat
/// losing the race as success**.
///
/// The premise, written as a claim so it can be falsified: *a file already at this
/// path was compiled from the same inputs as the one being staged*, because the
/// key covers the compiler's fingerprint, the optimisation level, the sanitiser,
/// the source path, the source text and the whole runtime's contents. Whatever is
/// there is byte-for-byte ours. `dir_for` and `runtime_object` are the two places
/// that build the key, and the claim dies the day either stops covering an input
/// that changes the output.
///
/// **Windows is why this is a function rather than a `rename`.** On POSIX, renaming
/// onto a path a *running process is executing* succeeds: the old inode survives
/// for as long as that process holds it. Windows locks the image and returns
/// `ERROR_ACCESS_DENIED (os error 5)`, so `cargo test`'s parallel harness — which
/// runs the same golden at two optimisation levels and can therefore have one
/// binary executing while another lands — failed on the third CI leg where it had
/// passed on two for a day. Measured 2026-08-14.
///
/// So the loss is made explicit instead of being reported as an internal error.
/// The staged file is removed either way; a failure with **no** file at the
/// destination is a real failure and is still returned.
fn publish(staged: &Path, final_path: &Path) -> Result<(), String> {
    match std::fs::rename(staged, final_path) {
        Ok(()) => Ok(()),
        Err(_) if final_path.exists() => {
            let _ = std::fs::remove_file(staged);
            Ok(())
        }
        Err(e) => Err(format!("cannot publish {}: {e}", final_path.display())),
    }
}


/// `--sanitize`'s flags, and what they are for.
///
/// **Not a leak detector.** AddressSanitizer's is missing on Darwin arm64
/// (`detect_leaks is not supported on this platform`, exit 134), and a program leaking
/// 999 blocks exits 0 in silence under it — measured twice, by two panel judges
/// independently. Leaks are caught by `hero_runtime_check_leaks()` in the generated
/// `main`. What these two *do* catch is use-after-free and double-free, and they caught
/// two real bugs in the panel's own hand-written C on their first run, which no output
/// comparison would have.
/// Every `.c` and `.h` under `dir`, one level of nesting deep — which is what
/// `runtime/` is: the entry points beside a `parts/` directory. Recursive rather
/// than hard-coded so that adding a part is not a second edit somewhere else.
fn collect_sources(dir: &Path, into: &mut Vec<PathBuf>) {
    let Ok(entries) = std::fs::read_dir(dir) else { return };
    for entry in entries.flatten() {
        let path = entry.path();
        if path.is_dir() {
            collect_sources(&path, into);
        } else if matches!(path.extension().and_then(|e| e.to_str()), Some("c") | Some("h")) {
            into.push(path);
        }
    }
}

fn sanitizers(sanitize: bool) -> Vec<String> {
    if sanitize {
        vec!["-fsanitize=address,undefined".to_string(), "-g".to_string()]
    } else {
        Vec::new()
    }
}

/// clang's own words, kept verbatim. A failure here says **the compiler is wrong**
/// — the generated C is not the author's text — so the caller exits 2 and says so.
///
/// A *warning* is forwarded rather than swallowed, and that is the whole point of
/// the flag set: `-Wconditional-uninitialized` is in it without `-Werror` on a
/// falsifiable disposition (zero fires across the corpus promotes it; one fire is a
/// lowering bug with a case named after it), and a warning nobody ever sees cannot
/// falsify anything.
fn run(mut clang: Command, what: &str) -> Result<(), String> {
    let output = clang
        .output()
        .map_err(|e| format!("cannot run clang: {e} — try `heroes doctor`"))?;
    if output.status.success() {
        let noise = String::from_utf8_lossy(&output.stderr);
        if !noise.trim().is_empty() {
            eprint!("{noise}");
        }
        return Ok(());
    }
    Err(format!(
        "{what} failed:\n{}{}",
        String::from_utf8_lossy(&output.stderr),
        String::from_utf8_lossy(&output.stdout)
    ))
}

/// FNV-1a, 64 bits, as sixteen hex digits.
///
/// Vendored rather than depended on, like the tokenisers in `measure/`: the whole
/// pipeline has zero dependencies and a cache key is not the place to acquire the
/// first one. Deterministic across runs and machines — no seed, no `RandomState`,
/// which `BTreeMap`-only (CLAUDE.md §5) exists to guarantee for the same reason.
pub fn digest(text: &str) -> String {
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    for byte in text.as_bytes() {
        hash ^= *byte as u64;
        hash = hash.wrapping_mul(0x0000_0100_0000_01b3);
    }
    format!("{hash:016x}")
}
