//! One translation unit's skeleton: prototypes, prologues, the shim (design.md
//! §3.1, panel 020).
//!
//! **Declaration ordering** is the first of the emitter's two obligations. Heroes'
//! top level is order-free and mutual recursion needs no forward declarations
//! (§4.2); C's does not work that way. So every prototype is emitted before every
//! definition, in source order — deterministic, and it needs no topological sort at
//! M-scalars-run because there are no `typedef struct`s yet: aggregates arrive with the
//! descriptor pass at M-value-aggregates, and their containment cycles with them.
//!
//! **The prologue exists because `goto` may not jump over an initialisation.**
//! Every slot and every temporary is declared at the top of the function, and
//! nothing is given an initial value: a Heroes binding is always initialised
//! (§4.4) and a synthetic join slot is written on every arm, so a C local that
//! clang thinks may be read uninitialised is a *lowering* bug — which is exactly
//! what `-Werror=uninitialized` is in the flag set to catch. Zero-initialising them
//! would hide it.
//!
//! **The `main` shim, not a mangler exception.** Heroes' `main` becomes
//! `h_<module>_main` like every other function, and a separate `int main(void)`
//! calls it. Vala does exactly this (`ccode.add_return (main_call)`), Nim's
//! generated `main` is a shim and `NimMain()` is where initialisation goes, and
//! Zig's C backend once emitted `void main(void)` — which clang rejects. The shim
//! is also where runtime setup will go when there is any.

use crate::ir::{is_refcounted, Function, Program, SlotId, SlotKind};
use crate::source::Source;
use crate::syntax::Ast;
use crate::types::Checked;

use super::Target;
use super::ctype::{c_result, c_type, is_unit, Names};
use super::externs;
use super::mangle;
use super::writer::Writer;
use super::{inst, term};

/// The header every generated file opens with.
///
/// The `_Static_assert` is not decoration. The runtime is found by searching, and
/// a directory called `runtime/` is one of the commonest things in a source tree:
/// the panel's ffi-pragmatist put a decoy one in the working directory and the
/// generated C compiled with **zero warnings under `-Weverything`** and printed
/// `0x1e` where `30` was expected. With the stamp, the same C is `error: use of
/// undeclared identifier 'HERO_RUNTIME_ABI'`.
pub(super) fn prelude(
    w: &mut Writer,
    program: &Program,
    target: Target,
    ast: &Ast,
    checked: &Checked,
    src: &Source,
) {
    w.line(&format!(
        "/* Generated by heroes {} from {}. Do not edit. */",
        crate::VERSION, src.name
    ));
    w.line("#include \"heroes_runtime.h\"");
    // `math.h` for `HUGE_VAL`, which is how an infinite `f64` literal is spelled —
    // and it heads the list rather than standing above it so that a program
    // binding libm does not include it twice.
    //
    // Then §4.19: every header a group named, in declaration order. **Angled,
    // never quoted** — panel 036 measured what the quoted form costs: a decoy
    // `sqlite3.h` beside the generated unit in `build/<hash>/` is read with zero
    // diagnostics under `-Weverything`, and no `_Static_assert` can be written
    // against a header this compiler does not own. The author's own header is
    // found because `compile.rs` passes `-I<directory of the .hero source>`.
    for header in externs::headers(program, ast, src) {
        w.line(&format!("#include <{header}>"));
    }
    w.line("");
    w.line(
        "_Static_assert(HERO_RUNTIME_ABI == 10, \"heroes_runtime.h is from another compiler\");",
    );
    w.line("");
    externs::extern_assertions(w, program, ast, checked, src);
    // Every decoded string literal **an emitted function actually reads**, as a
    // static block clang lays out: refcount −1 means "never freed", so a literal
    // allocates nothing and decrefing one is a no-op. The escapes were applied once,
    // at lowering (panel 008), so this is the one place they are re-escaped for C.
    //
    // Reachability, not the whole table, and it is not tidiness: `program.strings`
    // holds every literal in the *file*, including the ones only a `test` block or an
    // `assert` message mentions — and §4.18 says ordinary builds ignore those. Emitted
    // anyway, they are `-Wunused-const-variable`, which is the same warning panel 022
    // named for an unused descriptor. Eight of them on one gallery program, on every
    // build, is how a real diagnostic gets lost in noise.
    //
    // The index is kept: `hero_str_7` stays `hero_str_7` whether or not 0..6 are
    // emitted, so the name is a function of the literal and not of what surrounds it —
    // which is what keeps `--emit-c` stable when a `test` block is added to a file.
    let live = live_strings(program, target, src);
    for (index, text) in program.strings.iter().enumerate() {
        if !live.contains(&(index as u32)) {
            continue;
        }
        w.line(&format!("HERO_STR_STATIC(hero_str_{index}, \"{}\");", escape_c(text)));
    }
    if !live.is_empty() {
        w.line("");
    }
}


/// Which string literals an emitted function reads. A walk, because the answer must
/// come from the instructions rather than from a count kept in step with them.
fn live_strings(
    program: &Program,
    target: Target,
    src: &Source,
) -> std::collections::BTreeSet<u32> {
    // **The same set `emit_for` emits**, and it has to be: a library function the
    // program never reaches is dropped there, so counting its literals here left
    // them defined and unreferenced — `-Wunused-const-variable`, which is the
    // warning this walk exists to prevent.
    //
    // Invisible until M-ffi-ladder because no library function had a string in it.
    // `read_file` and `write_file` are the first, and they have four between them:
    // a program that reads a file and never writes one printed two warnings.
    let used = super::builtins::reachable(program, src);
    let mut live = std::collections::BTreeSet::new();
    for function in &program.functions {
        if !emitted(function, target) {
            continue;
        }
        if src.is_library(function.span.start) && !used.contains(&function.decl) {
            continue;
        }
        for block in &function.blocks {
            for inst in &block.insts {
                if let crate::ir::Op::Const(crate::ir::Const::Str(index)) = inst.op {
                    live.insert(index.0);
                }
            }
        }
    }
    live
}

/// A decoded Heroes string, as a C string literal. Octal escapes for everything
/// non-printable, because `\xNN` in C has no length limit and would swallow a
/// following hex digit.
fn escape_c(text: &str) -> String {
    let mut out = String::with_capacity(text.len() + 2);
    for byte in text.as_bytes() {
        match *byte {
            b'"' => out.push_str("\\\""),
            b'\\' => out.push_str("\\\\"),
            b'\n' => out.push_str("\\n"),
            b'\t' => out.push_str("\\t"),
            0x20..=0x7e => out.push(*byte as char),
            other => out.push_str(&format!("\\{other:03o}")),
        }
    }
    out
}

/// Whether this function reaches C at all. A `test` block does not: §4.18 says
/// ordinary builds ignore it, and `heroes test` (M-generics-library) is what enters it.
pub(super) fn emitted(function: &Function, target: Target) -> bool {
    use crate::ir::FnKind;
    match function.kind {
        FnKind::Function | FnKind::Constant => true,
        // §4.18: "`test` blocks run only when asked for; ordinary builds ignore
        // them." Asking for them is `heroes test`, and this is where the two
        // readings of one program part.
        FnKind::Test => target == Target::Tests,
        FnKind::Extern => false,
    }
}


pub(super) fn prototype(
    w: &mut Writer,
    function: &Function,
    target: Target,
    ast: &Ast,
    checked: &Checked,
    src: &Source,
    names: &Names,
) {
    if !emitted(function, target) {
        return;
    }
    w.at_generated();
    w.line(&format!("{};", signature(function, ast, checked, src, names)));
}

/// `int64_t h_mod_dist(int64_t h0_a, int64_t *ph1_b)`.
///
/// A mutable parameter is a **pointer** parameter — §4.8's copy-in/copy-out has no
/// other shape in C, because `Op::CopyOut` writes the *caller's* place and the
/// callee cannot otherwise reach it.
/// The C name of one function: its mangled name, plus the hash of what it was
/// instantiated at when it is a monomorphised instance (§4.12, panel 029 R5).
///
/// The rendering that is hashed is the *canonical* one — `render_instance` — so
/// the port reproduces the same symbol from the same public spelling, and the
/// M-selfhost-fixpoint fixpoint does not depend on two implementations interning in the same
/// order.
pub(super) fn instance_name(
    function: &Function,
    ast: &Ast,
    checked: &Checked,
    src: &Source,
) -> String {
    let module = src.component_at(function.span.start);
    if function.kind == crate::ir::FnKind::Test {
        return mangle::test(module, function.decl as usize);
    }
    if function.instance.is_empty() {
        return mangle::function(module, &function.name);
    }
    let rendered = render_instance(ast, checked, src, &function.instance);
    mangle::instance_of(module, &function.name, &rendered)
}

/// The type arguments as one string, which is what the hash is taken over and
/// what the comment above an instance shows. Independent of `TyId`, of the
/// module, and of the file's name.
pub(super) fn render_instance(
    ast: &Ast,
    checked: &Checked,
    src: &Source,
    args: &[crate::types::TyId],
) -> String {
    args.iter()
        .map(|t| crate::types::render_ty(&checked.types, ast, src, *t, &[]))
        .collect::<Vec<String>>()
        .join(", ")
}

fn signature(
    function: &Function,
    ast: &Ast,
    checked: &Checked,
    src: &Source,
    names: &Names,
) -> String {
    let name = instance_name(function, ast, checked, src);
    let result = c_result(names, checked, function.result);
    let mut params: Vec<String> = Vec::new();
    for slot in &function.params {
        params.push(param(function, checked, names, *slot));
    }
    let list = if params.is_empty() { "void".to_string() } else { params.join(", ") };
    format!("{result} {name}({list})")
}

fn param(function: &Function, checked: &Checked, names: &Names, slot: SlotId) -> String {
    let index = slot.0;
    let declared = &function.slots[index as usize];
    let ty = c_type(names, checked, declared.ty).unwrap_or_else(|| "void".to_string());
    if matches!(declared.kind, SlotKind::Param { mutable: true }) {
        format!("{ty} *{}", mangle::out_param(index, &declared.name))
    } else {
        format!("{ty} {}", mangle::slot(index, &declared.name))
    }
}

#[allow(clippy::too_many_arguments)] // PORT-DEBT: one emitter call site
pub(super) fn definition(
    w: &mut Writer,
    program: &Program,
    function: &Function,
    target: Target,
    ast: &Ast,
    checked: &Checked,
    names: &Names,
    src: &Source,
) {
    if !emitted(function, target) {
        return;
    }
    w.blank();
    // The signature is pointed at the author's declaration: a clang error about a
    // parameter type has to land on the line that wrote it.
    super::writer::at_span(w, src, function.span.start);
    // The instance's types, above it, because the hash in the name does not carry
    // them and a reader of `--emit-c` needs them (panel 029 R5).
    if !function.instance.is_empty() {
        w.line(&format!(
            "/* {}<{}> */",
            function.name,
            render_instance(ast, checked, src, &function.instance)
        ));
    }
    // **An `extern constant` has no blocks, so it takes none of the machinery
    // below.** The prologue, the entry `goto bb0` and the label walk all assume a
    // body; a blockless function through that path emits a jump to a label that is
    // never printed. What it needs instead is one line — the C name, read where
    // the preprocessor can see it (§4.19, panel 038).
    if externs::is_extern_constant(ast, function) {
        let name = src.slice(ast.decls[function.decl as usize].name);
        w.line(&format!("{} {{", signature(function, ast, checked, src, names)));
        w.at_generated();
        w.line(&format!("    return {name};"));
        w.line("}");
        return;
    }
    w.line(&format!("{} {{", signature(function, ast, checked, src, names)));
    w.at_generated();
    let types = super::aggregate::Types { ast, checked, names, src };
    let live = reachable(function);
    let read = emitted_reads(function, checked);
    prologue(w, function, checked, names, &live, &read);
    w.line(&format!("    goto {};", mangle::block(0)));
    for (index, block) in function.blocks.iter().enumerate() {
        if !live[index] {
            continue;
        }
        w.line(&format!("{}:", mangle::block(index)));
        for one in &block.insts {
            inst::emit(w, program, &types, function, one, &read);
        }
        term::emit(w, function, checked, &block.term);
    }
    w.at_generated();
    w.line("}");
}


/// Which blocks are reachable. A block nothing jumps to is **omitted entirely** —
/// not merely unlabelled, because C is physical and an unlabelled block would fall
/// through from the one above it.
///
/// The IR already carries the answer (`Block::preds`), so this is a lookup rather
/// than an analysis. It exists because a *correct* Heroes program produces one: an
/// `if` whose both arms `return` leaves an unreachable join block, and emitting its
/// label costs `-Wunused-label` on every build — which would then have to be
/// switched off, taking the emitter's own bugs with it.
fn reachable(function: &Function) -> Vec<bool> {
    let mut live = vec![false; function.blocks.len()];
    for (index, block) in function.blocks.iter().enumerate() {
        live[index] = index == 0 || !block.preds.is_empty();
    }
    live
}

fn prologue(
    w: &mut Writer,
    function: &Function,
    checked: &Checked,
    names: &Names,
    live: &[bool],
    read: &std::collections::BTreeSet<u32>,
) {
    for (index, slot) in function.slots.iter().enumerate() {
        // A parameter is already declared by the signature. A mutable one is
        // declared here instead: the pointer is the parameter, and the slot is the
        // local copy §4.8 says the callee works on.
        let is_param = function.params.contains(&SlotId(index as u32));
        let mutable = matches!(slot.kind, SlotKind::Param { mutable: true });
        if is_param && !mutable {
            continue;
        }
        if let Some(ty) = c_type(names, checked, slot.ty) {
            // **The one exception to "nothing is initialised here"** (panel 021 R3).
            // A refcounted slot is zeroed so that the exit sweep is unconditional:
            // `decref` of the null non-value is a no-op, and the alternative is a
            // liveness pass. clang's ARC specification licenses exactly this for
            // `__strong` locals — "may be properly initialized by filling it with
            // the representation of a null pointer" — and rustc's `ElaborateDrops`
            // does the alternative and then optimises it into the same thing.
            //
            // The cost is real and stated: `-Werror=uninitialized` stops covering
            // these, and without the zero clang would have reported a *compile
            // error*. What replaces it is `ptr == NULL` being the one non-value that
            // every runtime entry point rejects loudly, plus the verifier's own
            // store-before-load check.
            let initialiser = if is_refcounted(checked, slot.ty) { " = {0}" } else { "" };
            w.line(&format!(
                "    {ty} {}{initialiser};",
                mangle::slot(index as u32, &slot.name)
            ));
        }
    }
    for (index, ty) in function.values.iter().enumerate() {
        if is_unit(checked, *ty) || !assigned(function, live, index as u32) {
            continue;
        }
        // A discarded result is never assigned either (`inst::emit`), so declaring
        // it here would be the unused variable this rule exists to stop. The two
        // decisions have to agree, and they agree by reading the same set.
        if discarded(function, live, index as u32, read) {
            continue;
        }
        if let Some(name) = c_type(names, checked, *ty) {
            let initialiser = if is_refcounted(checked, *ty) { " = {0}" } else { "" };
            w.line(&format!("    {name} {}{initialiser};", mangle::value(index as u32)));
        }
    }
    // Copy-in, after every declaration: §4.8's first half.
    for slot in &function.params {
        let declared = &function.slots[slot.0 as usize];
        if !matches!(declared.kind, SlotKind::Param { mutable: true }) {
            continue;
        }
        w.line(&format!(
            "    {} = *{};",
            mangle::slot(slot.0, &declared.name),
            mangle::out_param(slot.0, &declared.name)
        ));
    }
}

/// Whether any *emitted* instruction assigns this temporary. `$t0` (the unit) is
/// assigned by nothing and named by nothing, and a temporary that only exists
/// inside a block nobody reaches would be an unused variable.
fn assigned(function: &Function, live: &[bool], value: u32) -> bool {
    for (index, block) in function.blocks.iter().enumerate() {
        if !live[index] {
            continue;
        }
        for one in &block.insts {
            if one.dest == Some(crate::ir::ValueId(value)) {
                return true;
            }
        }
    }
    false
}

/// A temporary that a call, a load or a constant writes and nothing reads:
/// `_ = f(x)`, and the load `r.must()` leaves behind when the payload is `()`.
///
/// The pair of this and `inst::emit`'s own test is what keeps the declaration and
/// the assignment in step — they agree because they ask the same question of the
/// same set. The three ops are the safe ones: a pure result may disappear, but an
/// *aborting* op's must not, or dropping the assignment drops the check.
fn discarded(
    function: &Function,
    live: &[bool],
    value: u32,
    read: &std::collections::BTreeSet<u32>,
) -> bool {
    if read.contains(&value) {
        return false;
    }
    for (index, block) in function.blocks.iter().enumerate() {
        if !live[index] {
            continue;
        }
        for one in &block.insts {
            if one.dest == Some(crate::ir::ValueId(value)) {
                return matches!(
                    one.op,
                    crate::ir::Op::Call { .. } | crate::ir::Op::Load(_) | crate::ir::Op::Const(_)
                );
            }
        }
    }
    false
}

/// What the **emitted C** reads, which is not what the IR references.
///
/// An instruction whose result is unit emits nothing at all (`is_unit` in
/// `inst::emit`), so its operands are referenced by the IR and read by no C. The
/// case that produced this is `()?`: `r.must()` lowers to a load and a payload
/// extraction, the extraction's result is `()`, and the load was left assigned
/// and unread — `-Wunused-but-set-variable` on a correct program.
///
/// **One pass, not a fixpoint, and the limit is stated rather than discovered.**
/// A suppressed reader whose own operand is produced by another suppressed
/// reader would still leave a warning; no such chain exists today, because the
/// only suppressed ops are the one-step extractions above. If one appears, this
/// is where it is answered, and the answer is a worklist.
fn emitted_reads(
    function: &Function,
    checked: &Checked,
) -> std::collections::BTreeSet<u32> {
    let mut read = std::collections::BTreeSet::new();
    for block in &function.blocks {
        for one in &block.insts {
            // A pure op with a unit result prints nothing, so it reads nothing.
            let silent = one.dest.is_some()
                && is_unit(checked, one.ty)
                && !matches!(one.op, crate::ir::Op::Call { .. } | crate::ir::Op::Abort { .. });
            if silent {
                continue;
            }
            for value in crate::ir::uses::operands(function, one.op) {
                read.insert(value.0);
            }
        }
        for value in crate::ir::uses::terminator_operands(&block.term) {
            read.insert(value.0);
        }
    }
    read
}
