/* Generated by heroes 0.0.1 from examples/csv/main.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 20, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 45 "main.c"
#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 117 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 123 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 63 "main.c"
#pragma clang diagnostic pop

HERO_STR_STATIC(hero_str_0, "");
HERO_STR_STATIC(hero_str_22, "\"");
HERO_STR_STATIC(hero_str_2c, ",");
HERO_STR_STATIC(hero_str_a, "\n");
HERO_STR_STATIC(hero_str_41de4fd4, "unterminated_quote");
HERO_STR_STATIC(hero_str_6147841e, "a quoted field never closes");
HERO_STR_STATIC(hero_str_688477b1, "no_such_column");
HERO_STR_STATIC(hero_str_5921dbd5, "the table has no column at that index");
HERO_STR_STATIC(hero_str_690861d0, "name,role,note\nada,engineer,\"first, and by some distance\"\ngrace,admiral,\"said \"\"debugging\"\" first\"\nalan,logician,\n");
HERO_STR_STATIC(hero_str_8a0b4, " | ");
HERO_STR_STATIC(hero_str_141e32a0, "a,\"unclosed");

typedef struct h_main_Table {
    HeroArrayHeader * f_rows;
} h_main_Table;

typedef struct h_0opt_755e4b59 {
    int64_t tag;
    union {
        h_main_Table ok;
        HeroFailure err;
    } as;
} h_0opt_755e4b59;

typedef struct h_0opt_5a58f2ca {
    int64_t tag;
    union {
        HeroArrayHeader * ok;
        HeroFailure err;
    } as;
} h_0opt_5a58f2ca;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

HERO_TU_LOCAL void h_main_Table_retain(const h_main_Table *v);
HERO_TU_LOCAL void h_main_Table_release(h_main_Table *v);
HERO_TU_LOCAL bool h_main_Table_eq(const h_main_Table *a, const h_main_Table *b);
HERO_TU_LOCAL uint64_t h_main_Table_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_755e4b59_retain(const h_0opt_755e4b59 *v);
HERO_TU_LOCAL void h_0opt_755e4b59_release(h_0opt_755e4b59 *v);
HERO_TU_LOCAL bool h_0opt_755e4b59_eq(const h_0opt_755e4b59 *a, const h_0opt_755e4b59 *b);
HERO_TU_LOCAL uint64_t h_0opt_755e4b59_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_5a58f2ca_retain(const h_0opt_5a58f2ca *v);
HERO_TU_LOCAL void h_0opt_5a58f2ca_release(h_0opt_5a58f2ca *v);
HERO_TU_LOCAL bool h_0opt_5a58f2ca_eq(const h_0opt_5a58f2ca *a, const h_0opt_5a58f2ca *b);
HERO_TU_LOCAL uint64_t h_0opt_5a58f2ca_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

static void h_main_Table_desc_copy(void *dst, const void *src) {
    *(h_main_Table *)dst = *(const h_main_Table *)src;
    h_main_Table_retain((const h_main_Table *)dst);
}
static void h_main_Table_desc_drop(void *elem) {
    h_main_Table_release((h_main_Table *)elem);
}
static bool h_main_Table_desc_eq(const void *a, const void *b) {
    return h_main_Table_eq((const h_main_Table *)a, (const h_main_Table *)b);
}
HERO_TU_QUIET static const HeroDesc h_main_Table_desc = {
    sizeof(h_main_Table),
    h_main_Table_desc_copy,
    h_main_Table_desc_drop,
    h_main_Table_desc_eq,
    h_main_Table_hash,
};

h_0opt_755e4b59 h_main_parse(HeroStr h0_text);
int64_t h_main_width(h_main_Table h0_t);
bool h_main_rectangular(h_main_Table h0_t);
h_0opt_5a58f2ca h_main_column(h_main_Table h0_t, int64_t h1_at);
HeroStr h_main_SAMPLE(void);
void h_main_main(void);

#line 23 "examples/csv/main.hero"
h_0opt_755e4b59 h_main_parse(HeroStr h0_text) {
#line 161 "main.c"
    HeroArrayHeader * h1_rows = {0};
    HeroArrayHeader * h2_row = {0};
    HeroStr h3_field = {0};
    bool h4_quoted;
    bool h5_pending_quote;
    bool h6_started;
    HeroArrayHeader * h7_xs0 = {0};
    int64_t h8_i0;
    HeroStr h9_ch = {0};
    bool h10_b0;
    bool h11_b1;
    bool h12_b2;
    HeroArrayHeader * h13_own13 = {0};
    HeroArrayHeader * h14_own14 = {0};
    HeroArrayHeader * h15_own15 = {0};
    HeroStr h16_own16 = {0};
    HeroStr h17_own17 = {0};
    HeroStr h18_own18 = {0};
    HeroArrayHeader * h19_own19 = {0};
    h_0opt_755e4b59 h20_own20 = {0};
    h_main_Table h21_own21 = {0};
    h_0opt_755e4b59 h22_own22 = {0};
    HeroArrayHeader * t1 = {0};
    HeroArrayHeader * t2 = {0};
    HeroStr t3 = {0};
    bool t4;
    bool t5;
    bool t6;
    HeroStr t7 = {0};
    HeroArrayHeader * t8 = {0};
    int64_t t9;
    int64_t t10;
    HeroArrayHeader * t11 = {0};
    int64_t t12;
    bool t13;
    HeroArrayHeader * t14 = {0};
    int64_t t15;
    HeroStr t16 = {0};
    bool t17;
    bool t18;
    HeroStr t19 = {0};
    HeroStr t20 = {0};
    bool t21;
    HeroStr t22 = {0};
    HeroStr t23 = {0};
    HeroStr t24 = {0};
    bool t25;
    bool t26;
    HeroStr t27 = {0};
    HeroStr t28 = {0};
    bool t29;
    bool t30;
    HeroStr t31 = {0};
    HeroStr t32 = {0};
    HeroStr t33 = {0};
    HeroStr t34 = {0};
    HeroStr t35 = {0};
    bool t36;
    bool t37;
    bool t38;
    HeroStr t39 = {0};
    HeroStr t40 = {0};
    bool t41;
    HeroStr t43 = {0};
    HeroStr t45 = {0};
    bool t46;
    HeroStr t47 = {0};
    HeroStr t48 = {0};
    bool t49;
    HeroStr t51 = {0};
    HeroArrayHeader * t54 = {0};
    HeroArrayHeader * t56 = {0};
    HeroStr t57 = {0};
    bool t58;
    HeroStr t59 = {0};
    HeroStr t60 = {0};
    HeroStr t61 = {0};
    bool t62;
    int64_t t63;
    int64_t t64;
    int64_t t65;
    bool t66;
    bool t67;
    bool t68;
    bool t69;
    HeroStr t70 = {0};
    HeroStr t71 = {0};
    h_0opt_755e4b59 t72 = {0};
    bool t73;
    HeroStr t74 = {0};
    int64_t t75;
    int64_t t76;
    bool t77;
    bool t78;
    HeroArrayHeader * t79 = {0};
    int64_t t80;
    int64_t t81;
    bool t82;
    bool t83;
    HeroStr t85 = {0};
    HeroArrayHeader * t88 = {0};
    HeroArrayHeader * t90 = {0};
    h_main_Table t91 = {0};
    h_0opt_755e4b59 t92 = {0};
    HeroArrayHeader * t93 = {0};
    HeroArrayHeader * t94 = {0};
    HeroArrayHeader * t95 = {0};
    HeroArrayHeader * t96 = {0};
    HeroStr t97 = {0};
    HeroArrayHeader * t98 = {0};
    HeroArrayHeader * t99 = {0};
    HeroStr t100 = {0};
    HeroStr t101 = {0};
    HeroStr t102 = {0};
    HeroStr t103 = {0};
    HeroStr t104 = {0};
    HeroStr t105 = {0};
    HeroStr t106 = {0};
    HeroStr t107 = {0};
    HeroArrayHeader * t108 = {0};
    HeroArrayHeader * t109 = {0};
    HeroStr t110 = {0};
    h_0opt_755e4b59 t111 = {0};
    h_main_Table t112 = {0};
    h_0opt_755e4b59 t113 = {0};
    goto bb0;
bb0:
#line 24 "examples/csv/main.hero"
    t1 = hero_array_new(&hero_desc_array, 1);
#line 24 "examples/csv/main.hero"
    t93 = h13_own13;
#line 24 "examples/csv/main.hero"
    h13_own13 = t1;
#line 295 "main.c"
    hero_array_decref(t93);
#line 24 "examples/csv/main.hero"
    t94 = h1_rows;
#line 299 "main.c"
    hero_array_incref(t1);
#line 24 "examples/csv/main.hero"
    h1_rows = t1;
#line 303 "main.c"
    hero_array_decref(t94);
#line 25 "examples/csv/main.hero"
    t2 = hero_array_new(&hero_desc_str, 1);
#line 25 "examples/csv/main.hero"
    t95 = h14_own14;
#line 25 "examples/csv/main.hero"
    h14_own14 = t2;
#line 311 "main.c"
    hero_array_decref(t95);
#line 25 "examples/csv/main.hero"
    t96 = h2_row;
#line 315 "main.c"
    hero_array_incref(t2);
#line 25 "examples/csv/main.hero"
    h2_row = t2;
#line 319 "main.c"
    hero_array_decref(t96);
#line 26 "examples/csv/main.hero"
    t3 = HERO_STR_LIT(hero_str_0);
#line 26 "examples/csv/main.hero"
    t97 = h3_field;
#line 325 "main.c"
    hero_str_incref(t3);
#line 26 "examples/csv/main.hero"
    h3_field = t3;
#line 329 "main.c"
    hero_str_decref(t97);
#line 27 "examples/csv/main.hero"
    t4 = false;
#line 27 "examples/csv/main.hero"
    h4_quoted = t4;
#line 28 "examples/csv/main.hero"
    t5 = false;
#line 28 "examples/csv/main.hero"
    h5_pending_quote = t5;
#line 29 "examples/csv/main.hero"
    t6 = false;
#line 29 "examples/csv/main.hero"
    h6_started = t6;
#line 31 "examples/csv/main.hero"
    t7 = h0_text;
#line 31 "examples/csv/main.hero"
    t8 = hero_str_chars(t7);
#line 31 "examples/csv/main.hero"
    t98 = h15_own15;
#line 31 "examples/csv/main.hero"
    h15_own15 = t8;
#line 351 "main.c"
    hero_array_decref(t98);
#line 31 "examples/csv/main.hero"
    t99 = h7_xs0;
#line 355 "main.c"
    hero_array_incref(t8);
#line 31 "examples/csv/main.hero"
    h7_xs0 = t8;
#line 359 "main.c"
    hero_array_decref(t99);
#line 31 "examples/csv/main.hero"
    t9 = INT64_C(0);
#line 31 "examples/csv/main.hero"
    h8_i0 = t9;
#line 31 "examples/csv/main.hero"
    goto bb1;
#line 31 "examples/csv/main.hero"
bb1:
#line 31 "examples/csv/main.hero"
    t10 = h8_i0;
#line 31 "examples/csv/main.hero"
    t11 = h7_xs0;
#line 31 "examples/csv/main.hero"
    t12 = hero_array_len(t11);
#line 31 "examples/csv/main.hero"
    t13 = t10 < t12;
#line 31 "examples/csv/main.hero"
    if (t13) goto bb2; else goto bb4;
#line 31 "examples/csv/main.hero"
bb2:
#line 31 "examples/csv/main.hero"
    t14 = h7_xs0;
#line 31 "examples/csv/main.hero"
    t15 = h8_i0;
#line 31 "examples/csv/main.hero"
    t16 = *(HeroStr const *)hero_array_at(t14, t15);
#line 31 "examples/csv/main.hero"
    t100 = h9_ch;
#line 389 "main.c"
    hero_str_incref(t16);
#line 31 "examples/csv/main.hero"
    h9_ch = t16;
#line 393 "main.c"
    hero_str_decref(t100);
#line 32 "examples/csv/main.hero"
    t17 = h5_pending_quote;
#line 32 "examples/csv/main.hero"
    if (t17) goto bb6; else goto bb7;
#line 32 "examples/csv/main.hero"
bb3:
#line 31 "examples/csv/main.hero"
    t63 = h8_i0;
#line 31 "examples/csv/main.hero"
    t64 = INT64_C(1);
#line 31 "examples/csv/main.hero"
    if (__builtin_add_overflow(t63, t64, &t65)) hero_panic_overflow();
#line 31 "examples/csv/main.hero"
    h8_i0 = t65;
#line 31 "examples/csv/main.hero"
    goto bb1;
#line 31 "examples/csv/main.hero"
bb4:
#line 72 "examples/csv/main.hero"
    t66 = h4_quoted;
#line 72 "examples/csv/main.hero"
    h10_b0 = t66;
#line 72 "examples/csv/main.hero"
    if (t66) goto bb27; else goto bb28;
#line 72 "examples/csv/main.hero"
bb5:
#line 41 "examples/csv/main.hero"
    t26 = h4_quoted;
#line 41 "examples/csv/main.hero"
    if (t26) goto bb12; else goto bb13;
#line 41 "examples/csv/main.hero"
bb6:
#line 33 "examples/csv/main.hero"
    t18 = false;
#line 33 "examples/csv/main.hero"
    h5_pending_quote = t18;
#line 35 "examples/csv/main.hero"
    t19 = h9_ch;
#line 35 "examples/csv/main.hero"
    t20 = HERO_STR_LIT(hero_str_22);
#line 35 "examples/csv/main.hero"
    t21 = hero_str_eq(t19, t20);
#line 35 "examples/csv/main.hero"
    if (t21) goto bb9; else goto bb10;
#line 35 "examples/csv/main.hero"
bb7:
#line 35 "examples/csv/main.hero"
    goto bb5;
#line 35 "examples/csv/main.hero"
bb8:
#line 39 "examples/csv/main.hero"
    t25 = false;
#line 39 "examples/csv/main.hero"
    h4_quoted = t25;
#line 39 "examples/csv/main.hero"
    goto bb5;
#line 39 "examples/csv/main.hero"
bb9:
#line 37 "examples/csv/main.hero"
    t22 = h3_field;
#line 37 "examples/csv/main.hero"
    t23 = HERO_STR_LIT(hero_str_22);
#line 37 "examples/csv/main.hero"
    t24 = hero_str_concat(t22, t23);
#line 37 "examples/csv/main.hero"
    t101 = h16_own16;
#line 37 "examples/csv/main.hero"
    h16_own16 = t24;
#line 463 "main.c"
    hero_str_decref(t101);
#line 37 "examples/csv/main.hero"
    t102 = h3_field;
#line 467 "main.c"
    hero_str_incref(t24);
#line 37 "examples/csv/main.hero"
    h3_field = t24;
#line 471 "main.c"
    hero_str_decref(t102);
    goto bb3;
bb10:
    goto bb8;
bb11:
#line 51 "examples/csv/main.hero"
    t34 = h9_ch;
#line 51 "examples/csv/main.hero"
    t35 = HERO_STR_LIT(hero_str_22);
#line 51 "examples/csv/main.hero"
    t36 = hero_str_eq(t34, t35);
#line 51 "examples/csv/main.hero"
    if (t36) goto bb18; else goto bb19;
#line 51 "examples/csv/main.hero"
bb12:
#line 42 "examples/csv/main.hero"
    t27 = h9_ch;
#line 42 "examples/csv/main.hero"
    t28 = HERO_STR_LIT(hero_str_22);
#line 42 "examples/csv/main.hero"
    t29 = hero_str_eq(t27, t28);
#line 42 "examples/csv/main.hero"
    if (t29) goto bb15; else goto bb16;
#line 42 "examples/csv/main.hero"
bb13:
#line 42 "examples/csv/main.hero"
    goto bb11;
#line 42 "examples/csv/main.hero"
bb14:
#line 42 "examples/csv/main.hero"
    goto bb3;
#line 42 "examples/csv/main.hero"
bb15:
#line 46 "examples/csv/main.hero"
    t30 = true;
#line 46 "examples/csv/main.hero"
    h5_pending_quote = t30;
#line 46 "examples/csv/main.hero"
    goto bb14;
#line 46 "examples/csv/main.hero"
bb16:
#line 48 "examples/csv/main.hero"
    t31 = h3_field;
#line 48 "examples/csv/main.hero"
    t32 = h9_ch;
#line 48 "examples/csv/main.hero"
    t33 = hero_str_concat(t31, t32);
#line 48 "examples/csv/main.hero"
    t103 = h17_own17;
#line 48 "examples/csv/main.hero"
    h17_own17 = t33;
#line 523 "main.c"
    hero_str_decref(t103);
#line 48 "examples/csv/main.hero"
    t104 = h3_field;
#line 527 "main.c"
    hero_str_incref(t33);
#line 48 "examples/csv/main.hero"
    h3_field = t33;
#line 531 "main.c"
    hero_str_decref(t104);
    goto bb14;
bb17:
#line 56 "examples/csv/main.hero"
    t39 = h9_ch;
#line 56 "examples/csv/main.hero"
    t40 = HERO_STR_LIT(hero_str_2c);
#line 56 "examples/csv/main.hero"
    t41 = hero_str_eq(t39, t40);
#line 56 "examples/csv/main.hero"
    if (t41) goto bb21; else goto bb22;
#line 56 "examples/csv/main.hero"
bb18:
#line 52 "examples/csv/main.hero"
    t37 = true;
#line 52 "examples/csv/main.hero"
    h4_quoted = t37;
#line 53 "examples/csv/main.hero"
    t38 = true;
#line 53 "examples/csv/main.hero"
    h6_started = t38;
#line 53 "examples/csv/main.hero"
    goto bb3;
#line 53 "examples/csv/main.hero"
bb19:
#line 53 "examples/csv/main.hero"
    goto bb17;
#line 53 "examples/csv/main.hero"
bb20:
#line 62 "examples/csv/main.hero"
    t47 = h9_ch;
#line 62 "examples/csv/main.hero"
    t48 = HERO_STR_LIT(hero_str_a);
#line 62 "examples/csv/main.hero"
    t49 = hero_str_eq(t47, t48);
#line 62 "examples/csv/main.hero"
    if (t49) goto bb24; else goto bb25;
#line 62 "examples/csv/main.hero"
bb21:
#line 57 "examples/csv/main.hero"
    t43 = h3_field;
#line 57 "examples/csv/main.hero"
    hero_array_push_owned(&h2_row, &t43);
#line 58 "examples/csv/main.hero"
    t45 = HERO_STR_LIT(hero_str_0);
#line 58 "examples/csv/main.hero"
    t105 = h3_field;
#line 579 "main.c"
    hero_str_incref(t45);
#line 58 "examples/csv/main.hero"
    h3_field = t45;
#line 583 "main.c"
    hero_str_decref(t105);
#line 59 "examples/csv/main.hero"
    t46 = true;
#line 59 "examples/csv/main.hero"
    h6_started = t46;
#line 59 "examples/csv/main.hero"
    goto bb3;
#line 59 "examples/csv/main.hero"
bb22:
#line 59 "examples/csv/main.hero"
    goto bb20;
#line 59 "examples/csv/main.hero"
bb23:
#line 69 "examples/csv/main.hero"
    t59 = h3_field;
#line 69 "examples/csv/main.hero"
    t60 = h9_ch;
#line 69 "examples/csv/main.hero"
    t61 = hero_str_concat(t59, t60);
#line 69 "examples/csv/main.hero"
    t106 = h18_own18;
#line 69 "examples/csv/main.hero"
    h18_own18 = t61;
#line 607 "main.c"
    hero_str_decref(t106);
#line 69 "examples/csv/main.hero"
    t107 = h3_field;
#line 611 "main.c"
    hero_str_incref(t61);
#line 69 "examples/csv/main.hero"
    h3_field = t61;
#line 615 "main.c"
    hero_str_decref(t107);
#line 70 "examples/csv/main.hero"
    t62 = true;
#line 70 "examples/csv/main.hero"
    h6_started = t62;
#line 70 "examples/csv/main.hero"
    goto bb3;
#line 70 "examples/csv/main.hero"
bb24:
#line 63 "examples/csv/main.hero"
    t51 = h3_field;
#line 63 "examples/csv/main.hero"
    hero_array_push_owned(&h2_row, &t51);
#line 64 "examples/csv/main.hero"
    t54 = h2_row;
#line 64 "examples/csv/main.hero"
    hero_array_push_owned(&h1_rows, &t54);
#line 65 "examples/csv/main.hero"
    t56 = hero_array_new(&hero_desc_str, 1);
#line 65 "examples/csv/main.hero"
    t108 = h19_own19;
#line 65 "examples/csv/main.hero"
    h19_own19 = t56;
#line 639 "main.c"
    hero_array_decref(t108);
#line 65 "examples/csv/main.hero"
    t109 = h2_row;
#line 643 "main.c"
    hero_array_incref(t56);
#line 65 "examples/csv/main.hero"
    h2_row = t56;
#line 647 "main.c"
    hero_array_decref(t109);
#line 66 "examples/csv/main.hero"
    t57 = HERO_STR_LIT(hero_str_0);
#line 66 "examples/csv/main.hero"
    t110 = h3_field;
#line 653 "main.c"
    hero_str_incref(t57);
#line 66 "examples/csv/main.hero"
    h3_field = t57;
#line 657 "main.c"
    hero_str_decref(t110);
#line 67 "examples/csv/main.hero"
    t58 = false;
#line 67 "examples/csv/main.hero"
    h6_started = t58;
#line 67 "examples/csv/main.hero"
    goto bb3;
#line 67 "examples/csv/main.hero"
bb25:
#line 67 "examples/csv/main.hero"
    goto bb23;
#line 67 "examples/csv/main.hero"
bb26:
#line 77 "examples/csv/main.hero"
    t73 = h6_started;
#line 77 "examples/csv/main.hero"
    h12_b2 = t73;
#line 77 "examples/csv/main.hero"
    if (t73) goto bb33; else goto bb32;
#line 77 "examples/csv/main.hero"
bb27:
#line 72 "examples/csv/main.hero"
    t67 = h5_pending_quote;
#line 72 "examples/csv/main.hero"
    t68 = !t67;
#line 72 "examples/csv/main.hero"
    h10_b0 = t68;
#line 72 "examples/csv/main.hero"
    goto bb28;
#line 72 "examples/csv/main.hero"
bb28:
#line 72 "examples/csv/main.hero"
    t69 = h10_b0;
#line 72 "examples/csv/main.hero"
    if (t69) goto bb29; else goto bb30;
#line 72 "examples/csv/main.hero"
bb29:
#line 73 "examples/csv/main.hero"
    t70 = HERO_STR_LIT(hero_str_41de4fd4);
#line 73 "examples/csv/main.hero"
    t71 = HERO_STR_LIT(hero_str_6147841e);
#line 699 "main.c"
    hero_str_incref(t70);
#line 73 "examples/csv/main.hero"
#line 702 "main.c"
    hero_str_incref(t71);
#line 73 "examples/csv/main.hero"
    t72 = (h_0opt_755e4b59){.tag = INT64_C(1), .as.err = {.code = t70, .msg = t71}};
#line 73 "examples/csv/main.hero"
    t111 = h20_own20;
#line 73 "examples/csv/main.hero"
    h20_own20 = t72;
#line 710 "main.c"
    h_0opt_755e4b59_release(&t111);
#line 73 "examples/csv/main.hero"
#line 713 "main.c"
    h_0opt_755e4b59_retain(&t72);
#line 73 "examples/csv/main.hero"
#line 716 "main.c"
    hero_array_decref(h1_rows);
#line 73 "examples/csv/main.hero"
#line 719 "main.c"
    hero_array_decref(h2_row);
#line 73 "examples/csv/main.hero"
#line 722 "main.c"
    hero_str_decref(h3_field);
#line 73 "examples/csv/main.hero"
#line 725 "main.c"
    hero_array_decref(h7_xs0);
#line 73 "examples/csv/main.hero"
#line 728 "main.c"
    hero_str_decref(h9_ch);
#line 73 "examples/csv/main.hero"
#line 731 "main.c"
    hero_array_decref(h13_own13);
#line 73 "examples/csv/main.hero"
#line 734 "main.c"
    hero_array_decref(h14_own14);
#line 73 "examples/csv/main.hero"
#line 737 "main.c"
    hero_array_decref(h15_own15);
#line 73 "examples/csv/main.hero"
#line 740 "main.c"
    hero_str_decref(h16_own16);
#line 73 "examples/csv/main.hero"
#line 743 "main.c"
    hero_str_decref(h17_own17);
#line 73 "examples/csv/main.hero"
#line 746 "main.c"
    hero_str_decref(h18_own18);
#line 73 "examples/csv/main.hero"
#line 749 "main.c"
    hero_array_decref(h19_own19);
#line 73 "examples/csv/main.hero"
#line 752 "main.c"
    h_0opt_755e4b59_release(&h20_own20);
#line 73 "examples/csv/main.hero"
#line 755 "main.c"
    h_main_Table_release(&h21_own21);
#line 73 "examples/csv/main.hero"
#line 758 "main.c"
    h_0opt_755e4b59_release(&h22_own22);
    return t72;
bb30:
    goto bb26;
bb31:
#line 81 "examples/csv/main.hero"
    t90 = h1_rows;
#line 766 "main.c"
    hero_array_incref(t90);
#line 81 "examples/csv/main.hero"
    t91 = (h_main_Table){.f_rows = t90};
#line 81 "examples/csv/main.hero"
    t112 = h21_own21;
#line 81 "examples/csv/main.hero"
    h21_own21 = t91;
#line 774 "main.c"
    h_main_Table_release(&t112);
#line 81 "examples/csv/main.hero"
#line 777 "main.c"
    h_main_Table_retain(&t91);
#line 81 "examples/csv/main.hero"
    t92 = (h_0opt_755e4b59){.tag = INT64_C(0), .as.ok = t91};
#line 81 "examples/csv/main.hero"
    t113 = h22_own22;
#line 81 "examples/csv/main.hero"
    h22_own22 = t92;
#line 785 "main.c"
    h_0opt_755e4b59_release(&t113);
#line 81 "examples/csv/main.hero"
#line 788 "main.c"
    h_0opt_755e4b59_retain(&t92);
#line 81 "examples/csv/main.hero"
#line 791 "main.c"
    hero_array_decref(h1_rows);
#line 81 "examples/csv/main.hero"
#line 794 "main.c"
    hero_array_decref(h2_row);
#line 81 "examples/csv/main.hero"
#line 797 "main.c"
    hero_str_decref(h3_field);
#line 81 "examples/csv/main.hero"
#line 800 "main.c"
    hero_array_decref(h7_xs0);
#line 81 "examples/csv/main.hero"
#line 803 "main.c"
    hero_str_decref(h9_ch);
#line 81 "examples/csv/main.hero"
#line 806 "main.c"
    hero_array_decref(h13_own13);
#line 81 "examples/csv/main.hero"
#line 809 "main.c"
    hero_array_decref(h14_own14);
#line 81 "examples/csv/main.hero"
#line 812 "main.c"
    hero_array_decref(h15_own15);
#line 81 "examples/csv/main.hero"
#line 815 "main.c"
    hero_str_decref(h16_own16);
#line 81 "examples/csv/main.hero"
#line 818 "main.c"
    hero_str_decref(h17_own17);
#line 81 "examples/csv/main.hero"
#line 821 "main.c"
    hero_str_decref(h18_own18);
#line 81 "examples/csv/main.hero"
#line 824 "main.c"
    hero_array_decref(h19_own19);
#line 81 "examples/csv/main.hero"
#line 827 "main.c"
    h_0opt_755e4b59_release(&h20_own20);
#line 81 "examples/csv/main.hero"
#line 830 "main.c"
    h_main_Table_release(&h21_own21);
#line 81 "examples/csv/main.hero"
#line 833 "main.c"
    h_0opt_755e4b59_release(&h22_own22);
    return t92;
bb32:
#line 77 "examples/csv/main.hero"
    t74 = h3_field;
#line 77 "examples/csv/main.hero"
    t75 = hero_str_len(t74);
#line 77 "examples/csv/main.hero"
    t76 = INT64_C(0);
#line 77 "examples/csv/main.hero"
    t77 = t75 > t76;
#line 77 "examples/csv/main.hero"
    h12_b2 = t77;
#line 77 "examples/csv/main.hero"
    goto bb33;
#line 77 "examples/csv/main.hero"
bb33:
#line 77 "examples/csv/main.hero"
    t78 = h12_b2;
#line 77 "examples/csv/main.hero"
    h11_b1 = t78;
#line 77 "examples/csv/main.hero"
    if (t78) goto bb35; else goto bb34;
#line 77 "examples/csv/main.hero"
bb34:
#line 77 "examples/csv/main.hero"
    t79 = h2_row;
#line 77 "examples/csv/main.hero"
    t80 = hero_array_len(t79);
#line 77 "examples/csv/main.hero"
    t81 = INT64_C(0);
#line 77 "examples/csv/main.hero"
    t82 = t80 > t81;
#line 77 "examples/csv/main.hero"
    h11_b1 = t82;
#line 77 "examples/csv/main.hero"
    goto bb35;
#line 77 "examples/csv/main.hero"
bb35:
#line 77 "examples/csv/main.hero"
    t83 = h11_b1;
#line 77 "examples/csv/main.hero"
    if (t83) goto bb36; else goto bb37;
#line 77 "examples/csv/main.hero"
bb36:
#line 78 "examples/csv/main.hero"
    t85 = h3_field;
#line 78 "examples/csv/main.hero"
    hero_array_push_owned(&h2_row, &t85);
#line 79 "examples/csv/main.hero"
    t88 = h2_row;
#line 79 "examples/csv/main.hero"
    hero_array_push_owned(&h1_rows, &t88);
#line 79 "examples/csv/main.hero"
    goto bb31;
#line 79 "examples/csv/main.hero"
bb37:
#line 79 "examples/csv/main.hero"
    goto bb31;
#line 893 "main.c"
}

#line 83 "examples/csv/main.hero"
int64_t h_main_width(h_main_Table h0_t) {
#line 898 "main.c"
    int64_t h1_r0;
    h_main_Table t1 = {0};
    HeroArrayHeader * t2 = {0};
    int64_t t3;
    int64_t t4;
    bool t5;
    int64_t t6;
    h_main_Table t7 = {0};
    HeroArrayHeader * t8 = {0};
    int64_t t9;
    HeroArrayHeader * t10 = {0};
    int64_t t11;
    int64_t t12;
    goto bb0;
bb0:
#line 84 "examples/csv/main.hero"
    t1 = h0_t;
#line 84 "examples/csv/main.hero"
    t2 = t1.f_rows;
#line 84 "examples/csv/main.hero"
    t3 = hero_array_len(t2);
#line 84 "examples/csv/main.hero"
    t4 = INT64_C(0);
#line 84 "examples/csv/main.hero"
    t5 = t3 == t4;
#line 84 "examples/csv/main.hero"
    if (t5) goto bb2; else goto bb3;
#line 84 "examples/csv/main.hero"
bb1:
#line 84 "examples/csv/main.hero"
    t12 = h1_r0;
#line 84 "examples/csv/main.hero"
    return t12;
#line 84 "examples/csv/main.hero"
bb2:
#line 85 "examples/csv/main.hero"
    t6 = INT64_C(0);
#line 84 "examples/csv/main.hero"
    h1_r0 = t6;
#line 84 "examples/csv/main.hero"
    goto bb1;
#line 84 "examples/csv/main.hero"
bb3:
#line 87 "examples/csv/main.hero"
    t7 = h0_t;
#line 87 "examples/csv/main.hero"
    t8 = t7.f_rows;
#line 87 "examples/csv/main.hero"
    t9 = INT64_C(0);
#line 87 "examples/csv/main.hero"
    t10 = *(HeroArrayHeader * const *)hero_array_at(t8, t9);
#line 87 "examples/csv/main.hero"
    t11 = hero_array_len(t10);
#line 84 "examples/csv/main.hero"
    h1_r0 = t11;
#line 84 "examples/csv/main.hero"
    goto bb1;
#line 956 "main.c"
}

#line 91 "examples/csv/main.hero"
bool h_main_rectangular(h_main_Table h0_t) {
#line 961 "main.c"
    HeroArrayHeader * h1_xs0 = {0};
    int64_t h2_i0;
    HeroArrayHeader * h3_one = {0};
    h_main_Table t1 = {0};
    HeroArrayHeader * t2 = {0};
    int64_t t3;
    int64_t t4;
    HeroArrayHeader * t5 = {0};
    int64_t t6;
    bool t7;
    HeroArrayHeader * t8 = {0};
    int64_t t9;
    HeroArrayHeader * t10 = {0};
    HeroArrayHeader * t11 = {0};
    int64_t t12;
    h_main_Table t13 = {0};
    int64_t t14;
    bool t15;
    bool t16;
    int64_t t17;
    int64_t t18;
    int64_t t19;
    bool t20;
    HeroArrayHeader * t21 = {0};
    HeroArrayHeader * t22 = {0};
    goto bb0;
bb0:
#line 92 "examples/csv/main.hero"
    t1 = h0_t;
#line 92 "examples/csv/main.hero"
    t2 = t1.f_rows;
#line 92 "examples/csv/main.hero"
    t21 = h1_xs0;
#line 995 "main.c"
    hero_array_incref(t2);
#line 92 "examples/csv/main.hero"
    h1_xs0 = t2;
#line 999 "main.c"
    hero_array_decref(t21);
#line 92 "examples/csv/main.hero"
    t3 = INT64_C(0);
#line 92 "examples/csv/main.hero"
    h2_i0 = t3;
#line 92 "examples/csv/main.hero"
    goto bb1;
#line 92 "examples/csv/main.hero"
bb1:
#line 92 "examples/csv/main.hero"
    t4 = h2_i0;
#line 92 "examples/csv/main.hero"
    t5 = h1_xs0;
#line 92 "examples/csv/main.hero"
    t6 = hero_array_len(t5);
#line 92 "examples/csv/main.hero"
    t7 = t4 < t6;
#line 92 "examples/csv/main.hero"
    if (t7) goto bb2; else goto bb4;
#line 92 "examples/csv/main.hero"
bb2:
#line 92 "examples/csv/main.hero"
    t8 = h1_xs0;
#line 92 "examples/csv/main.hero"
    t9 = h2_i0;
#line 92 "examples/csv/main.hero"
    t10 = *(HeroArrayHeader * const *)hero_array_at(t8, t9);
#line 92 "examples/csv/main.hero"
    t22 = h3_one;
#line 1029 "main.c"
    hero_array_incref(t10);
#line 92 "examples/csv/main.hero"
    h3_one = t10;
#line 1033 "main.c"
    hero_array_decref(t22);
#line 93 "examples/csv/main.hero"
    t11 = h3_one;
#line 93 "examples/csv/main.hero"
    t12 = hero_array_len(t11);
#line 93 "examples/csv/main.hero"
    t13 = h0_t;
#line 93 "examples/csv/main.hero"
    t14 = h_main_width(t13);
#line 93 "examples/csv/main.hero"
    t15 = t12 != t14;
#line 93 "examples/csv/main.hero"
    if (t15) goto bb6; else goto bb7;
#line 93 "examples/csv/main.hero"
bb3:
#line 92 "examples/csv/main.hero"
    t17 = h2_i0;
#line 92 "examples/csv/main.hero"
    t18 = INT64_C(1);
#line 92 "examples/csv/main.hero"
    if (__builtin_add_overflow(t17, t18, &t19)) hero_panic_overflow();
#line 92 "examples/csv/main.hero"
    h2_i0 = t19;
#line 92 "examples/csv/main.hero"
    goto bb1;
#line 92 "examples/csv/main.hero"
bb4:
#line 96 "examples/csv/main.hero"
    t20 = true;
#line 1063 "main.c"
    hero_array_decref(h1_xs0);
#line 96 "examples/csv/main.hero"
#line 1066 "main.c"
    hero_array_decref(h3_one);
    return t20;
bb5:
    goto bb3;
bb6:
#line 94 "examples/csv/main.hero"
    t16 = false;
#line 1074 "main.c"
    hero_array_decref(h1_xs0);
#line 94 "examples/csv/main.hero"
#line 1077 "main.c"
    hero_array_decref(h3_one);
    return t16;
bb7:
    goto bb5;
}

#line 98 "examples/csv/main.hero"
h_0opt_5a58f2ca h_main_column(h_main_Table h0_t, int64_t h1_at) {
#line 1086 "main.c"
    bool h2_b0;
    HeroArrayHeader * h3_out = {0};
    HeroArrayHeader * h4_xs0 = {0};
    int64_t h5_i0;
    HeroArrayHeader * h6_one = {0};
    HeroArrayHeader * h7_own7 = {0};
    h_0opt_5a58f2ca h8_own8 = {0};
    h_0opt_5a58f2ca h9_own9 = {0};
    int64_t t1;
    int64_t t2;
    bool t3;
    int64_t t4;
    h_main_Table t5 = {0};
    int64_t t6;
    bool t7;
    bool t8;
    HeroStr t9 = {0};
    HeroStr t10 = {0};
    h_0opt_5a58f2ca t11 = {0};
    HeroArrayHeader * t12 = {0};
    h_main_Table t13 = {0};
    HeroArrayHeader * t14 = {0};
    int64_t t15;
    int64_t t16;
    HeroArrayHeader * t17 = {0};
    int64_t t18;
    bool t19;
    HeroArrayHeader * t20 = {0};
    int64_t t21;
    HeroArrayHeader * t22 = {0};
    int64_t t23;
    HeroArrayHeader * t24 = {0};
    int64_t t25;
    bool t26;
    HeroArrayHeader * t28 = {0};
    int64_t t29;
    HeroStr t30 = {0};
    int64_t t32;
    int64_t t33;
    int64_t t34;
    HeroArrayHeader * t35 = {0};
    h_0opt_5a58f2ca t36 = {0};
    HeroArrayHeader * t37 = {0};
    HeroArrayHeader * t38 = {0};
    HeroArrayHeader * t39 = {0};
    h_0opt_5a58f2ca t40 = {0};
    HeroArrayHeader * t41 = {0};
    h_0opt_5a58f2ca t42 = {0};
    goto bb0;
bb0:
#line 99 "examples/csv/main.hero"
    t1 = h1_at;
#line 99 "examples/csv/main.hero"
    t2 = INT64_C(0);
#line 99 "examples/csv/main.hero"
    t3 = t1 < t2;
#line 99 "examples/csv/main.hero"
    h2_b0 = t3;
#line 99 "examples/csv/main.hero"
    if (t3) goto bb3; else goto bb2;
#line 99 "examples/csv/main.hero"
bb1:
#line 101 "examples/csv/main.hero"
    t12 = hero_array_new(&hero_desc_str, 1);
#line 101 "examples/csv/main.hero"
    t37 = h7_own7;
#line 101 "examples/csv/main.hero"
    h7_own7 = t12;
#line 1155 "main.c"
    hero_array_decref(t37);
#line 101 "examples/csv/main.hero"
    t38 = h3_out;
#line 1159 "main.c"
    hero_array_incref(t12);
#line 101 "examples/csv/main.hero"
    h3_out = t12;
#line 1163 "main.c"
    hero_array_decref(t38);
#line 103 "examples/csv/main.hero"
    t13 = h0_t;
#line 103 "examples/csv/main.hero"
    t14 = t13.f_rows;
#line 103 "examples/csv/main.hero"
    t39 = h4_xs0;
#line 1171 "main.c"
    hero_array_incref(t14);
#line 103 "examples/csv/main.hero"
    h4_xs0 = t14;
#line 1175 "main.c"
    hero_array_decref(t39);
#line 103 "examples/csv/main.hero"
    t15 = INT64_C(0);
#line 103 "examples/csv/main.hero"
    h5_i0 = t15;
#line 103 "examples/csv/main.hero"
    goto bb6;
#line 103 "examples/csv/main.hero"
bb2:
#line 99 "examples/csv/main.hero"
    t4 = h1_at;
#line 99 "examples/csv/main.hero"
    t5 = h0_t;
#line 99 "examples/csv/main.hero"
    t6 = h_main_width(t5);
#line 99 "examples/csv/main.hero"
    t7 = t4 >= t6;
#line 99 "examples/csv/main.hero"
    h2_b0 = t7;
#line 99 "examples/csv/main.hero"
    goto bb3;
#line 99 "examples/csv/main.hero"
bb3:
#line 99 "examples/csv/main.hero"
    t8 = h2_b0;
#line 99 "examples/csv/main.hero"
    if (t8) goto bb4; else goto bb5;
#line 99 "examples/csv/main.hero"
bb4:
#line 100 "examples/csv/main.hero"
    t9 = HERO_STR_LIT(hero_str_688477b1);
#line 100 "examples/csv/main.hero"
    t10 = HERO_STR_LIT(hero_str_5921dbd5);
#line 1209 "main.c"
    hero_str_incref(t9);
#line 100 "examples/csv/main.hero"
#line 1212 "main.c"
    hero_str_incref(t10);
#line 100 "examples/csv/main.hero"
    t11 = (h_0opt_5a58f2ca){.tag = INT64_C(1), .as.err = {.code = t9, .msg = t10}};
#line 100 "examples/csv/main.hero"
    t40 = h8_own8;
#line 100 "examples/csv/main.hero"
    h8_own8 = t11;
#line 1220 "main.c"
    h_0opt_5a58f2ca_release(&t40);
#line 100 "examples/csv/main.hero"
#line 1223 "main.c"
    h_0opt_5a58f2ca_retain(&t11);
#line 100 "examples/csv/main.hero"
#line 1226 "main.c"
    hero_array_decref(h3_out);
#line 100 "examples/csv/main.hero"
#line 1229 "main.c"
    hero_array_decref(h4_xs0);
#line 100 "examples/csv/main.hero"
#line 1232 "main.c"
    hero_array_decref(h6_one);
#line 100 "examples/csv/main.hero"
#line 1235 "main.c"
    hero_array_decref(h7_own7);
#line 100 "examples/csv/main.hero"
#line 1238 "main.c"
    h_0opt_5a58f2ca_release(&h8_own8);
#line 100 "examples/csv/main.hero"
#line 1241 "main.c"
    h_0opt_5a58f2ca_release(&h9_own9);
    return t11;
bb5:
    goto bb1;
bb6:
#line 103 "examples/csv/main.hero"
    t16 = h5_i0;
#line 103 "examples/csv/main.hero"
    t17 = h4_xs0;
#line 103 "examples/csv/main.hero"
    t18 = hero_array_len(t17);
#line 103 "examples/csv/main.hero"
    t19 = t16 < t18;
#line 103 "examples/csv/main.hero"
    if (t19) goto bb7; else goto bb9;
#line 103 "examples/csv/main.hero"
bb7:
#line 103 "examples/csv/main.hero"
    t20 = h4_xs0;
#line 103 "examples/csv/main.hero"
    t21 = h5_i0;
#line 103 "examples/csv/main.hero"
    t22 = *(HeroArrayHeader * const *)hero_array_at(t20, t21);
#line 103 "examples/csv/main.hero"
    t41 = h6_one;
#line 1267 "main.c"
    hero_array_incref(t22);
#line 103 "examples/csv/main.hero"
    h6_one = t22;
#line 1271 "main.c"
    hero_array_decref(t41);
#line 104 "examples/csv/main.hero"
    t23 = h1_at;
#line 104 "examples/csv/main.hero"
    t24 = h6_one;
#line 104 "examples/csv/main.hero"
    t25 = hero_array_len(t24);
#line 104 "examples/csv/main.hero"
    t26 = t23 < t25;
#line 104 "examples/csv/main.hero"
    if (t26) goto bb11; else goto bb12;
#line 104 "examples/csv/main.hero"
bb8:
#line 103 "examples/csv/main.hero"
    t32 = h5_i0;
#line 103 "examples/csv/main.hero"
    t33 = INT64_C(1);
#line 103 "examples/csv/main.hero"
    if (__builtin_add_overflow(t32, t33, &t34)) hero_panic_overflow();
#line 103 "examples/csv/main.hero"
    h5_i0 = t34;
#line 103 "examples/csv/main.hero"
    goto bb6;
#line 103 "examples/csv/main.hero"
bb9:
#line 107 "examples/csv/main.hero"
    t35 = h3_out;
#line 1299 "main.c"
    hero_array_incref(t35);
#line 107 "examples/csv/main.hero"
    t36 = (h_0opt_5a58f2ca){.tag = INT64_C(0), .as.ok = t35};
#line 107 "examples/csv/main.hero"
    t42 = h9_own9;
#line 107 "examples/csv/main.hero"
    h9_own9 = t36;
#line 1307 "main.c"
    h_0opt_5a58f2ca_release(&t42);
#line 107 "examples/csv/main.hero"
#line 1310 "main.c"
    h_0opt_5a58f2ca_retain(&t36);
#line 107 "examples/csv/main.hero"
#line 1313 "main.c"
    hero_array_decref(h3_out);
#line 107 "examples/csv/main.hero"
#line 1316 "main.c"
    hero_array_decref(h4_xs0);
#line 107 "examples/csv/main.hero"
#line 1319 "main.c"
    hero_array_decref(h6_one);
#line 107 "examples/csv/main.hero"
#line 1322 "main.c"
    hero_array_decref(h7_own7);
#line 107 "examples/csv/main.hero"
#line 1325 "main.c"
    h_0opt_5a58f2ca_release(&h8_own8);
#line 107 "examples/csv/main.hero"
#line 1328 "main.c"
    h_0opt_5a58f2ca_release(&h9_own9);
    return t36;
bb10:
    goto bb8;
bb11:
#line 105 "examples/csv/main.hero"
    t28 = h6_one;
#line 105 "examples/csv/main.hero"
    t29 = h1_at;
#line 105 "examples/csv/main.hero"
    t30 = *(HeroStr const *)hero_array_at(t28, t29);
#line 105 "examples/csv/main.hero"
    hero_array_push_owned(&h3_out, &t30);
#line 105 "examples/csv/main.hero"
    goto bb10;
#line 105 "examples/csv/main.hero"
bb12:
#line 105 "examples/csv/main.hero"
    goto bb10;
#line 1348 "main.c"
}

#line 109 "examples/csv/main.hero"
HeroStr h_main_SAMPLE(void) {
#line 1353 "main.c"
    HeroStr t1 = {0};
    goto bb0;
bb0:
#line 110 "examples/csv/main.hero"
    t1 = HERO_STR_LIT(hero_str_690861d0);
#line 1359 "main.c"
    hero_str_incref(t1);
    return t1;
}

#line 112 "examples/csv/main.hero"
void h_main_main(void) {
#line 1366 "main.c"
    h_0opt_755e4b59 h0_f0 = {0};
    h_main_Table h1_table = {0};
    h_0opt_5a58f2ca h2_f1 = {0};
    h_0opt_5a58f2ca h3_f2 = {0};
    h_0opt_755e4b59 h4_f3 = {0};
    h_0opt_755e4b59 h5_f4 = {0};
    HeroStr h6_own6 = {0};
    h_0opt_755e4b59 h7_own7 = {0};
    HeroStr h8_own8 = {0};
    HeroStr h9_own9 = {0};
    h_0opt_5a58f2ca h10_own10 = {0};
    HeroStr h11_own11 = {0};
    h_0opt_5a58f2ca h12_own12 = {0};
    h_0opt_755e4b59 h13_own13 = {0};
    h_0opt_755e4b59 h14_own14 = {0};
    HeroStr t1 = {0};
    h_0opt_755e4b59 t2 = {0};
    h_0opt_755e4b59 t3 = {0};
    int64_t t4;
    int64_t t5;
    bool t6;
    h_0opt_755e4b59 t7 = {0};
    HeroFailure t8 = {0};
    h_0opt_755e4b59 t9 = {0};
    h_main_Table t10 = {0};
    h_main_Table t11 = {0};
    HeroArrayHeader * t12 = {0};
    int64_t t13;
    h_main_Table t14 = {0};
    int64_t t15;
    h_main_Table t16 = {0};
    bool t17;
    h_main_Table t18 = {0};
    HeroArrayHeader * t19 = {0};
    int64_t t20;
    HeroArrayHeader * t21 = {0};
    HeroStr t22 = {0};
    HeroStr t23 = {0};
    h_main_Table t24 = {0};
    HeroArrayHeader * t25 = {0};
    int64_t t26;
    HeroArrayHeader * t27 = {0};
    HeroStr t28 = {0};
    HeroStr t29 = {0};
    h_main_Table t30 = {0};
    int64_t t31;
    h_0opt_5a58f2ca t32 = {0};
    h_0opt_5a58f2ca t33 = {0};
    int64_t t34;
    int64_t t35;
    bool t36;
    h_0opt_5a58f2ca t37 = {0};
    HeroFailure t38 = {0};
    h_0opt_5a58f2ca t39 = {0};
    HeroArrayHeader * t40 = {0};
    HeroStr t41 = {0};
    HeroStr t42 = {0};
    h_main_Table t43 = {0};
    int64_t t44;
    h_0opt_5a58f2ca t45 = {0};
    h_0opt_5a58f2ca t46 = {0};
    int64_t t47;
    int64_t t48;
    bool t49;
    HeroStr t50 = {0};
    h_0opt_755e4b59 t51 = {0};
    h_0opt_755e4b59 t52 = {0};
    int64_t t53;
    int64_t t54;
    bool t55;
    HeroStr t56 = {0};
    h_0opt_755e4b59 t57 = {0};
    h_0opt_755e4b59 t58 = {0};
    int64_t t59;
    int64_t t60;
    bool t61;
    h_0opt_755e4b59 t62 = {0};
    HeroFailure t63 = {0};
    h_0opt_755e4b59 t64 = {0};
    h_main_Table t65 = {0};
    HeroArrayHeader * t66 = {0};
    int64_t t67;
    HeroStr t68 = {0};
    h_0opt_755e4b59 t69 = {0};
    h_0opt_755e4b59 t70 = {0};
    h_main_Table t71 = {0};
    HeroStr t72 = {0};
    HeroStr t73 = {0};
    h_0opt_5a58f2ca t74 = {0};
    h_0opt_5a58f2ca t75 = {0};
    HeroStr t76 = {0};
    h_0opt_5a58f2ca t77 = {0};
    h_0opt_5a58f2ca t78 = {0};
    h_0opt_755e4b59 t79 = {0};
    h_0opt_755e4b59 t80 = {0};
    h_0opt_755e4b59 t81 = {0};
    h_0opt_755e4b59 t82 = {0};
    goto bb0;
bb0:
#line 113 "examples/csv/main.hero"
    t1 = h_main_SAMPLE();
#line 113 "examples/csv/main.hero"
    t68 = h6_own6;
#line 113 "examples/csv/main.hero"
    h6_own6 = t1;
#line 1472 "main.c"
    hero_str_decref(t68);
#line 113 "examples/csv/main.hero"
    t2 = h_main_parse(t1);
#line 113 "examples/csv/main.hero"
    t69 = h7_own7;
#line 113 "examples/csv/main.hero"
    h7_own7 = t2;
#line 1480 "main.c"
    h_0opt_755e4b59_release(&t69);
#line 113 "examples/csv/main.hero"
    t70 = h0_f0;
#line 1484 "main.c"
    h_0opt_755e4b59_retain(&t2);
#line 113 "examples/csv/main.hero"
    h0_f0 = t2;
#line 1488 "main.c"
    h_0opt_755e4b59_release(&t70);
#line 113 "examples/csv/main.hero"
    t3 = h0_f0;
#line 113 "examples/csv/main.hero"
    t4 = t3.tag;
#line 113 "examples/csv/main.hero"
    t5 = INT64_C(0);
#line 113 "examples/csv/main.hero"
    t6 = t4 == t5;
#line 113 "examples/csv/main.hero"
    if (t6) goto bb1; else goto bb2;
#line 113 "examples/csv/main.hero"
bb1:
#line 113 "examples/csv/main.hero"
    t9 = h0_f0;
#line 113 "examples/csv/main.hero"
    t10 = t9.as.ok;
#line 113 "examples/csv/main.hero"
    t71 = h1_table;
#line 1508 "main.c"
    h_main_Table_retain(&t10);
#line 113 "examples/csv/main.hero"
    h1_table = t10;
#line 1512 "main.c"
    h_main_Table_release(&t71);
#line 114 "examples/csv/main.hero"
    t11 = h1_table;
#line 114 "examples/csv/main.hero"
    t12 = t11.f_rows;
#line 114 "examples/csv/main.hero"
    t13 = hero_array_len(t12);
#line 114 "examples/csv/main.hero"
    hero_print_int(t13);
#line 114 "examples/csv/main.hero"
    hero_print_end();
#line 115 "examples/csv/main.hero"
    t14 = h1_table;
#line 115 "examples/csv/main.hero"
    t15 = h_main_width(t14);
#line 115 "examples/csv/main.hero"
    hero_print_int(t15);
#line 115 "examples/csv/main.hero"
    hero_print_end();
#line 116 "examples/csv/main.hero"
    t16 = h1_table;
#line 116 "examples/csv/main.hero"
    t17 = h_main_rectangular(t16);
#line 116 "examples/csv/main.hero"
    hero_print_bool(t17);
#line 116 "examples/csv/main.hero"
    hero_print_end();
#line 118 "examples/csv/main.hero"
    t18 = h1_table;
#line 118 "examples/csv/main.hero"
    t19 = t18.f_rows;
#line 118 "examples/csv/main.hero"
    t20 = INT64_C(1);
#line 118 "examples/csv/main.hero"
    t21 = *(HeroArrayHeader * const *)hero_array_at(t19, t20);
#line 118 "examples/csv/main.hero"
    t22 = HERO_STR_LIT(hero_str_8a0b4);
#line 118 "examples/csv/main.hero"
    t23 = hero_str_join(t21, t22);
#line 118 "examples/csv/main.hero"
    t72 = h8_own8;
#line 118 "examples/csv/main.hero"
    h8_own8 = t23;
#line 1556 "main.c"
    hero_str_decref(t72);
#line 118 "examples/csv/main.hero"
    hero_print_str(t23);
#line 118 "examples/csv/main.hero"
    hero_print_end();
#line 119 "examples/csv/main.hero"
    t24 = h1_table;
#line 119 "examples/csv/main.hero"
    t25 = t24.f_rows;
#line 119 "examples/csv/main.hero"
    t26 = INT64_C(2);
#line 119 "examples/csv/main.hero"
    t27 = *(HeroArrayHeader * const *)hero_array_at(t25, t26);
#line 119 "examples/csv/main.hero"
    t28 = HERO_STR_LIT(hero_str_8a0b4);
#line 119 "examples/csv/main.hero"
    t29 = hero_str_join(t27, t28);
#line 119 "examples/csv/main.hero"
    t73 = h9_own9;
#line 119 "examples/csv/main.hero"
    h9_own9 = t29;
#line 1578 "main.c"
    hero_str_decref(t73);
#line 119 "examples/csv/main.hero"
    hero_print_str(t29);
#line 119 "examples/csv/main.hero"
    hero_print_end();
#line 120 "examples/csv/main.hero"
    t30 = h1_table;
#line 120 "examples/csv/main.hero"
    t31 = INT64_C(0);
#line 120 "examples/csv/main.hero"
    t32 = h_main_column(t30, t31);
#line 120 "examples/csv/main.hero"
    t74 = h10_own10;
#line 120 "examples/csv/main.hero"
    h10_own10 = t32;
#line 1594 "main.c"
    h_0opt_5a58f2ca_release(&t74);
#line 120 "examples/csv/main.hero"
    t75 = h2_f1;
#line 1598 "main.c"
    h_0opt_5a58f2ca_retain(&t32);
#line 120 "examples/csv/main.hero"
    h2_f1 = t32;
#line 1602 "main.c"
    h_0opt_5a58f2ca_release(&t75);
#line 120 "examples/csv/main.hero"
    t33 = h2_f1;
#line 120 "examples/csv/main.hero"
    t34 = t33.tag;
#line 120 "examples/csv/main.hero"
    t35 = INT64_C(0);
#line 120 "examples/csv/main.hero"
    t36 = t34 == t35;
#line 120 "examples/csv/main.hero"
    if (t36) goto bb3; else goto bb4;
#line 120 "examples/csv/main.hero"
bb2:
#line 113 "examples/csv/main.hero"
    t7 = h0_f0;
#line 113 "examples/csv/main.hero"
    t8 = t7.as.err;
#line 1620 "main.c"
    hero_panic_must(t8);
    hero_unreachable();
bb3:
#line 120 "examples/csv/main.hero"
    t39 = h2_f1;
#line 120 "examples/csv/main.hero"
    t40 = t39.as.ok;
#line 120 "examples/csv/main.hero"
    t41 = HERO_STR_LIT(hero_str_2c);
#line 120 "examples/csv/main.hero"
    t42 = hero_str_join(t40, t41);
#line 120 "examples/csv/main.hero"
    t76 = h11_own11;
#line 120 "examples/csv/main.hero"
    h11_own11 = t42;
#line 1636 "main.c"
    hero_str_decref(t76);
#line 120 "examples/csv/main.hero"
    hero_print_str(t42);
#line 120 "examples/csv/main.hero"
    hero_print_end();
#line 121 "examples/csv/main.hero"
    t43 = h1_table;
#line 121 "examples/csv/main.hero"
    t44 = INT64_C(9);
#line 121 "examples/csv/main.hero"
    t45 = h_main_column(t43, t44);
#line 121 "examples/csv/main.hero"
    t77 = h12_own12;
#line 121 "examples/csv/main.hero"
    h12_own12 = t45;
#line 1652 "main.c"
    h_0opt_5a58f2ca_release(&t77);
#line 121 "examples/csv/main.hero"
    t78 = h3_f2;
#line 1656 "main.c"
    h_0opt_5a58f2ca_retain(&t45);
#line 121 "examples/csv/main.hero"
    h3_f2 = t45;
#line 1660 "main.c"
    h_0opt_5a58f2ca_release(&t78);
#line 121 "examples/csv/main.hero"
    t46 = h3_f2;
#line 121 "examples/csv/main.hero"
    t47 = t46.tag;
#line 121 "examples/csv/main.hero"
    t48 = INT64_C(1);
#line 121 "examples/csv/main.hero"
    t49 = t47 == t48;
#line 121 "examples/csv/main.hero"
    hero_print_bool(t49);
#line 121 "examples/csv/main.hero"
    hero_print_end();
#line 124 "examples/csv/main.hero"
    t50 = HERO_STR_LIT(hero_str_141e32a0);
#line 124 "examples/csv/main.hero"
    t51 = h_main_parse(t50);
#line 124 "examples/csv/main.hero"
    t79 = h13_own13;
#line 124 "examples/csv/main.hero"
    h13_own13 = t51;
#line 1682 "main.c"
    h_0opt_755e4b59_release(&t79);
#line 124 "examples/csv/main.hero"
    t80 = h4_f3;
#line 1686 "main.c"
    h_0opt_755e4b59_retain(&t51);
#line 124 "examples/csv/main.hero"
    h4_f3 = t51;
#line 1690 "main.c"
    h_0opt_755e4b59_release(&t80);
#line 124 "examples/csv/main.hero"
    t52 = h4_f3;
#line 124 "examples/csv/main.hero"
    t53 = t52.tag;
#line 124 "examples/csv/main.hero"
    t54 = INT64_C(1);
#line 124 "examples/csv/main.hero"
    t55 = t53 == t54;
#line 124 "examples/csv/main.hero"
    hero_print_bool(t55);
#line 124 "examples/csv/main.hero"
    hero_print_end();
#line 125 "examples/csv/main.hero"
    t56 = HERO_STR_LIT(hero_str_0);
#line 125 "examples/csv/main.hero"
    t57 = h_main_parse(t56);
#line 125 "examples/csv/main.hero"
    t81 = h14_own14;
#line 125 "examples/csv/main.hero"
    h14_own14 = t57;
#line 1712 "main.c"
    h_0opt_755e4b59_release(&t81);
#line 125 "examples/csv/main.hero"
    t82 = h5_f4;
#line 1716 "main.c"
    h_0opt_755e4b59_retain(&t57);
#line 125 "examples/csv/main.hero"
    h5_f4 = t57;
#line 1720 "main.c"
    h_0opt_755e4b59_release(&t82);
#line 125 "examples/csv/main.hero"
    t58 = h5_f4;
#line 125 "examples/csv/main.hero"
    t59 = t58.tag;
#line 125 "examples/csv/main.hero"
    t60 = INT64_C(0);
#line 125 "examples/csv/main.hero"
    t61 = t59 == t60;
#line 125 "examples/csv/main.hero"
    if (t61) goto bb5; else goto bb6;
#line 125 "examples/csv/main.hero"
bb4:
#line 120 "examples/csv/main.hero"
    t37 = h2_f1;
#line 120 "examples/csv/main.hero"
    t38 = t37.as.err;
#line 1738 "main.c"
    hero_panic_must(t38);
    hero_unreachable();
bb5:
#line 125 "examples/csv/main.hero"
    t64 = h5_f4;
#line 125 "examples/csv/main.hero"
    t65 = t64.as.ok;
#line 125 "examples/csv/main.hero"
    t66 = t65.f_rows;
#line 125 "examples/csv/main.hero"
    t67 = hero_array_len(t66);
#line 125 "examples/csv/main.hero"
    hero_print_int(t67);
#line 125 "examples/csv/main.hero"
    hero_print_end();
#line 1754 "main.c"
    h_0opt_755e4b59_release(&h0_f0);
#line 125 "examples/csv/main.hero"
#line 1757 "main.c"
    h_main_Table_release(&h1_table);
#line 125 "examples/csv/main.hero"
#line 1760 "main.c"
    h_0opt_5a58f2ca_release(&h2_f1);
#line 125 "examples/csv/main.hero"
#line 1763 "main.c"
    h_0opt_5a58f2ca_release(&h3_f2);
#line 125 "examples/csv/main.hero"
#line 1766 "main.c"
    h_0opt_755e4b59_release(&h4_f3);
#line 125 "examples/csv/main.hero"
#line 1769 "main.c"
    h_0opt_755e4b59_release(&h5_f4);
#line 125 "examples/csv/main.hero"
#line 1772 "main.c"
    hero_str_decref(h6_own6);
#line 125 "examples/csv/main.hero"
#line 1775 "main.c"
    h_0opt_755e4b59_release(&h7_own7);
#line 125 "examples/csv/main.hero"
#line 1778 "main.c"
    hero_str_decref(h8_own8);
#line 125 "examples/csv/main.hero"
#line 1781 "main.c"
    hero_str_decref(h9_own9);
#line 125 "examples/csv/main.hero"
#line 1784 "main.c"
    h_0opt_5a58f2ca_release(&h10_own10);
#line 125 "examples/csv/main.hero"
#line 1787 "main.c"
    hero_str_decref(h11_own11);
#line 125 "examples/csv/main.hero"
#line 1790 "main.c"
    h_0opt_5a58f2ca_release(&h12_own12);
#line 125 "examples/csv/main.hero"
#line 1793 "main.c"
    h_0opt_755e4b59_release(&h13_own13);
#line 125 "examples/csv/main.hero"
#line 1796 "main.c"
    h_0opt_755e4b59_release(&h14_own14);
    return;
bb6:
#line 125 "examples/csv/main.hero"
    t62 = h5_f4;
#line 125 "examples/csv/main.hero"
    t63 = t62.as.err;
#line 1804 "main.c"
    hero_panic_must(t63);
    hero_unreachable();
}
HERO_TU_LOCAL void h_main_Table_retain(const h_main_Table *v) {
    hero_array_incref(v->f_rows);
}

HERO_TU_LOCAL void h_main_Table_release(h_main_Table *v) {
    hero_array_decref(v->f_rows);
}

HERO_TU_LOCAL bool h_main_Table_eq(const h_main_Table *a, const h_main_Table *b) {
    if (!(hero_array_eq(a->f_rows, b->f_rows))) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_main_Table_hash(const void *elem) {
    const h_main_Table *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_array)->hash(&v->f_rows)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_0opt_755e4b59_retain(const h_0opt_755e4b59 *v) {
    if (v->tag == INT64_C(0)) {
        h_main_Table_retain(&v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_755e4b59_release(h_0opt_755e4b59 *v) {
    if (v->tag == INT64_C(0)) {
        h_main_Table_release(&v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_755e4b59_eq(const h_0opt_755e4b59 *a, const h_0opt_755e4b59 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&h_main_Table_desc)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_755e4b59_hash(const void *elem) {
    const h_0opt_755e4b59 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&h_main_Table_desc)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_5a58f2ca_retain(const h_0opt_5a58f2ca *v) {
    if (v->tag == INT64_C(0)) {
        hero_array_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_5a58f2ca_release(h_0opt_5a58f2ca *v) {
    if (v->tag == INT64_C(0)) {
        hero_array_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_5a58f2ca_eq(const h_0opt_5a58f2ca *a, const h_0opt_5a58f2ca *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_array)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_5a58f2ca_hash(const void *elem) {
    const h_0opt_5a58f2ca *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_array)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_main_main();
    hero_runtime_check_leaks();
    return 0;
}
