/* Generated by heroes 0.2.0 from tests/golden/ir/place-paths.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 21, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 45 "placepaths.c"
typedef struct h_placepaths_Row {
    HeroArrayHeader * f_cells;
} h_placepaths_Row;

typedef struct h_placepaths_Grid {
    HeroArrayHeader * f_rows;
} h_placepaths_Grid;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 117 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 123 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 86 "placepaths.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL void h_placepaths_Row_retain(const h_placepaths_Row *v);
HERO_TU_LOCAL void h_placepaths_Row_release(h_placepaths_Row *v);
HERO_TU_LOCAL bool h_placepaths_Row_eq(const h_placepaths_Row *a, const h_placepaths_Row *b);
HERO_TU_LOCAL uint64_t h_placepaths_Row_hash(const void *elem);
HERO_TU_LOCAL void h_placepaths_Grid_retain(const h_placepaths_Grid *v);
HERO_TU_LOCAL void h_placepaths_Grid_release(h_placepaths_Grid *v);
HERO_TU_LOCAL bool h_placepaths_Grid_eq(const h_placepaths_Grid *a, const h_placepaths_Grid *b);
HERO_TU_LOCAL uint64_t h_placepaths_Grid_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

void h_placepaths_set_cell(h_placepaths_Grid *ph0_g, int64_t h1_r, int64_t h2_c, int64_t h3_v);
int64_t h_placepaths_cell_of(h_placepaths_Grid h0_g, int64_t h1_r, int64_t h2_c);

#line 12 "tests/golden/ir/place-paths.hero"
void h_placepaths_set_cell(h_placepaths_Grid *ph0_g, int64_t h1_r, int64_t h2_c, int64_t h3_v) {
#line 111 "placepaths.c"
    h_placepaths_Grid h0_g = {0};
    int64_t t1;
    int64_t t2;
    int64_t t3;
    h0_g = *ph0_g;
    goto bb0;
bb0:
#line 13 "tests/golden/ir/place-paths.hero"
    t1 = h1_r;
#line 13 "tests/golden/ir/place-paths.hero"
    t2 = h2_c;
#line 13 "tests/golden/ir/place-paths.hero"
    t3 = h3_v;
#line 13 "tests/golden/ir/place-paths.hero"
    hero_array_unshare(&(h0_g.f_rows));
#line 13 "tests/golden/ir/place-paths.hero"
    hero_array_set(&((*(h_placepaths_Row *)hero_array_at_mut(h0_g.f_rows, t1)).f_cells), t2, &t3);
#line 129 "placepaths.c"
    *ph0_g = h0_g;
    return;
}

#line 15 "tests/golden/ir/place-paths.hero"
int64_t h_placepaths_cell_of(h_placepaths_Grid h0_g, int64_t h1_r, int64_t h2_c) {
#line 136 "placepaths.c"
    h_placepaths_Grid t1 = {0};
    HeroArrayHeader * t2 = {0};
    int64_t t3;
    h_placepaths_Row t4 = {0};
    HeroArrayHeader * t5 = {0};
    int64_t t6;
    int64_t t7;
    goto bb0;
bb0:
#line 16 "tests/golden/ir/place-paths.hero"
    t1 = h0_g;
#line 16 "tests/golden/ir/place-paths.hero"
    t2 = t1.f_rows;
#line 16 "tests/golden/ir/place-paths.hero"
    t3 = h1_r;
#line 16 "tests/golden/ir/place-paths.hero"
    t4 = *(h_placepaths_Row const *)hero_array_at(t2, t3);
#line 16 "tests/golden/ir/place-paths.hero"
    t5 = t4.f_cells;
#line 16 "tests/golden/ir/place-paths.hero"
    t6 = h2_c;
#line 16 "tests/golden/ir/place-paths.hero"
    t7 = *(int64_t const *)hero_array_at(t5, t6);
#line 16 "tests/golden/ir/place-paths.hero"
    return t7;
#line 162 "placepaths.c"
}
HERO_TU_LOCAL void h_placepaths_Row_retain(const h_placepaths_Row *v) {
    hero_array_incref(v->f_cells);
}

HERO_TU_LOCAL void h_placepaths_Row_release(h_placepaths_Row *v) {
    hero_array_decref(v->f_cells);
}

HERO_TU_LOCAL bool h_placepaths_Row_eq(const h_placepaths_Row *a, const h_placepaths_Row *b) {
    if (!(hero_array_eq(a->f_cells, b->f_cells))) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_placepaths_Row_hash(const void *elem) {
    const h_placepaths_Row *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_array)->hash(&v->f_cells)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_placepaths_Grid_retain(const h_placepaths_Grid *v) {
    hero_array_incref(v->f_rows);
}

HERO_TU_LOCAL void h_placepaths_Grid_release(h_placepaths_Grid *v) {
    hero_array_decref(v->f_rows);
}

HERO_TU_LOCAL bool h_placepaths_Grid_eq(const h_placepaths_Grid *a, const h_placepaths_Grid *b) {
    if (!(hero_array_eq(a->f_rows, b->f_rows))) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_placepaths_Grid_hash(const void *elem) {
    const h_placepaths_Grid *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_array)->hash(&v->f_rows)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}

