/* Generated by heroes 0.0.1 from tests/golden/run/fixedbugs-function-in-a-record-field.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 18, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 43 "fixedbugsfunctioninarecordfield.c"
#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 111 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 114 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 122 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 61 "fixedbugsfunctioninarecordfield.c"
#pragma clang diagnostic pop

HERO_STR_STATIC(hero_str_6be6e610, "double");

typedef int64_t (*h_0fn_48ac9712)(int64_t);
typedef struct h_fixedbugsfunctioninarecordfield_Holder {
    h_0fn_48ac9712 f_f;
    HeroStr f_label;
} h_fixedbugsfunctioninarecordfield_Holder;

typedef enum h_fixedbugsfunctioninarecordfield_Step_tag {
    h_fixedbugsfunctioninarecordfield_Step_tag_stop = 0,
    h_fixedbugsfunctioninarecordfield_Step_tag_apply = 1,
} h_fixedbugsfunctioninarecordfield_Step_tag;

typedef struct h_fixedbugsfunctioninarecordfield_Step_c_apply {
    h_0fn_48ac9712 f_g;
} h_fixedbugsfunctioninarecordfield_Step_c_apply;

typedef struct h_fixedbugsfunctioninarecordfield_Step {
    h_fixedbugsfunctioninarecordfield_Step_tag tag;
    union {
        h_fixedbugsfunctioninarecordfield_Step_c_apply c_apply;
    } as;
} h_fixedbugsfunctioninarecordfield_Step;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

HERO_TU_LOCAL void h_fixedbugsfunctioninarecordfield_Holder_retain(const h_fixedbugsfunctioninarecordfield_Holder *v);
HERO_TU_LOCAL void h_fixedbugsfunctioninarecordfield_Holder_release(h_fixedbugsfunctioninarecordfield_Holder *v);
HERO_TU_LOCAL bool h_fixedbugsfunctioninarecordfield_Holder_eq(const h_fixedbugsfunctioninarecordfield_Holder *a, const h_fixedbugsfunctioninarecordfield_Holder *b);
HERO_TU_LOCAL uint64_t h_fixedbugsfunctioninarecordfield_Holder_hash(const void *elem);
HERO_TU_LOCAL bool h_fixedbugsfunctioninarecordfield_Step_c_apply_eq(const h_fixedbugsfunctioninarecordfield_Step_c_apply *a, const h_fixedbugsfunctioninarecordfield_Step_c_apply *b);
HERO_TU_LOCAL uint64_t h_fixedbugsfunctioninarecordfield_Step_c_apply_hash(const void *elem);
HERO_TU_LOCAL bool h_fixedbugsfunctioninarecordfield_Step_eq(const h_fixedbugsfunctioninarecordfield_Step *a, const h_fixedbugsfunctioninarecordfield_Step *b);
HERO_TU_LOCAL uint64_t h_fixedbugsfunctioninarecordfield_Step_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

int64_t h_fixedbugsfunctioninarecordfield_double(int64_t h0_n);
int64_t h_fixedbugsfunctioninarecordfield_negate(int64_t h0_n);
void h_fixedbugsfunctioninarecordfield_main(void);

#line 29 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
int64_t h_fixedbugsfunctioninarecordfield_double(int64_t h0_n) {
#line 126 "fixedbugsfunctioninarecordfield.c"
    int64_t t1;
    int64_t t2;
    int64_t t3;
    goto bb0;
bb0:
#line 30 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t1 = h0_n;
#line 30 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t2 = INT64_C(2);
#line 30 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    if (__builtin_mul_overflow(t1, t2, &t3)) hero_panic_overflow();
#line 30 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    return t3;
#line 140 "fixedbugsfunctioninarecordfield.c"
}

#line 32 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
int64_t h_fixedbugsfunctioninarecordfield_negate(int64_t h0_n) {
#line 145 "fixedbugsfunctioninarecordfield.c"
    int64_t t1;
    int64_t t2;
    goto bb0;
bb0:
#line 33 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t1 = h0_n;
#line 33 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    if (__builtin_sub_overflow(INT64_C(0), t1, &t2)) hero_panic_overflow();
#line 33 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    return t2;
#line 156 "fixedbugsfunctioninarecordfield.c"
}

#line 46 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
void h_fixedbugsfunctioninarecordfield_main(void) {
#line 161 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder h0_h = {0};
    h_fixedbugsfunctioninarecordfield_Holder h1_k = {0};
    h_fixedbugsfunctioninarecordfield_Step h2_s;
    h_fixedbugsfunctioninarecordfield_Step h3_s0;
    h_fixedbugsfunctioninarecordfield_Step_c_apply h4_a;
    h_0fn_48ac9712 h5_call;
    h_fixedbugsfunctioninarecordfield_Holder h6_own6 = {0};
    h_0fn_48ac9712 t1;
    HeroStr t2 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t3 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t4 = {0};
    h_0fn_48ac9712 t5;
    int64_t t6;
    int64_t t7;
    h_fixedbugsfunctioninarecordfield_Holder t8 = {0};
    HeroStr t9 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t10 = {0};
    h_0fn_48ac9712 t11;
    h_fixedbugsfunctioninarecordfield_Holder t12 = {0};
    h_0fn_48ac9712 t13;
    int64_t t14;
    int64_t t15;
    h_fixedbugsfunctioninarecordfield_Holder t16 = {0};
    h_0fn_48ac9712 t17;
    int64_t t18;
    int64_t t19;
    h_0fn_48ac9712 t20;
    h_fixedbugsfunctioninarecordfield_Step t21;
    h_fixedbugsfunctioninarecordfield_Step t22;
    h_fixedbugsfunctioninarecordfield_Step t23;
    int64_t t24;
    h_fixedbugsfunctioninarecordfield_Step t25;
    h_fixedbugsfunctioninarecordfield_Step_c_apply t26;
    h_fixedbugsfunctioninarecordfield_Step_c_apply t27;
    h_0fn_48ac9712 t28;
    h_0fn_48ac9712 t29;
    int64_t t30;
    int64_t t31;
    int64_t t32;
    h_fixedbugsfunctioninarecordfield_Holder t33 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t34 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t35 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t36 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t37 = {0};
    h_fixedbugsfunctioninarecordfield_Holder t38 = {0};
    goto bb0;
bb0:
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t1 = h_fixedbugsfunctioninarecordfield_double;
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t2 = HERO_STR_LIT(hero_str_6be6e610);
#line 213 "fixedbugsfunctioninarecordfield.c"
    hero_str_incref(t2);
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t3 = (h_fixedbugsfunctioninarecordfield_Holder){.f_f = t1, .f_label = t2};
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t33 = h6_own6;
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h6_own6 = t3;
#line 221 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_release(&t33);
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t34 = h0_h;
#line 225 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_retain(&t3);
#line 47 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h0_h = t3;
#line 229 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_release(&t34);
#line 48 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t4 = h0_h;
#line 48 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t5 = t4.f_f;
#line 48 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t6 = INT64_C(21);
#line 48 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t7 = t5(t6);
#line 48 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_int(t7);
#line 48 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_end();
#line 49 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t8 = h0_h;
#line 49 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t9 = t8.f_label;
#line 49 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_str(t9);
#line 49 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_end();
#line 52 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t10 = h0_h;
#line 52 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t35 = h1_k;
#line 255 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_retain(&t10);
#line 52 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h1_k = t10;
#line 259 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_release(&t35);
#line 53 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t11 = h_fixedbugsfunctioninarecordfield_negate;
#line 53 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h1_k.f_f = t11;
#line 54 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t12 = h1_k;
#line 54 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t13 = t12.f_f;
#line 54 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t14 = INT64_C(21);
#line 54 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t15 = t13(t14);
#line 54 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_int(t15);
#line 54 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_end();
#line 57 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t16 = h0_h;
#line 57 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t17 = t16.f_f;
#line 57 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t18 = INT64_C(21);
#line 57 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t19 = t17(t18);
#line 57 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_int(t19);
#line 57 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_end();
#line 58 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t20 = h_fixedbugsfunctioninarecordfield_double;
#line 58 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t21 = (h_fixedbugsfunctioninarecordfield_Step){.tag = h_fixedbugsfunctioninarecordfield_Step_tag_apply, .as.c_apply = {.f_g = t20}};
#line 58 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h2_s = t21;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t22 = h2_s;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h3_s0 = t22;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t23 = h3_s0;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t24 = t23.tag;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    switch (t24) {
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
        case 0: goto bb3;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
        case 1: goto bb2;
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
        default: hero_unreachable();
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    }
#line 60 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
bb1:
#line 46 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t36 = h0_h;
#line 317 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_release(&t36);
#line 46 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t37 = h1_k;
#line 321 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_release(&t37);
#line 46 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t38 = h6_own6;
#line 325 "fixedbugsfunctioninarecordfield.c"
    h_fixedbugsfunctioninarecordfield_Holder_release(&t38);
    return;
bb2:
#line 61 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t25 = h3_s0;
#line 61 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t26 = t25.as.c_apply;
#line 61 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h4_a = t26;
#line 62 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t27 = h4_a;
#line 62 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t28 = t27.f_g;
#line 62 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    h5_call = t28;
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t29 = h5_call;
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t30 = INT64_C(50);
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t31 = t29(t30);
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_int(t31);
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_end();
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    goto bb1;
#line 63 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
bb3:
#line 64 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    t32 = INT64_C(0);
#line 64 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_int(t32);
#line 64 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    hero_print_end();
#line 64 "tests/golden/run/fixedbugs-function-in-a-record-field.hero"
    goto bb1;
#line 363 "fixedbugsfunctioninarecordfield.c"
}
HERO_TU_LOCAL void h_fixedbugsfunctioninarecordfield_Holder_retain(const h_fixedbugsfunctioninarecordfield_Holder *v) {
    hero_str_incref(v->f_label);
}

HERO_TU_LOCAL void h_fixedbugsfunctioninarecordfield_Holder_release(h_fixedbugsfunctioninarecordfield_Holder *v) {
    hero_str_decref(v->f_label);
}

HERO_TU_LOCAL bool h_fixedbugsfunctioninarecordfield_Holder_eq(const h_fixedbugsfunctioninarecordfield_Holder *a, const h_fixedbugsfunctioninarecordfield_Holder *b) {
    if (!(a->f_f == b->f_f)) return false;
    if (!(hero_str_eq(a->f_label, b->f_label))) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_fixedbugsfunctioninarecordfield_Holder_hash(const void *elem) {
    const h_fixedbugsfunctioninarecordfield_Holder *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_func)->hash(&v->f_f)) * UINT64_C(0x100000001b3);
    h = (h ^ (&hero_desc_str)->hash(&v->f_label)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL bool h_fixedbugsfunctioninarecordfield_Step_c_apply_eq(const h_fixedbugsfunctioninarecordfield_Step_c_apply *a, const h_fixedbugsfunctioninarecordfield_Step_c_apply *b) {
    if (!(a->f_g == b->f_g)) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_fixedbugsfunctioninarecordfield_Step_c_apply_hash(const void *elem) {
    const h_fixedbugsfunctioninarecordfield_Step_c_apply *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_func)->hash(&v->f_g)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL bool h_fixedbugsfunctioninarecordfield_Step_eq(const h_fixedbugsfunctioninarecordfield_Step *a, const h_fixedbugsfunctioninarecordfield_Step *b) {
    if (a->tag != b->tag) return false;
    switch (a->tag) {
        case h_fixedbugsfunctioninarecordfield_Step_tag_stop: return true;
        case h_fixedbugsfunctioninarecordfield_Step_tag_apply: return h_fixedbugsfunctioninarecordfield_Step_c_apply_eq(&a->as.c_apply, &b->as.c_apply);
    }
    hero_unreachable();
}

HERO_TU_LOCAL uint64_t h_fixedbugsfunctioninarecordfield_Step_hash(const void *elem) {
    const h_fixedbugsfunctioninarecordfield_Step *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    switch (v->tag) {
        case h_fixedbugsfunctioninarecordfield_Step_tag_stop: return h;
        case h_fixedbugsfunctioninarecordfield_Step_tag_apply: return (h ^ h_fixedbugsfunctioninarecordfield_Step_c_apply_hash(&v->as.c_apply)) * UINT64_C(0x100000001b3);
    }
    hero_unreachable();
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_fixedbugsfunctioninarecordfield_main();
    hero_runtime_check_leaks();
    return 0;
}
