/* Generated by heroes 0.0.1 from tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 15, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_STR(hero_file_read(0, (int64_t *)0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, (int64_t *)0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 43 "fixedbugsunaryminusisnotaliteral.c"
#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 111 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, a1); }
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 114 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 122 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, a1); }
#line 61 "fixedbugsunaryminusisnotaliteral.c"
#pragma clang diagnostic pop

HERO_STR_STATIC(hero_str_726a17c3, "literal ");
HERO_STR_STATIC(hero_str_48404065, "names ");
HERO_STR_STATIC(hero_str_20, " ");
HERO_STR_STATIC(hero_str_2a2e6b28, "checked ");
HERO_STR_STATIC(hero_str_52436c76, "nested ");

typedef struct h_0opt_e201354 {
    int64_t tag;
    union {
        int64_t ok;
        HeroFailure err;
    } as;
} h_0opt_e201354;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v);
HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v);
HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b);
HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

h_0opt_e201354 h_fixedbugsunaryminusisnotaliteral_negated(int64_t h0_n);
double h_fixedbugsunaryminusisnotaliteral_scaled(double h0_v);
void h_fixedbugsunaryminusisnotaliteral_main(void);

#line 32 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
h_0opt_e201354 h_fixedbugsunaryminusisnotaliteral_negated(int64_t h0_n) {
#line 112 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354 h1_own1 = {0};
    int64_t t1;
    int64_t t2;
    h_0opt_e201354 t3 = {0};
    h_0opt_e201354 t4 = {0};
    h_0opt_e201354 t5 = {0};
    goto bb0;
bb0:
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t1 = h0_n;
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    if (__builtin_sub_overflow(INT64_C(0), t1, &t2)) hero_panic_overflow();
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t3 = (h_0opt_e201354){.tag = INT64_C(0), .as.ok = t2};
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t4 = h1_own1;
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h1_own1 = t3;
#line 131 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_release(&t4);
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
#line 134 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_retain(&t3);
#line 33 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t5 = h1_own1;
#line 138 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_release(&t5);
    return t3;
}

#line 35 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
double h_fixedbugsunaryminusisnotaliteral_scaled(double h0_v) {
#line 145 "fixedbugsunaryminusisnotaliteral.c"
    double t1;
    double t2;
    goto bb0;
bb0:
#line 36 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t1 = h0_v;
#line 36 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t2 = -t1;
#line 36 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    return t2;
#line 156 "fixedbugsunaryminusisnotaliteral.c"
}

#line 38 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
void h_fixedbugsunaryminusisnotaliteral_main(void) {
#line 161 "fixedbugsunaryminusisnotaliteral.c"
    int8_t h0_small;
    int64_t h1_n;
    double h2_x;
    h_0opt_e201354 h3_f0 = {0};
    h_0opt_e201354 h4_own4 = {0};
    int8_t t1;
    HeroStr t2 = {0};
    int8_t t3;
    int64_t t4;
    int64_t t5;
    int64_t t6;
    double t7;
    double t8;
    double t9;
    HeroStr t10 = {0};
    int64_t t11;
    HeroStr t12 = {0};
    double t13;
    HeroStr t14 = {0};
    int64_t t15;
    h_0opt_e201354 t16 = {0};
    h_0opt_e201354 t17 = {0};
    int64_t t18;
    int64_t t19;
    bool t20;
    h_0opt_e201354 t21 = {0};
    HeroFailure t22 = {0};
    h_0opt_e201354 t23 = {0};
    int64_t t24;
    HeroStr t25 = {0};
    double t26;
    double t27;
    HeroStr t28 = {0};
    int64_t t29;
    int64_t t30;
    int64_t t31;
    int64_t t32;
    HeroStr t33 = {0};
    double t34;
    double t35;
    double t36;
    h_0opt_e201354 t37 = {0};
    h_0opt_e201354 t38 = {0};
    h_0opt_e201354 t39 = {0};
    h_0opt_e201354 t40 = {0};
    goto bb0;
bb0:
#line 40 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t1 = INT64_C(-128);
#line 40 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h0_small = t1;
#line 41 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t2 = HERO_STR_LIT(hero_str_726a17c3);
#line 41 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t3 = h0_small;
#line 41 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t2);
#line 41 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_int(t3);
#line 41 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_end();
#line 44 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t4 = INT64_C(7);
#line 44 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h1_n = t4;
#line 45 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t5 = h1_n;
#line 45 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    if (__builtin_sub_overflow(INT64_C(0), t5, &t6)) hero_panic_overflow();
#line 45 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h1_n = t6;
#line 46 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t7 = 0x1.8p+0;
#line 46 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h2_x = t7;
#line 47 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t8 = h2_x;
#line 47 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t9 = -t8;
#line 47 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h2_x = t9;
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t10 = HERO_STR_LIT(hero_str_48404065);
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t11 = h1_n;
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t12 = HERO_STR_LIT(hero_str_20);
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t13 = h2_x;
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t10);
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_int(t11);
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t12);
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_f64(t13);
#line 48 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_end();
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t14 = HERO_STR_LIT(hero_str_2a2e6b28);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t15 = INT64_C(9);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t16 = h_fixedbugsunaryminusisnotaliteral_negated(t15);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t37 = h4_own4;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h4_own4 = t16;
#line 271 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_release(&t37);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t38 = h3_f0;
#line 275 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_retain(&t16);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    h3_f0 = t16;
#line 279 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_release(&t38);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t17 = h3_f0;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t18 = t17.tag;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t19 = INT64_C(0);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t20 = t18 == t19;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    if (t20) goto bb1; else goto bb2;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
bb1:
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t23 = h3_f0;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t24 = t23.as.ok;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t25 = HERO_STR_LIT(hero_str_20);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t26 = 0x1p-2;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t27 = h_fixedbugsunaryminusisnotaliteral_scaled(t26);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t14);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_int(t24);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t25);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_f64(t27);
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_end();
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t28 = HERO_STR_LIT(hero_str_52436c76);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t29 = h1_n;
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t30 = INT64_C(1);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    if (__builtin_add_overflow(t29, t30, &t31)) hero_panic_overflow();
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    if (__builtin_sub_overflow(INT64_C(0), t31, &t32)) hero_panic_overflow();
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t33 = HERO_STR_LIT(hero_str_20);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t34 = 0x1p+1;
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t35 = h_fixedbugsunaryminusisnotaliteral_scaled(t34);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t36 = -t35;
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t28);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_int(t32);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_str(t33);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_f64(t36);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    hero_print_end();
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t39 = h3_f0;
#line 343 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_release(&t39);
#line 55 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t40 = h4_own4;
#line 347 "fixedbugsunaryminusisnotaliteral.c"
    h_0opt_e201354_release(&t40);
    return;
bb2:
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t21 = h3_f0;
#line 52 "tests/golden/run/fixedbugs-unary-minus-is-not-a-literal.hero"
    t22 = t21.as.err;
#line 355 "fixedbugsunaryminusisnotaliteral.c"
    hero_panic_must(t22);
    hero_unreachable();
}
HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_int)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem) {
    const h_0opt_e201354 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_int)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_fixedbugsunaryminusisnotaliteral_main();
    hero_runtime_check_leaks();
    return 0;
}
