/* Generated by heroes 0.2.0 from tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 30, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 8 : sizeof(c) <= 8))
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && (_Generic((c), _Bool:1, default:0) || (!HERO_C_UNSIGNED(c) && sizeof(c) == 1)))
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 2 : sizeof(c) <= 2))
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 4 : sizeof(c) <= 4))
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:(__LDBL_MANT_DIG__ <= __DBL_MANT_DIG__ && __LDBL_MAX_EXP__ <= __DBL_MAX_EXP__ && __LDBL_MIN_EXP__ >= __DBL_MIN_EXP__), default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_INT(HERO_OS_BAD_NAME), "heroes-ffi-return HERO_OS_BAD_NAME i64");
_Static_assert(__builtin_constant_p(HERO_OS_BAD_NAME), "heroes-ffi-const HERO_OS_BAD_NAME");
_Static_assert(HERO_RET_STR(hero_file_read_str((HeroStr){0}, 0)), "heroes-ffi-return hero_file_read_str str");
_Static_assert(HERO_RET_INT(hero_file_write_str((HeroStr){0}, (HeroStr){0})), "heroes-ffi-return hero_file_write_str i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

HERO_STR_STATIC(hero_str_78, "x");
HERO_STR_STATIC(hero_str_61, "a");
HERO_STR_STATIC(hero_str_62, "b");
HERO_STR_STATIC(hero_str_3204, "aa");
HERO_STR_STATIC(hero_str_3288, "bb");
HERO_STR_STATIC(hero_str_330c, "cc");
HERO_STR_STATIC(hero_str_3390, "dd");
HERO_STR_STATIC(hero_str_3ed3d9ee, "kept[0].cells[0].n == 9");
HERO_STR_STATIC(hero_str_6185c9b, "rows[0].cells[0].n == 10");
HERO_STR_STATIC(hero_str_7a, "z");
HERO_STR_STATIC(hero_str_6b, "k");

#line 59 "fixedbugsafieldstoredbehindanindex.c"
typedef struct h_fixedbugsafieldstoredbehindanindex_Cell {
    int64_t f_n;
    HeroStr f_tag;
} h_fixedbugsafieldstoredbehindanindex_Cell;

typedef struct h_fixedbugsafieldstoredbehindanindex_Row {
    HeroArrayHeader * f_cells;
    HeroStr f_label;
} h_fixedbugsafieldstoredbehindanindex_Row;

typedef struct h_0opt_e201354 {
    int64_t tag;
    union {
        int64_t ok;
        HeroFailure err;
    } as;
} h_0opt_e201354;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read_str(HeroStr a0, int64_t * a1) { (void)(hero_file_read_str)(a0, (void *)a1); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write_str(HeroStr a0, HeroStr a1) { (void)(hero_file_write_str)(a0, a1); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 124 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 107 "fixedbugsafieldstoredbehindanindex.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Cell_retain(const h_fixedbugsafieldstoredbehindanindex_Cell *v);
HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Cell_release(h_fixedbugsafieldstoredbehindanindex_Cell *v);
HERO_TU_LOCAL bool h_fixedbugsafieldstoredbehindanindex_Cell_eq(const h_fixedbugsafieldstoredbehindanindex_Cell *a, const h_fixedbugsafieldstoredbehindanindex_Cell *b);
HERO_TU_LOCAL uint64_t h_fixedbugsafieldstoredbehindanindex_Cell_hash(const void *elem);
HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Row_retain(const h_fixedbugsafieldstoredbehindanindex_Row *v);
HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Row_release(h_fixedbugsafieldstoredbehindanindex_Row *v);
HERO_TU_LOCAL bool h_fixedbugsafieldstoredbehindanindex_Row_eq(const h_fixedbugsafieldstoredbehindanindex_Row *a, const h_fixedbugsafieldstoredbehindanindex_Row *b);
HERO_TU_LOCAL uint64_t h_fixedbugsafieldstoredbehindanindex_Row_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v);
HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v);
HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b);
HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

static void h_fixedbugsafieldstoredbehindanindex_Cell_desc_copy(void *dst, const void *src) {
    __builtin_memmove(dst, src, sizeof(h_fixedbugsafieldstoredbehindanindex_Cell));
    h_fixedbugsafieldstoredbehindanindex_Cell_retain((const h_fixedbugsafieldstoredbehindanindex_Cell *)dst);
}
static void h_fixedbugsafieldstoredbehindanindex_Cell_desc_drop(void *elem) {
    h_fixedbugsafieldstoredbehindanindex_Cell_release((h_fixedbugsafieldstoredbehindanindex_Cell *)elem);
}
static bool h_fixedbugsafieldstoredbehindanindex_Cell_desc_eq(const void *a, const void *b) {
    return h_fixedbugsafieldstoredbehindanindex_Cell_eq((const h_fixedbugsafieldstoredbehindanindex_Cell *)a, (const h_fixedbugsafieldstoredbehindanindex_Cell *)b);
}
HERO_TU_QUIET static const HeroDesc h_fixedbugsafieldstoredbehindanindex_Cell_desc = {
    sizeof(h_fixedbugsafieldstoredbehindanindex_Cell),
    h_fixedbugsafieldstoredbehindanindex_Cell_desc_copy,
    h_fixedbugsafieldstoredbehindanindex_Cell_desc_drop,
    h_fixedbugsafieldstoredbehindanindex_Cell_desc_eq,
    h_fixedbugsafieldstoredbehindanindex_Cell_hash,
};

static void h_fixedbugsafieldstoredbehindanindex_Row_desc_copy(void *dst, const void *src) {
    __builtin_memmove(dst, src, sizeof(h_fixedbugsafieldstoredbehindanindex_Row));
    h_fixedbugsafieldstoredbehindanindex_Row_retain((const h_fixedbugsafieldstoredbehindanindex_Row *)dst);
}
static void h_fixedbugsafieldstoredbehindanindex_Row_desc_drop(void *elem) {
    h_fixedbugsafieldstoredbehindanindex_Row_release((h_fixedbugsafieldstoredbehindanindex_Row *)elem);
}
static bool h_fixedbugsafieldstoredbehindanindex_Row_desc_eq(const void *a, const void *b) {
    return h_fixedbugsafieldstoredbehindanindex_Row_eq((const h_fixedbugsafieldstoredbehindanindex_Row *)a, (const h_fixedbugsafieldstoredbehindanindex_Row *)b);
}
HERO_TU_QUIET static const HeroDesc h_fixedbugsafieldstoredbehindanindex_Row_desc = {
    sizeof(h_fixedbugsafieldstoredbehindanindex_Row),
    h_fixedbugsafieldstoredbehindanindex_Row_desc_copy,
    h_fixedbugsafieldstoredbehindanindex_Row_desc_drop,
    h_fixedbugsafieldstoredbehindanindex_Row_desc_eq,
    h_fixedbugsafieldstoredbehindanindex_Row_hash,
};

void h_fixedbugsafieldstoredbehindanindex_main(void);

#line 33 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
void h_fixedbugsafieldstoredbehindanindex_main(void) {
#line 171 "fixedbugsafieldstoredbehindanindex.c"
    HeroArrayHeader * h0_rows = {0};
    HeroArrayHeader * h1_kept = {0};
    HeroMapHeader * h2_m = {0};
    h_0opt_e201354 h3_f0 = {0};
    h_fixedbugsafieldstoredbehindanindex_Cell h4_own4 = {0};
    HeroArrayHeader * h5_own5 = {0};
    h_fixedbugsafieldstoredbehindanindex_Row h6_own6 = {0};
    HeroArrayHeader * h7_own7 = {0};
    HeroStr h8_own8 = {0};
    HeroStr h9_own9 = {0};
    h_fixedbugsafieldstoredbehindanindex_Cell h10_own10 = {0};
    HeroMapHeader * h11_own11 = {0};
    h_0opt_e201354 h12_own12 = {0};
    int64_t t1;
    HeroStr t2;
    h_fixedbugsafieldstoredbehindanindex_Cell t3;
    HeroArrayHeader * t4;
    HeroStr t5;
    h_fixedbugsafieldstoredbehindanindex_Row t6;
    HeroArrayHeader * t7;
    int64_t t8;
    HeroStr t9;
    int64_t t10;
    int64_t t11;
    int64_t t12;
    int64_t t13;
    int64_t t14;
    HeroStr t15;
    HeroStr t16;
    HeroStr t17;
    int64_t t18;
    int64_t t19;
    HeroStr t20;
    HeroStr t21;
    HeroStr t22;
    HeroArrayHeader * t23;
    int64_t t24;
    int64_t t25;
    int64_t t26;
    HeroStr t27;
    HeroArrayHeader * t28;
    int64_t t29;
    h_fixedbugsafieldstoredbehindanindex_Row t30;
    HeroArrayHeader * t31;
    int64_t t32;
    h_fixedbugsafieldstoredbehindanindex_Cell t33;
    int64_t t34;
    int64_t t35;
    bool t36;
    HeroStr t37;
    HeroArrayHeader * t38;
    int64_t t39;
    h_fixedbugsafieldstoredbehindanindex_Row t40;
    HeroArrayHeader * t41;
    int64_t t42;
    h_fixedbugsafieldstoredbehindanindex_Cell t43;
    int64_t t44;
    int64_t t45;
    bool t46;
    int64_t t47;
    int64_t t48;
    int64_t t49;
    HeroStr t50;
    h_fixedbugsafieldstoredbehindanindex_Cell t51;
    HeroMapHeader * t52;
    HeroStr t53;
    int64_t t54;
    HeroArrayHeader * t55;
    int64_t t56;
    h_fixedbugsafieldstoredbehindanindex_Row t57;
    HeroStr t58;
    HeroArrayHeader * t59;
    int64_t t60;
    h_fixedbugsafieldstoredbehindanindex_Row t61;
    HeroArrayHeader * t62;
    int64_t t63;
    h_fixedbugsafieldstoredbehindanindex_Cell t64;
    int64_t t65;
    HeroArrayHeader * t66;
    int64_t t67;
    h_fixedbugsafieldstoredbehindanindex_Row t68;
    HeroArrayHeader * t69;
    int64_t t70;
    h_fixedbugsafieldstoredbehindanindex_Cell t71;
    HeroStr t72;
    HeroMapHeader * t73;
    HeroStr t74;
    h_0opt_e201354 t75;
    h_0opt_e201354 t76;
    int64_t t77;
    int64_t t78;
    bool t79;
    h_0opt_e201354 t80;
    HeroFailure t81;
    h_0opt_e201354 t82;
    int64_t t83;
    h_fixedbugsafieldstoredbehindanindex_Cell t84;
    HeroArrayHeader * t85;
    h_fixedbugsafieldstoredbehindanindex_Row t86;
    HeroArrayHeader * t87;
    HeroArrayHeader * t88;
    HeroStr t89;
    HeroStr t90;
    HeroArrayHeader * t91;
    h_fixedbugsafieldstoredbehindanindex_Cell t92;
    HeroMapHeader * t93;
    HeroMapHeader * t94;
    h_0opt_e201354 t95;
    h_0opt_e201354 t96;
    goto bb0;
bb0:
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t1 = INT64_C(1);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t2 = HERO_STR_LIT(hero_str_78);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_incref(t2);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t3 = (h_fixedbugsafieldstoredbehindanindex_Cell){.f_n = t1, .f_tag = t2};
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t84 = h4_own4;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h4_own4 = t3;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_fixedbugsafieldstoredbehindanindex_Cell_release(&t84);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t4 = hero_array_new(&h_fixedbugsafieldstoredbehindanindex_Cell_desc, 1);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_push_owned(&t4, &t3);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t85 = h5_own5;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h5_own5 = t4;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_decref(t85);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t5 = HERO_STR_LIT(hero_str_61);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_incref(t4);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_incref(t5);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t6 = (h_fixedbugsafieldstoredbehindanindex_Row){.f_cells = t4, .f_label = t5};
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t86 = h6_own6;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h6_own6 = t6;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_fixedbugsafieldstoredbehindanindex_Row_release(&t86);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t7 = hero_array_new(&h_fixedbugsafieldstoredbehindanindex_Row_desc, 1);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_push_owned(&t7, &t6);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t87 = h7_own7;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h7_own7 = t7;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_decref(t87);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t88 = h0_rows;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_incref(t7);
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h0_rows = t7;
#line 34 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_decref(t88);
#line 37 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t8 = INT64_C(0);
#line 37 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t9 = HERO_STR_LIT(hero_str_62);
#line 37 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_incref(t9);
#line 37 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&(h0_rows));
#line 37 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_decref((*((void)((h0_rows == NULL || t8 < 0 || t8 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t8), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t8)).f_label);
#line 37 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    (*((void)((h0_rows == NULL || t8 < 0 || t8 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t8), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t8)).f_label = t9;
    t10 = INT64_C(0);
#line 38 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t11 = INT64_C(0);
#line 38 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t12 = INT64_C(9);
#line 38 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&(h0_rows));
#line 38 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&((*((void)((h0_rows == NULL || t10 < 0 || t10 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t10), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t10)).f_cells));
#line 38 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    (*(h_fixedbugsafieldstoredbehindanindex_Cell *)hero_array_at_mut((*((void)((h0_rows == NULL || t10 < 0 || t10 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t10), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t10)).f_cells, t11)).f_n = t12;
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t13 = INT64_C(0);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t14 = INT64_C(0);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t15 = HERO_STR_LIT(hero_str_3204);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t16 = HERO_STR_LIT(hero_str_3288);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t17 = hero_str_concat(t15, t16);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t89 = h8_own8;
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h8_own8 = t17;
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_decref(t89);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_incref(t17);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&(h0_rows));
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&((*((void)((h0_rows == NULL || t13 < 0 || t13 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t13), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t13)).f_cells));
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_decref((*(h_fixedbugsafieldstoredbehindanindex_Cell *)hero_array_at_mut((*((void)((h0_rows == NULL || t13 < 0 || t13 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t13), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t13)).f_cells, t14)).f_tag);
#line 41 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    (*(h_fixedbugsafieldstoredbehindanindex_Cell *)hero_array_at_mut((*((void)((h0_rows == NULL || t13 < 0 || t13 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t13), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t13)).f_cells, t14)).f_tag = t17;
    t18 = INT64_C(0);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t19 = INT64_C(0);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t20 = HERO_STR_LIT(hero_str_330c);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t21 = HERO_STR_LIT(hero_str_3390);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t22 = hero_str_concat(t20, t21);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t90 = h9_own9;
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h9_own9 = t22;
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_decref(t90);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_incref(t22);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&(h0_rows));
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&((*((void)((h0_rows == NULL || t18 < 0 || t18 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t18), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t18)).f_cells));
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_decref((*(h_fixedbugsafieldstoredbehindanindex_Cell *)hero_array_at_mut((*((void)((h0_rows == NULL || t18 < 0 || t18 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t18), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t18)).f_cells, t19)).f_tag);
#line 42 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    (*(h_fixedbugsafieldstoredbehindanindex_Cell *)hero_array_at_mut((*((void)((h0_rows == NULL || t18 < 0 || t18 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t18), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t18)).f_cells, t19)).f_tag = t22;
#line 46 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t23 = h0_rows;
#line 46 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t91 = h1_kept;
#line 46 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_incref(t23);
#line 46 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h1_kept = t23;
#line 46 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_decref(t91);
    t24 = INT64_C(0);
#line 47 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t25 = INT64_C(0);
#line 47 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t26 = INT64_C(10);
#line 47 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&(h0_rows));
#line 47 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&((*((void)((h0_rows == NULL || t24 < 0 || t24 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t24), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t24)).f_cells));
#line 47 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    (*(h_fixedbugsafieldstoredbehindanindex_Cell *)hero_array_at_mut((*((void)((h0_rows == NULL || t24 < 0 || t24 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t24), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t24)).f_cells, t25)).f_n = t26;
    t27 = HERO_STR_LIT(hero_str_3ed3d9ee);
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t28 = h1_kept;
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t29 = INT64_C(0);
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t30 = ((void)((t28 == NULL || t29 < 0 || t29 >= t28->len) ? ((void)hero_array_at(t28, t29), hero_unreachable()) : (void)0), (void)(t28->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Row const *)(const void *)(t28 + 1))[t29]);
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t31 = t30.f_cells;
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t32 = INT64_C(0);
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t33 = ((void)((t31 == NULL || t32 < 0 || t32 >= t31->len) ? ((void)hero_array_at(t31, t32), hero_unreachable()) : (void)0), (void)(t31->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Cell) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Cell const *)(const void *)(t31 + 1))[t32]);
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t34 = t33.f_n;
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t35 = INT64_C(9);
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t36 = t34 == t35;
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    if (t36) goto bb1; else goto bb2;
#line 48 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
bb1:
    t37 = HERO_STR_LIT(hero_str_6185c9b);
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t38 = h0_rows;
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t39 = INT64_C(0);
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t40 = ((void)((t38 == NULL || t39 < 0 || t39 >= t38->len) ? ((void)hero_array_at(t38, t39), hero_unreachable()) : (void)0), (void)(t38->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Row const *)(const void *)(t38 + 1))[t39]);
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t41 = t40.f_cells;
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t42 = INT64_C(0);
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t43 = ((void)((t41 == NULL || t42 < 0 || t42 >= t41->len) ? ((void)hero_array_at(t41, t42), hero_unreachable()) : (void)0), (void)(t41->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Cell) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Cell const *)(const void *)(t41 + 1))[t42]);
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t44 = t43.f_n;
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t45 = INT64_C(10);
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t46 = t44 == t45;
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    if (t46) goto bb3; else goto bb4;
#line 49 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
bb2:
#line 480 "fixedbugsafieldstoredbehindanindex.c"
    hero_panic_assert_sides(t27, hero_int_to_str(t34), hero_int_to_str(t35));
    hero_unreachable();
bb3:
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t47 = INT64_C(0);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t48 = INT64_C(0);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t49 = INT64_C(7);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t50 = HERO_STR_LIT(hero_str_7a);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_str_incref(t50);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t51 = (h_fixedbugsafieldstoredbehindanindex_Cell){.f_n = t49, .f_tag = t50};
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t92 = h10_own10;
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h10_own10 = t51;
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_fixedbugsafieldstoredbehindanindex_Cell_release(&t92);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_fixedbugsafieldstoredbehindanindex_Cell_retain(&t51);
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_unshare(&(h0_rows));
#line 52 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_array_set(&((*((void)((h0_rows == NULL || t47 < 0 || t47 >= h0_rows->len) ? ((void)hero_array_at_mut(h0_rows, t47), hero_unreachable()) : (void)0), (void)(h0_rows->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), (h_fixedbugsafieldstoredbehindanindex_Row *)(void *)(h0_rows + 1) + t47)).f_cells), t48, &t51);
    t52 = hero_map_new(&hero_desc_str, &hero_desc_int, 0);
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t93 = h11_own11;
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h11_own11 = t52;
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_map_decref(t93);
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t94 = h2_m;
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_map_incref(t52);
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h2_m = t52;
#line 53 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_map_decref(t94);
    t53 = HERO_STR_LIT(hero_str_6b);
#line 54 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t54 = INT64_C(3);
#line 54 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_map_set(&(h2_m), &t53, &t54);
    t55 = h0_rows;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t56 = INT64_C(0);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t57 = ((void)((t55 == NULL || t56 < 0 || t56 >= t55->len) ? ((void)hero_array_at(t55, t56), hero_unreachable()) : (void)0), (void)(t55->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Row const *)(const void *)(t55 + 1))[t56]);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t58 = t57.f_label;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t59 = h0_rows;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t60 = INT64_C(0);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t61 = ((void)((t59 == NULL || t60 < 0 || t60 >= t59->len) ? ((void)hero_array_at(t59, t60), hero_unreachable()) : (void)0), (void)(t59->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Row const *)(const void *)(t59 + 1))[t60]);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t62 = t61.f_cells;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t63 = INT64_C(0);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t64 = ((void)((t62 == NULL || t63 < 0 || t63 >= t62->len) ? ((void)hero_array_at(t62, t63), hero_unreachable()) : (void)0), (void)(t62->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Cell) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Cell const *)(const void *)(t62 + 1))[t63]);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t65 = t64.f_n;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t66 = h0_rows;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t67 = INT64_C(0);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t68 = ((void)((t66 == NULL || t67 < 0 || t67 >= t66->len) ? ((void)hero_array_at(t66, t67), hero_unreachable()) : (void)0), (void)(t66->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Row) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Row const *)(const void *)(t66 + 1))[t67]);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t69 = t68.f_cells;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t70 = INT64_C(0);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t71 = ((void)((t69 == NULL || t70 < 0 || t70 >= t69->len) ? ((void)hero_array_at(t69, t70), hero_unreachable()) : (void)0), (void)(t69->elem->size != sizeof(h_fixedbugsafieldstoredbehindanindex_Cell) ? hero_unreachable() : (void)0), ((h_fixedbugsafieldstoredbehindanindex_Cell const *)(const void *)(t69 + 1))[t70]);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t72 = t71.f_tag;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t73 = h2_m;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t74 = HERO_STR_LIT(hero_str_6b);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    {
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
      const void *found = hero_map_find(t73, &t74);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
      if (found == NULL) {
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
        t75 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
      } else {
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
        t75 = (h_0opt_e201354){.tag = INT64_C(0)};
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
        (&hero_desc_int)->copy(&t75.as.ok, found);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
      }
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    }
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t95 = h12_own12;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h12_own12 = t75;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_0opt_e201354_release(&t95);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t96 = h3_f0;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_0opt_e201354_retain(&t75);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h3_f0 = t75;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    h_0opt_e201354_release(&t96);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t76 = h3_f0;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t77 = t76.tag;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t78 = INT64_C(0);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t79 = t77 == t78;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    if (t79) goto bb5; else goto bb6;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
bb4:
#line 611 "fixedbugsafieldstoredbehindanindex.c"
    hero_panic_assert_sides(t37, hero_int_to_str(t44), hero_int_to_str(t45));
    hero_unreachable();
bb5:
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t82 = h3_f0;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t83 = t82.as.ok;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_print_str(t58);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_print_int(t65);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_print_str(t72);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_print_int(t83);
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    hero_print_end();
#line 629 "fixedbugsafieldstoredbehindanindex.c"
    hero_array_release_at(&h0_rows);
    hero_array_release_at(&h1_kept);
    hero_map_release_at(&h2_m);
    h_0opt_e201354_release(hero_slot_escape(&h3_f0));
    h_fixedbugsafieldstoredbehindanindex_Cell_release(hero_slot_escape(&h4_own4));
    hero_array_release_at(&h5_own5);
    h_fixedbugsafieldstoredbehindanindex_Row_release(hero_slot_escape(&h6_own6));
    hero_array_release_at(&h7_own7);
    hero_str_release_at(&h8_own8);
    hero_str_release_at(&h9_own9);
    h_fixedbugsafieldstoredbehindanindex_Cell_release(hero_slot_escape(&h10_own10));
    hero_map_release_at(&h11_own11);
    h_0opt_e201354_release(hero_slot_escape(&h12_own12));
    return;
bb6:
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t80 = h3_f0;
#line 55 "tests/golden/run/fixedbugs-a-field-stored-behind-an-index.hero"
    t81 = t80.as.err;
#line 649 "fixedbugsafieldstoredbehindanindex.c"
    hero_panic_must(t81);
    hero_unreachable();
}
HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Cell_retain(const h_fixedbugsafieldstoredbehindanindex_Cell *v) {
    hero_str_incref(v->f_tag);
}

HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Cell_release(h_fixedbugsafieldstoredbehindanindex_Cell *v) {
    hero_str_decref(v->f_tag);
}

HERO_TU_LOCAL bool h_fixedbugsafieldstoredbehindanindex_Cell_eq(const h_fixedbugsafieldstoredbehindanindex_Cell *a, const h_fixedbugsafieldstoredbehindanindex_Cell *b) {
    if (!(a->f_n == b->f_n)) return false;
    if (!(hero_str_eq(a->f_tag, b->f_tag))) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_fixedbugsafieldstoredbehindanindex_Cell_hash(const void *elem) {
    const h_fixedbugsafieldstoredbehindanindex_Cell *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_int)->hash(&v->f_n)) * UINT64_C(0x100000001b3);
    h = (h ^ (&hero_desc_str)->hash(&v->f_tag)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Row_retain(const h_fixedbugsafieldstoredbehindanindex_Row *v) {
    hero_array_incref(v->f_cells);
    hero_str_incref(v->f_label);
}

HERO_TU_LOCAL void h_fixedbugsafieldstoredbehindanindex_Row_release(h_fixedbugsafieldstoredbehindanindex_Row *v) {
    hero_array_decref(v->f_cells);
    hero_str_decref(v->f_label);
}

HERO_TU_LOCAL bool h_fixedbugsafieldstoredbehindanindex_Row_eq(const h_fixedbugsafieldstoredbehindanindex_Row *a, const h_fixedbugsafieldstoredbehindanindex_Row *b) {
    if (!(hero_array_eq(a->f_cells, b->f_cells))) return false;
    if (!(hero_str_eq(a->f_label, b->f_label))) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_fixedbugsafieldstoredbehindanindex_Row_hash(const void *elem) {
    const h_fixedbugsafieldstoredbehindanindex_Row *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_array)->hash(&v->f_cells)) * UINT64_C(0x100000001b3);
    h = (h ^ (&hero_desc_str)->hash(&v->f_label)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_int)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem) {
    const h_0opt_e201354 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_int)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_fixedbugsafieldstoredbehindanindex_main();
    hero_runtime_check_leaks();
    return 0;
}
