/* Generated by heroes 0.0.1 from tests/golden/run/exit-status.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>

_Static_assert(HERO_RUNTIME_ABI == 15, "heroes_runtime.h is from another compiler");

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_STR(hero_file_read(0, (int64_t *)0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");

#line 111 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)hero_file_read(a0, a1); }
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)hero_file_write(a0, a1); }
#line 114 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)hero_args_at(a0); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)hero_exit(a0); }
#line 43 "exitstatus.c"

HERO_STR_STATIC(hero_str_0, "before");
HERO_STR_STATIC(hero_str_1, "after");

typedef struct h_exitstatus_0opt0 {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_exitstatus_0opt0;

typedef struct h_exitstatus_0opt1 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_exitstatus_0opt1;

void h_exitstatus_0opt0_retain(const h_exitstatus_0opt0 *v);
void h_exitstatus_0opt0_release(h_exitstatus_0opt0 *v);
bool h_exitstatus_0opt0_eq(const h_exitstatus_0opt0 *a, const h_exitstatus_0opt0 *b);
uint64_t h_exitstatus_0opt0_hash(const void *elem);
void h_exitstatus_0opt1_retain(const h_exitstatus_0opt1 *v);
void h_exitstatus_0opt1_release(h_exitstatus_0opt1 *v);
bool h_exitstatus_0opt1_eq(const h_exitstatus_0opt1 *a, const h_exitstatus_0opt1 *b);
uint64_t h_exitstatus_0opt1_hash(const void *elem);

void h_exitstatus_main(void);
void h_library_exit(int64_t h0_code);

#line 18 "tests/golden/run/exit-status.hero"
void h_exitstatus_main(void) {
#line 77 "exitstatus.c"
    HeroStr t1 = {0};
    int64_t t2;
    HeroStr t3 = {0};
    goto bb0;
bb0:
#line 19 "tests/golden/run/exit-status.hero"
    t1 = HERO_STR_LIT(hero_str_0);
#line 19 "tests/golden/run/exit-status.hero"
    hero_print_str(t1);
#line 19 "tests/golden/run/exit-status.hero"
    hero_print_end();
#line 20 "tests/golden/run/exit-status.hero"
    t2 = INT64_C(3);
#line 20 "tests/golden/run/exit-status.hero"
    h_library_exit(t2);
#line 21 "tests/golden/run/exit-status.hero"
    t3 = HERO_STR_LIT(hero_str_1);
#line 21 "tests/golden/run/exit-status.hero"
    hero_print_str(t3);
#line 21 "tests/golden/run/exit-status.hero"
    hero_print_end();
#line 21 "tests/golden/run/exit-status.hero"
    return;
#line 101 "exitstatus.c"
}

#line 148 "<heroes library>"
void h_library_exit(int64_t h0_code) {
#line 106 "exitstatus.c"
    int64_t t1;
    goto bb0;
bb0:
#line 149 "<heroes library>"
    t1 = h0_code;
#line 149 "<heroes library>"
    hero_exit(t1);
#line 149 "<heroes library>"
    return;
#line 116 "exitstatus.c"
}
void h_exitstatus_0opt0_retain(const h_exitstatus_0opt0 *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

void h_exitstatus_0opt0_release(h_exitstatus_0opt0 *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

bool h_exitstatus_0opt0_eq(const h_exitstatus_0opt0 *a, const h_exitstatus_0opt0 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

uint64_t h_exitstatus_0opt0_hash(const void *elem) {
    const h_exitstatus_0opt0 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

void h_exitstatus_0opt1_retain(const h_exitstatus_0opt1 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

void h_exitstatus_0opt1_release(h_exitstatus_0opt1 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

bool h_exitstatus_0opt1_eq(const h_exitstatus_0opt1 *a, const h_exitstatus_0opt1 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

uint64_t h_exitstatus_0opt1_hash(const void *elem) {
    const h_exitstatus_0opt1 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_exitstatus_main();
    hero_runtime_check_leaks();
    return 0;
}
