/* Generated by heroes 0.2.0 from tests/golden/run/mutable-arguments-that-do-not-overlap.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 21, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 45 "mutableargumentsthatdonotoverlap.c"
typedef struct h_mutableargumentsthatdonotoverlap_P {
    int64_t f_x;
    int64_t f_y;
} h_mutableargumentsthatdonotoverlap_P;

typedef struct h_mutableargumentsthatdonotoverlap_Nest {
    h_mutableargumentsthatdonotoverlap_P f_inner;
    int64_t f_tag;
} h_mutableargumentsthatdonotoverlap_Nest;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 117 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 123 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 88 "mutableargumentsthatdonotoverlap.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL bool h_mutableargumentsthatdonotoverlap_P_eq(const h_mutableargumentsthatdonotoverlap_P *a, const h_mutableargumentsthatdonotoverlap_P *b);
HERO_TU_LOCAL uint64_t h_mutableargumentsthatdonotoverlap_P_hash(const void *elem);
HERO_TU_LOCAL bool h_mutableargumentsthatdonotoverlap_Nest_eq(const h_mutableargumentsthatdonotoverlap_Nest *a, const h_mutableargumentsthatdonotoverlap_Nest *b);
HERO_TU_LOCAL uint64_t h_mutableargumentsthatdonotoverlap_Nest_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

static void h_mutableargumentsthatdonotoverlap_P_desc_copy(void *dst, const void *src) {
    *(h_mutableargumentsthatdonotoverlap_P *)dst = *(const h_mutableargumentsthatdonotoverlap_P *)src;
}
static void h_mutableargumentsthatdonotoverlap_P_desc_drop(void *elem) {
    (void)elem;
}
static bool h_mutableargumentsthatdonotoverlap_P_desc_eq(const void *a, const void *b) {
    return h_mutableargumentsthatdonotoverlap_P_eq((const h_mutableargumentsthatdonotoverlap_P *)a, (const h_mutableargumentsthatdonotoverlap_P *)b);
}
HERO_TU_QUIET static const HeroDesc h_mutableargumentsthatdonotoverlap_P_desc = {
    sizeof(h_mutableargumentsthatdonotoverlap_P),
    h_mutableargumentsthatdonotoverlap_P_desc_copy,
    h_mutableargumentsthatdonotoverlap_P_desc_drop,
    h_mutableargumentsthatdonotoverlap_P_desc_eq,
    h_mutableargumentsthatdonotoverlap_P_hash,
};

void h_mutableargumentsthatdonotoverlap_shift(int64_t *ph0_a, int64_t *ph1_b);
void h_mutableargumentsthatdonotoverlap_main(void);

#line 20 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
void h_mutableargumentsthatdonotoverlap_shift(int64_t *ph0_a, int64_t *ph1_b) {
#line 126 "mutableargumentsthatdonotoverlap.c"
    int64_t h0_a;
    int64_t h1_b;
    int64_t t1;
    int64_t t2;
    int64_t t3;
    int64_t t4;
    int64_t t5;
    int64_t t6;
    h0_a = *ph0_a;
    h1_b = *ph1_b;
    goto bb0;
bb0:
#line 21 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t1 = h0_a;
#line 21 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t2 = INT64_C(1);
#line 21 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    if (__builtin_add_overflow(t1, t2, &t3)) hero_panic_overflow();
#line 21 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h0_a = t3;
#line 22 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t4 = h1_b;
#line 22 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t5 = INT64_C(10);
#line 22 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    if (__builtin_add_overflow(t4, t5, &t6)) hero_panic_overflow();
#line 22 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h1_b = t6;
#line 155 "mutableargumentsthatdonotoverlap.c"
    *ph0_a = h0_a;
    *ph1_b = h1_b;
    return;
}

#line 24 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
void h_mutableargumentsthatdonotoverlap_main(void) {
#line 163 "mutableargumentsthatdonotoverlap.c"
    h_mutableargumentsthatdonotoverlap_P h0_p;
    h_mutableargumentsthatdonotoverlap_P h1_q;
    HeroArrayHeader * h2_xs = {0};
    int64_t h3_e0;
    int64_t h4_e1;
    HeroArrayHeader * h5_ys = {0};
    int64_t h6_e2;
    int64_t h7_e3;
    h_mutableargumentsthatdonotoverlap_Nest h8_n;
    HeroArrayHeader * h9_ps = {0};
    int64_t h10_e4;
    int64_t h11_e5;
    int64_t h12_u;
    int64_t h13_v;
    HeroArrayHeader * h14_own14 = {0};
    HeroArrayHeader * h15_own15 = {0};
    int64_t t1;
    int64_t t2;
    h_mutableargumentsthatdonotoverlap_P t3;
    h_mutableargumentsthatdonotoverlap_P t4;
    int64_t t5;
    h_mutableargumentsthatdonotoverlap_P t6;
    int64_t t7;
    h_mutableargumentsthatdonotoverlap_P t8;
    h_mutableargumentsthatdonotoverlap_P t9;
    int64_t t10;
    h_mutableargumentsthatdonotoverlap_P t11;
    int64_t t12;
    int64_t t13;
    int64_t t14;
    int64_t t15;
    HeroArrayHeader * t16 = {0};
    int64_t t17;
    HeroArrayHeader * t18 = {0};
    int64_t t19;
    int64_t t20;
    HeroArrayHeader * t21 = {0};
    int64_t t22;
    int64_t t23;
    int64_t t24;
    HeroArrayHeader * t25 = {0};
    int64_t t26;
    int64_t t27;
    HeroArrayHeader * t28 = {0};
    int64_t t29;
    int64_t t30;
    HeroArrayHeader * t31 = {0};
    int64_t t32;
    int64_t t33;
    HeroArrayHeader * t34 = {0};
    int64_t t35;
    HeroArrayHeader * t36 = {0};
    int64_t t37;
    int64_t t38;
    HeroArrayHeader * t39 = {0};
    int64_t t40;
    int64_t t41;
    int64_t t42;
    HeroArrayHeader * t43 = {0};
    int64_t t44;
    int64_t t45;
    HeroArrayHeader * t46 = {0};
    int64_t t47;
    int64_t t48;
    int64_t t49;
    int64_t t50;
    h_mutableargumentsthatdonotoverlap_P t51;
    int64_t t52;
    h_mutableargumentsthatdonotoverlap_Nest t53;
    h_mutableargumentsthatdonotoverlap_Nest t54;
    h_mutableargumentsthatdonotoverlap_P t55;
    int64_t t56;
    h_mutableargumentsthatdonotoverlap_Nest t57;
    h_mutableargumentsthatdonotoverlap_P t58;
    int64_t t59;
    h_mutableargumentsthatdonotoverlap_Nest t60;
    h_mutableargumentsthatdonotoverlap_P t61;
    int64_t t62;
    h_mutableargumentsthatdonotoverlap_Nest t63;
    int64_t t64;
    int64_t t65;
    int64_t t66;
    h_mutableargumentsthatdonotoverlap_P t67;
    int64_t t68;
    int64_t t69;
    h_mutableargumentsthatdonotoverlap_P t70;
    HeroArrayHeader * t71 = {0};
    int64_t t72;
    HeroArrayHeader * t73 = {0};
    h_mutableargumentsthatdonotoverlap_P t74;
    int64_t t75;
    int64_t t76;
    HeroArrayHeader * t77 = {0};
    h_mutableargumentsthatdonotoverlap_P t78;
    int64_t t79;
    int64_t t80;
    int64_t t81;
    HeroArrayHeader * t82 = {0};
    int64_t t83;
    h_mutableargumentsthatdonotoverlap_P t84;
    int64_t t85;
    HeroArrayHeader * t86 = {0};
    int64_t t87;
    h_mutableargumentsthatdonotoverlap_P t88;
    int64_t t89;
    int64_t t90;
    int64_t t91;
    int64_t t92;
    int64_t t93;
    HeroArrayHeader * t94 = {0};
    HeroArrayHeader * t95 = {0};
    HeroArrayHeader * t96 = {0};
    HeroArrayHeader * t97 = {0};
    HeroArrayHeader * t98 = {0};
    goto bb0;
bb0:
#line 26 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t1 = INT64_C(0);
#line 26 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t2 = INT64_C(0);
#line 26 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t3 = (h_mutableargumentsthatdonotoverlap_P){.f_x = t1, .f_y = t2};
#line 26 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h0_p = t3;
#line 27 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h0_p.f_x, &h0_p.f_y);
#line 28 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t4 = h0_p;
#line 28 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t5 = t4.f_x;
#line 28 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t5);
#line 28 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 29 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t6 = h0_p;
#line 29 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t7 = t6.f_y;
#line 29 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t7);
#line 29 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 33 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t8 = h0_p;
#line 33 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h1_q = t8;
#line 34 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h0_p.f_x, &h0_p.f_y);
#line 35 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t9 = h0_p;
#line 35 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t10 = t9.f_x;
#line 35 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t10);
#line 35 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 36 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t11 = h1_q;
#line 36 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t12 = t11.f_x;
#line 36 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t12);
#line 36 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t13 = INT64_C(0);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t14 = INT64_C(0);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t15 = INT64_C(0);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t16 = hero_array_new(&hero_desc_int, 3);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    { HeroArrayHeader *grown = hero_array_push(t16, &t13);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
      hero_array_decref(t16); t16 = grown; }
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    { HeroArrayHeader *grown = hero_array_push(t16, &t14);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
      hero_array_decref(t16); t16 = grown; }
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    { HeroArrayHeader *grown = hero_array_push(t16, &t15);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
      hero_array_decref(t16); t16 = grown; }
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t94 = h14_own14;
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h14_own14 = t16;
#line 352 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(t94);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t95 = h2_xs;
#line 356 "mutableargumentsthatdonotoverlap.c"
    hero_array_incref(t16);
#line 39 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h2_xs = t16;
#line 360 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(t95);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t17 = INT64_C(0);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t18 = h2_xs;
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t19 = *(int64_t const *)hero_array_at(t18, t17);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h3_e0 = t19;
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t20 = INT64_C(1);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t21 = h2_xs;
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t22 = *(int64_t const *)hero_array_at(t21, t20);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h4_e1 = t22;
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h3_e0, &h4_e1);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t23 = h3_e0;
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_array_set(&(h2_xs), t17, &t23);
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t24 = h4_e1;
#line 40 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_array_set(&(h2_xs), t20, &t24);
#line 41 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t25 = h2_xs;
#line 41 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t26 = INT64_C(0);
#line 41 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t27 = *(int64_t const *)hero_array_at(t25, t26);
#line 41 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t27);
#line 41 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 42 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t28 = h2_xs;
#line 42 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t29 = INT64_C(1);
#line 42 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t30 = *(int64_t const *)hero_array_at(t28, t29);
#line 42 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t30);
#line 42 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 43 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t31 = h2_xs;
#line 43 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t32 = INT64_C(2);
#line 43 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t33 = *(int64_t const *)hero_array_at(t31, t32);
#line 43 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t33);
#line 43 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 44 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t34 = h2_xs;
#line 44 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t96 = h5_ys;
#line 422 "mutableargumentsthatdonotoverlap.c"
    hero_array_incref(t34);
#line 44 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h5_ys = t34;
#line 426 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(t96);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t35 = INT64_C(0);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t36 = h2_xs;
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t37 = *(int64_t const *)hero_array_at(t36, t35);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h6_e2 = t37;
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t38 = INT64_C(2);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t39 = h2_xs;
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t40 = *(int64_t const *)hero_array_at(t39, t38);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h7_e3 = t40;
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h6_e2, &h7_e3);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t41 = h6_e2;
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_array_set(&(h2_xs), t35, &t41);
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t42 = h7_e3;
#line 45 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_array_set(&(h2_xs), t38, &t42);
#line 46 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t43 = h2_xs;
#line 46 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t44 = INT64_C(0);
#line 46 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t45 = *(int64_t const *)hero_array_at(t43, t44);
#line 46 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t45);
#line 46 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 47 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t46 = h5_ys;
#line 47 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t47 = INT64_C(0);
#line 47 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t48 = *(int64_t const *)hero_array_at(t46, t47);
#line 47 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t48);
#line 47 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 50 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t49 = INT64_C(0);
#line 50 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t50 = INT64_C(0);
#line 50 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t51 = (h_mutableargumentsthatdonotoverlap_P){.f_x = t49, .f_y = t50};
#line 50 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t52 = INT64_C(7);
#line 50 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t53 = (h_mutableargumentsthatdonotoverlap_Nest){.f_inner = t51, .f_tag = t52};
#line 50 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h8_n = t53;
#line 51 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h8_n.f_inner.f_x, &h8_n.f_inner.f_y);
#line 52 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t54 = h8_n;
#line 52 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t55 = t54.f_inner;
#line 52 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t56 = t55.f_x;
#line 52 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t56);
#line 52 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 53 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t57 = h8_n;
#line 53 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t58 = t57.f_inner;
#line 53 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t59 = t58.f_y;
#line 53 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t59);
#line 53 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 56 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h8_n.f_inner.f_x, &h8_n.f_tag);
#line 57 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t60 = h8_n;
#line 57 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t61 = t60.f_inner;
#line 57 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t62 = t61.f_x;
#line 57 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t62);
#line 57 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 58 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t63 = h8_n;
#line 58 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t64 = t63.f_tag;
#line 58 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t64);
#line 58 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t65 = INT64_C(0);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t66 = INT64_C(0);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t67 = (h_mutableargumentsthatdonotoverlap_P){.f_x = t65, .f_y = t66};
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t68 = INT64_C(0);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t69 = INT64_C(0);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t70 = (h_mutableargumentsthatdonotoverlap_P){.f_x = t68, .f_y = t69};
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t71 = hero_array_new(&h_mutableargumentsthatdonotoverlap_P_desc, 2);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    { HeroArrayHeader *grown = hero_array_push(t71, &t67);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
      hero_array_decref(t71); t71 = grown; }
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    { HeroArrayHeader *grown = hero_array_push(t71, &t70);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
      hero_array_decref(t71); t71 = grown; }
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t97 = h15_own15;
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h15_own15 = t71;
#line 554 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(t97);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t98 = h9_ps;
#line 558 "mutableargumentsthatdonotoverlap.c"
    hero_array_incref(t71);
#line 62 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h9_ps = t71;
#line 562 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(t98);
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t72 = INT64_C(0);
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t73 = h9_ps;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t74 = *(h_mutableargumentsthatdonotoverlap_P const *)hero_array_at(t73, t72);
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t75 = t74.f_x;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h10_e4 = t75;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t76 = INT64_C(0);
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t77 = h9_ps;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t78 = *(h_mutableargumentsthatdonotoverlap_P const *)hero_array_at(t77, t76);
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t79 = t78.f_y;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h11_e5 = t79;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h10_e4, &h11_e5);
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t80 = h10_e4;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_array_unshare(&(h9_ps));
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    (*(h_mutableargumentsthatdonotoverlap_P *)hero_array_at_mut(h9_ps, t72)).f_x = t80;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t81 = h11_e5;
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_array_unshare(&(h9_ps));
#line 63 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    (*(h_mutableargumentsthatdonotoverlap_P *)hero_array_at_mut(h9_ps, t76)).f_y = t81;
#line 64 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t82 = h9_ps;
#line 64 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t83 = INT64_C(0);
#line 64 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t84 = *(h_mutableargumentsthatdonotoverlap_P const *)hero_array_at(t82, t83);
#line 64 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t85 = t84.f_x;
#line 64 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t85);
#line 64 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 65 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t86 = h9_ps;
#line 65 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t87 = INT64_C(0);
#line 65 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t88 = *(h_mutableargumentsthatdonotoverlap_P const *)hero_array_at(t86, t87);
#line 65 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t89 = t88.f_y;
#line 65 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t89);
#line 65 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 68 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t90 = INT64_C(0);
#line 68 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h12_u = t90;
#line 69 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t91 = INT64_C(0);
#line 69 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h13_v = t91;
#line 70 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    h_mutableargumentsthatdonotoverlap_shift(&h12_u, &h13_v);
#line 71 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t92 = h12_u;
#line 71 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t92);
#line 71 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    t93 = h13_v;
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_int(t93);
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
    hero_print_end();
#line 644 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(h2_xs);
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
#line 647 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(h5_ys);
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
#line 650 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(h9_ps);
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
#line 653 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(h14_own14);
#line 72 "tests/golden/run/mutable-arguments-that-do-not-overlap.hero"
#line 656 "mutableargumentsthatdonotoverlap.c"
    hero_array_decref(h15_own15);
    return;
}
HERO_TU_LOCAL bool h_mutableargumentsthatdonotoverlap_P_eq(const h_mutableargumentsthatdonotoverlap_P *a, const h_mutableargumentsthatdonotoverlap_P *b) {
    if (!(a->f_x == b->f_x)) return false;
    if (!(a->f_y == b->f_y)) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_mutableargumentsthatdonotoverlap_P_hash(const void *elem) {
    const h_mutableargumentsthatdonotoverlap_P *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_int)->hash(&v->f_x)) * UINT64_C(0x100000001b3);
    h = (h ^ (&hero_desc_int)->hash(&v->f_y)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL bool h_mutableargumentsthatdonotoverlap_Nest_eq(const h_mutableargumentsthatdonotoverlap_Nest *a, const h_mutableargumentsthatdonotoverlap_Nest *b) {
    if (!(h_mutableargumentsthatdonotoverlap_P_eq(&a->f_inner, &b->f_inner))) return false;
    if (!(a->f_tag == b->f_tag)) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_mutableargumentsthatdonotoverlap_Nest_hash(const void *elem) {
    const h_mutableargumentsthatdonotoverlap_Nest *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ h_mutableargumentsthatdonotoverlap_P_hash(&v->f_inner)) * UINT64_C(0x100000001b3);
    h = (h ^ (&hero_desc_int)->hash(&v->f_tag)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_mutableargumentsthatdonotoverlap_main();
    hero_runtime_check_leaks();
    return 0;
}
