/* Generated by heroes 0.0.1 from tests/golden/run/premise-mangler-hash-in-heroes.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 19, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 43 "premisemanglerhashinheroes.c"
#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 111 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 114 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 122 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 61 "premisemanglerhashinheroes.c"
#pragma clang diagnostic pop

HERO_STR_STATIC(hero_str_1afbd0d1, "map<i64, str>");
HERO_STR_STATIC(hero_str_38777701, "fold<i64, i64>");
HERO_STR_STATIC(hero_str_642c20d9, "pair<i64, str_x>");
HERO_STR_STATIC(hero_str_1343f73c, "pair<i64_str, x>");

typedef struct h_0opt_e201354 {
    int64_t tag;
    union {
        int64_t ok;
        HeroFailure err;
    } as;
} h_0opt_e201354;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v);
HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v);
HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b);
HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

int64_t h_premisemanglerhashinheroes_typehash(HeroStr h0_rendered);
void h_premisemanglerhashinheroes_main(void);
HeroArrayHeader * h_library_range(int64_t h0_from, int64_t h1_to);

#line 24 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
int64_t h_premisemanglerhashinheroes_typehash(HeroStr h0_rendered) {
#line 111 "premisemanglerhashinheroes.c"
    int64_t h1_h;
    HeroArrayHeader * h2_xs0 = {0};
    int64_t h3_i0;
    int64_t h4_i;
    h_0opt_e201354 h5_f0 = {0};
    HeroArrayHeader * h6_own6 = {0};
    h_0opt_e201354 h7_own7 = {0};
    int64_t t1;
    int64_t t2;
    HeroStr t3 = {0};
    int64_t t4;
    HeroArrayHeader * t5 = {0};
    int64_t t6;
    int64_t t7;
    HeroArrayHeader * t8 = {0};
    int64_t t9;
    bool t10;
    HeroArrayHeader * t11 = {0};
    int64_t t12;
    int64_t t13;
    int64_t t14;
    int64_t t15;
    int64_t t16;
    HeroStr t17 = {0};
    int64_t t18;
    uint8_t t19;
    h_0opt_e201354 t20 = {0};
    h_0opt_e201354 t21 = {0};
    int64_t t22;
    int64_t t23;
    bool t24;
    h_0opt_e201354 t25 = {0};
    HeroFailure t26 = {0};
    h_0opt_e201354 t27 = {0};
    int64_t t28;
    int64_t t29;
    int64_t t30;
    int64_t t31;
    int64_t t32;
    int64_t t33;
    int64_t t34;
    int64_t t35;
    HeroArrayHeader * t36 = {0};
    HeroArrayHeader * t37 = {0};
    h_0opt_e201354 t38 = {0};
    h_0opt_e201354 t39 = {0};
    HeroArrayHeader * t40 = {0};
    h_0opt_e201354 t41 = {0};
    HeroArrayHeader * t42 = {0};
    h_0opt_e201354 t43 = {0};
    goto bb0;
bb0:
#line 25 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t1 = INT64_C(0);
#line 25 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h1_h = t1;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t2 = INT64_C(0);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t3 = h0_rendered;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t4 = hero_str_len(t3);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t5 = h_library_range(t2, t4);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t36 = h6_own6;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h6_own6 = t5;
#line 180 "premisemanglerhashinheroes.c"
    hero_array_decref(t36);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t37 = h2_xs0;
#line 184 "premisemanglerhashinheroes.c"
    hero_array_incref(t5);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h2_xs0 = t5;
#line 188 "premisemanglerhashinheroes.c"
    hero_array_decref(t37);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t6 = INT64_C(0);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h3_i0 = t6;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    goto bb1;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
bb1:
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t7 = h3_i0;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t8 = h2_xs0;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t9 = hero_array_len(t8);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t10 = t7 < t9;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (t10) goto bb2; else goto bb4;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
bb2:
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t11 = h2_xs0;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t12 = h3_i0;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t13 = *(int64_t const *)hero_array_at(t11, t12);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h4_i = t13;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t14 = h1_h;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t15 = INT64_C(131);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (__builtin_mul_overflow(t14, t15, &t16)) hero_panic_overflow();
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t17 = h0_rendered;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t18 = h4_i;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t19 = hero_str_byte(t17, t18);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t20 = (h_0opt_e201354){.tag = INT64_C(0), .as.ok = (int64_t)t19};
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t38 = h7_own7;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h7_own7 = t20;
#line 236 "premisemanglerhashinheroes.c"
    h_0opt_e201354_release(&t38);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t39 = h5_f0;
#line 240 "premisemanglerhashinheroes.c"
    h_0opt_e201354_retain(&t20);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h5_f0 = t20;
#line 244 "premisemanglerhashinheroes.c"
    h_0opt_e201354_release(&t39);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t21 = h5_f0;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t22 = t21.tag;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t23 = INT64_C(0);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t24 = t22 == t23;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (t24) goto bb5; else goto bb6;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
bb3:
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t32 = h3_i0;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t33 = INT64_C(1);
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (__builtin_add_overflow(t32, t33, &t34)) hero_panic_overflow();
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h3_i0 = t34;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    goto bb1;
#line 27 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
bb4:
#line 30 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t35 = h1_h;
#line 30 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t40 = h2_xs0;
#line 274 "premisemanglerhashinheroes.c"
    hero_array_decref(t40);
#line 30 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t41 = h5_f0;
#line 278 "premisemanglerhashinheroes.c"
    h_0opt_e201354_release(&t41);
#line 30 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t42 = h6_own6;
#line 282 "premisemanglerhashinheroes.c"
    hero_array_decref(t42);
#line 30 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t43 = h7_own7;
#line 286 "premisemanglerhashinheroes.c"
    h_0opt_e201354_release(&t43);
    return t35;
bb5:
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t27 = h5_f0;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t28 = t27.as.ok;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (__builtin_add_overflow(t16, t28, &t29)) hero_panic_overflow();
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t30 = INT64_C(2147483647);
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (t30 == 0) hero_panic("division by zero");
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    if (t29 == INT64_MIN && t30 == INT64_C(-1)) hero_panic("`%` by -1 at the smallest i64: the remainder is 0, but C reaches it through a quotient that has no int64");
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t31 = t29 % t30;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    h1_h = t31;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    goto bb3;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
bb6:
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t25 = h5_f0;
#line 28 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t26 = t25.as.err;
#line 314 "premisemanglerhashinheroes.c"
    hero_panic_must(t26);
    hero_unreachable();
}

#line 32 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
void h_premisemanglerhashinheroes_main(void) {
#line 321 "premisemanglerhashinheroes.c"
    HeroStr t1 = {0};
    int64_t t2;
    HeroStr t3 = {0};
    int64_t t4;
    HeroStr t5 = {0};
    int64_t t6;
    HeroStr t7 = {0};
    int64_t t8;
    goto bb0;
bb0:
#line 33 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t1 = HERO_STR_LIT(hero_str_1afbd0d1);
#line 33 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t2 = h_premisemanglerhashinheroes_typehash(t1);
#line 33 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_int(t2);
#line 33 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_end();
#line 34 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t3 = HERO_STR_LIT(hero_str_38777701);
#line 34 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t4 = h_premisemanglerhashinheroes_typehash(t3);
#line 34 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_int(t4);
#line 34 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_end();
#line 38 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t5 = HERO_STR_LIT(hero_str_642c20d9);
#line 38 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t6 = h_premisemanglerhashinheroes_typehash(t5);
#line 38 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_int(t6);
#line 38 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_end();
#line 39 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t7 = HERO_STR_LIT(hero_str_1343f73c);
#line 39 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    t8 = h_premisemanglerhashinheroes_typehash(t7);
#line 39 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_int(t8);
#line 39 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    hero_print_end();
#line 39 "tests/golden/run/premise-mangler-hash-in-heroes.hero"
    return;
#line 366 "premisemanglerhashinheroes.c"
}

#line 26 "<heroes library>"
HeroArrayHeader * h_library_range(int64_t h0_from, int64_t h1_to) {
#line 371 "premisemanglerhashinheroes.c"
    HeroArrayHeader * h2_out = {0};
    int64_t h3_i;
    HeroArrayHeader * h4_own4 = {0};
    HeroArrayHeader * t1 = {0};
    int64_t t2;
    int64_t t3;
    int64_t t4;
    bool t5;
    int64_t t7;
    int64_t t9;
    int64_t t10;
    int64_t t11;
    HeroArrayHeader * t12 = {0};
    HeroArrayHeader * t13 = {0};
    HeroArrayHeader * t14 = {0};
    HeroArrayHeader * t15 = {0};
    HeroArrayHeader * t16 = {0};
    goto bb0;
bb0:
#line 27 "<heroes library>"
    t1 = hero_array_new(&hero_desc_int, 1);
#line 27 "<heroes library>"
    t13 = h4_own4;
#line 27 "<heroes library>"
    h4_own4 = t1;
#line 397 "premisemanglerhashinheroes.c"
    hero_array_decref(t13);
#line 27 "<heroes library>"
    t14 = h2_out;
#line 401 "premisemanglerhashinheroes.c"
    hero_array_incref(t1);
#line 27 "<heroes library>"
    h2_out = t1;
#line 405 "premisemanglerhashinheroes.c"
    hero_array_decref(t14);
#line 28 "<heroes library>"
    t2 = h0_from;
#line 28 "<heroes library>"
    h3_i = t2;
#line 28 "<heroes library>"
    goto bb1;
#line 28 "<heroes library>"
bb1:
#line 29 "<heroes library>"
    t3 = h3_i;
#line 29 "<heroes library>"
    t4 = h1_to;
#line 29 "<heroes library>"
    t5 = t3 < t4;
#line 29 "<heroes library>"
    if (t5) goto bb2; else goto bb3;
#line 29 "<heroes library>"
bb2:
#line 30 "<heroes library>"
    t7 = h3_i;
#line 30 "<heroes library>"
    hero_array_push_owned(&h2_out, &t7);
#line 31 "<heroes library>"
    t9 = h3_i;
#line 31 "<heroes library>"
    t10 = INT64_C(1);
#line 31 "<heroes library>"
    if (__builtin_add_overflow(t9, t10, &t11)) hero_panic_overflow();
#line 31 "<heroes library>"
    h3_i = t11;
#line 31 "<heroes library>"
    goto bb1;
#line 31 "<heroes library>"
bb3:
#line 32 "<heroes library>"
    t12 = h2_out;
#line 443 "premisemanglerhashinheroes.c"
    hero_array_incref(t12);
#line 32 "<heroes library>"
    t15 = h2_out;
#line 447 "premisemanglerhashinheroes.c"
    hero_array_decref(t15);
#line 32 "<heroes library>"
    t16 = h4_own4;
#line 451 "premisemanglerhashinheroes.c"
    hero_array_decref(t16);
    return t12;
}
HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_int)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem) {
    const h_0opt_e201354 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_int)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_premisemanglerhashinheroes_main();
    hero_runtime_check_leaks();
    return 0;
}
