/* Generated by heroes 0.0.1 from tests/golden/run/crlf-literal.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 20, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 45 "crlfliteral.c"
#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 117 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 123 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 63 "crlfliteral.c"
#pragma clang diagnostic pop

HERO_STR_STATIC(hero_str_6b1, "\015\n");
HERO_STR_STATIC(hero_str_995c286, "GET ");
HERO_STR_STATIC(hero_str_59caaa51, " HTTP/1.1");
HERO_STR_STATIC(hero_str_692ea516, "Host: ");
HERO_STR_STATIC(hero_str_71c6be1f, "example.com");
HERO_STR_STATIC(hero_str_2f, "/");

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

HeroStr h_crlfliteral_crlf(void);
HeroStr h_crlfliteral_request(HeroStr h0_host, HeroStr h1_path);
void h_crlfliteral_main(void);

#line 8 "tests/golden/run/crlf-literal.hero"
HeroStr h_crlfliteral_crlf(void) {
#line 103 "crlfliteral.c"
    HeroStr t1 = {0};
    goto bb0;
bb0:
#line 9 "tests/golden/run/crlf-literal.hero"
    t1 = HERO_STR_LIT(hero_str_6b1);
#line 109 "crlfliteral.c"
    hero_str_incref(t1);
    return t1;
}

#line 11 "tests/golden/run/crlf-literal.hero"
HeroStr h_crlfliteral_request(HeroStr h0_host, HeroStr h1_path) {
#line 116 "crlfliteral.c"
    HeroStr h2_line = {0};
    HeroStr h3_own3 = {0};
    HeroStr h4_own4 = {0};
    HeroStr h5_own5 = {0};
    HeroStr h6_own6 = {0};
    HeroStr h7_own7 = {0};
    HeroStr h8_own8 = {0};
    HeroStr h9_own9 = {0};
    HeroStr h10_own10 = {0};
    HeroStr h11_own11 = {0};
    HeroStr h12_own12 = {0};
    HeroStr t1 = {0};
    HeroStr t2 = {0};
    HeroStr t3 = {0};
    HeroStr t4 = {0};
    HeroStr t5 = {0};
    HeroStr t6 = {0};
    HeroStr t7 = {0};
    HeroStr t8 = {0};
    HeroStr t9 = {0};
    HeroStr t10 = {0};
    HeroStr t11 = {0};
    HeroStr t12 = {0};
    HeroStr t13 = {0};
    HeroStr t14 = {0};
    HeroStr t15 = {0};
    HeroStr t16 = {0};
    HeroStr t17 = {0};
    HeroStr t18 = {0};
    HeroStr t19 = {0};
    HeroStr t20 = {0};
    HeroStr t21 = {0};
    HeroStr t22 = {0};
    HeroStr t23 = {0};
    HeroStr t24 = {0};
    HeroStr t25 = {0};
    HeroStr t26 = {0};
    HeroStr t27 = {0};
    goto bb0;
bb0:
#line 12 "tests/golden/run/crlf-literal.hero"
    t1 = HERO_STR_LIT(hero_str_995c286);
#line 12 "tests/golden/run/crlf-literal.hero"
    t2 = h1_path;
#line 12 "tests/golden/run/crlf-literal.hero"
    t3 = hero_str_concat(t1, t2);
#line 12 "tests/golden/run/crlf-literal.hero"
    t17 = h3_own3;
#line 12 "tests/golden/run/crlf-literal.hero"
    h3_own3 = t3;
#line 167 "crlfliteral.c"
    hero_str_decref(t17);
#line 12 "tests/golden/run/crlf-literal.hero"
    t4 = HERO_STR_LIT(hero_str_59caaa51);
#line 12 "tests/golden/run/crlf-literal.hero"
    t5 = hero_str_concat(t3, t4);
#line 12 "tests/golden/run/crlf-literal.hero"
    t18 = h4_own4;
#line 12 "tests/golden/run/crlf-literal.hero"
    h4_own4 = t5;
#line 177 "crlfliteral.c"
    hero_str_decref(t18);
#line 12 "tests/golden/run/crlf-literal.hero"
    t6 = h_crlfliteral_crlf();
#line 12 "tests/golden/run/crlf-literal.hero"
    t19 = h5_own5;
#line 12 "tests/golden/run/crlf-literal.hero"
    h5_own5 = t6;
#line 185 "crlfliteral.c"
    hero_str_decref(t19);
#line 12 "tests/golden/run/crlf-literal.hero"
    t7 = hero_str_concat(t5, t6);
#line 12 "tests/golden/run/crlf-literal.hero"
    t20 = h6_own6;
#line 12 "tests/golden/run/crlf-literal.hero"
    h6_own6 = t7;
#line 193 "crlfliteral.c"
    hero_str_decref(t20);
#line 12 "tests/golden/run/crlf-literal.hero"
    t21 = h2_line;
#line 197 "crlfliteral.c"
    hero_str_incref(t7);
#line 12 "tests/golden/run/crlf-literal.hero"
    h2_line = t7;
#line 201 "crlfliteral.c"
    hero_str_decref(t21);
#line 13 "tests/golden/run/crlf-literal.hero"
    t8 = h2_line;
#line 13 "tests/golden/run/crlf-literal.hero"
    t9 = HERO_STR_LIT(hero_str_692ea516);
#line 13 "tests/golden/run/crlf-literal.hero"
    t10 = hero_str_concat(t8, t9);
#line 13 "tests/golden/run/crlf-literal.hero"
    t22 = h7_own7;
#line 13 "tests/golden/run/crlf-literal.hero"
    h7_own7 = t10;
#line 213 "crlfliteral.c"
    hero_str_decref(t22);
#line 13 "tests/golden/run/crlf-literal.hero"
    t11 = h0_host;
#line 13 "tests/golden/run/crlf-literal.hero"
    t12 = hero_str_concat(t10, t11);
#line 13 "tests/golden/run/crlf-literal.hero"
    t23 = h8_own8;
#line 13 "tests/golden/run/crlf-literal.hero"
    h8_own8 = t12;
#line 223 "crlfliteral.c"
    hero_str_decref(t23);
#line 13 "tests/golden/run/crlf-literal.hero"
    t13 = h_crlfliteral_crlf();
#line 13 "tests/golden/run/crlf-literal.hero"
    t24 = h9_own9;
#line 13 "tests/golden/run/crlf-literal.hero"
    h9_own9 = t13;
#line 231 "crlfliteral.c"
    hero_str_decref(t24);
#line 13 "tests/golden/run/crlf-literal.hero"
    t14 = hero_str_concat(t12, t13);
#line 13 "tests/golden/run/crlf-literal.hero"
    t25 = h10_own10;
#line 13 "tests/golden/run/crlf-literal.hero"
    h10_own10 = t14;
#line 239 "crlfliteral.c"
    hero_str_decref(t25);
#line 13 "tests/golden/run/crlf-literal.hero"
    t15 = h_crlfliteral_crlf();
#line 13 "tests/golden/run/crlf-literal.hero"
    t26 = h11_own11;
#line 13 "tests/golden/run/crlf-literal.hero"
    h11_own11 = t15;
#line 247 "crlfliteral.c"
    hero_str_decref(t26);
#line 13 "tests/golden/run/crlf-literal.hero"
    t16 = hero_str_concat(t14, t15);
#line 13 "tests/golden/run/crlf-literal.hero"
    t27 = h12_own12;
#line 13 "tests/golden/run/crlf-literal.hero"
    h12_own12 = t16;
#line 255 "crlfliteral.c"
    hero_str_decref(t27);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 258 "crlfliteral.c"
    hero_str_incref(t16);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 261 "crlfliteral.c"
    hero_str_decref(h2_line);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 264 "crlfliteral.c"
    hero_str_decref(h3_own3);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 267 "crlfliteral.c"
    hero_str_decref(h4_own4);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 270 "crlfliteral.c"
    hero_str_decref(h5_own5);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 273 "crlfliteral.c"
    hero_str_decref(h6_own6);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 276 "crlfliteral.c"
    hero_str_decref(h7_own7);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 279 "crlfliteral.c"
    hero_str_decref(h8_own8);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 282 "crlfliteral.c"
    hero_str_decref(h9_own9);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 285 "crlfliteral.c"
    hero_str_decref(h10_own10);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 288 "crlfliteral.c"
    hero_str_decref(h11_own11);
#line 13 "tests/golden/run/crlf-literal.hero"
#line 291 "crlfliteral.c"
    hero_str_decref(h12_own12);
    return t16;
}

#line 15 "tests/golden/run/crlf-literal.hero"
void h_crlfliteral_main(void) {
#line 298 "crlfliteral.c"
    HeroStr h0_e = {0};
    HeroStr h1_r = {0};
    HeroStr h2_own2 = {0};
    HeroStr h3_own3 = {0};
    HeroStr t1 = {0};
    HeroStr t2 = {0};
    int64_t t3;
    HeroStr t4 = {0};
    int64_t t5;
    uint8_t t6;
    HeroStr t7 = {0};
    int64_t t8;
    uint8_t t9;
    int64_t t10;
    HeroStr t11 = {0};
    HeroStr t12 = {0};
    HeroStr t13 = {0};
    HeroStr t14 = {0};
    int64_t t15;
    HeroStr t16 = {0};
    HeroStr t17 = {0};
    int64_t t18;
    int64_t t19;
    int64_t t20;
    uint8_t t21;
    HeroStr t22 = {0};
    HeroStr t23 = {0};
    int64_t t24;
    int64_t t25;
    int64_t t26;
    uint8_t t27;
    HeroStr t28 = {0};
    HeroStr t29 = {0};
    int64_t t30;
    int64_t t31;
    int64_t t32;
    uint8_t t33;
    HeroStr t34 = {0};
    HeroStr t35 = {0};
    int64_t t36;
    int64_t t37;
    int64_t t38;
    uint8_t t39;
    HeroStr t40 = {0};
    HeroStr t41 = {0};
    HeroStr t42 = {0};
    HeroStr t43 = {0};
    goto bb0;
bb0:
#line 17 "tests/golden/run/crlf-literal.hero"
    t1 = h_crlfliteral_crlf();
#line 17 "tests/golden/run/crlf-literal.hero"
    t40 = h2_own2;
#line 17 "tests/golden/run/crlf-literal.hero"
    h2_own2 = t1;
#line 354 "crlfliteral.c"
    hero_str_decref(t40);
#line 17 "tests/golden/run/crlf-literal.hero"
    t41 = h0_e;
#line 358 "crlfliteral.c"
    hero_str_incref(t1);
#line 17 "tests/golden/run/crlf-literal.hero"
    h0_e = t1;
#line 362 "crlfliteral.c"
    hero_str_decref(t41);
#line 18 "tests/golden/run/crlf-literal.hero"
    t2 = h0_e;
#line 18 "tests/golden/run/crlf-literal.hero"
    t3 = hero_str_len(t2);
#line 18 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t3);
#line 18 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 19 "tests/golden/run/crlf-literal.hero"
    t4 = h0_e;
#line 19 "tests/golden/run/crlf-literal.hero"
    t5 = INT64_C(0);
#line 19 "tests/golden/run/crlf-literal.hero"
    t6 = hero_str_byte(t4, t5);
#line 19 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t6);
#line 19 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 20 "tests/golden/run/crlf-literal.hero"
    t7 = h0_e;
#line 20 "tests/golden/run/crlf-literal.hero"
    t8 = INT64_C(1);
#line 20 "tests/golden/run/crlf-literal.hero"
    t9 = hero_str_byte(t7, t8);
#line 20 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t9);
#line 20 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 23 "tests/golden/run/crlf-literal.hero"
    t10 = INT64_C(13);
#line 23 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t10);
#line 23 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 26 "tests/golden/run/crlf-literal.hero"
    t11 = HERO_STR_LIT(hero_str_71c6be1f);
#line 26 "tests/golden/run/crlf-literal.hero"
    t12 = HERO_STR_LIT(hero_str_2f);
#line 26 "tests/golden/run/crlf-literal.hero"
    t13 = h_crlfliteral_request(t11, t12);
#line 26 "tests/golden/run/crlf-literal.hero"
    t42 = h3_own3;
#line 26 "tests/golden/run/crlf-literal.hero"
    h3_own3 = t13;
#line 408 "crlfliteral.c"
    hero_str_decref(t42);
#line 26 "tests/golden/run/crlf-literal.hero"
    t43 = h1_r;
#line 412 "crlfliteral.c"
    hero_str_incref(t13);
#line 26 "tests/golden/run/crlf-literal.hero"
    h1_r = t13;
#line 416 "crlfliteral.c"
    hero_str_decref(t43);
#line 27 "tests/golden/run/crlf-literal.hero"
    t14 = h1_r;
#line 27 "tests/golden/run/crlf-literal.hero"
    t15 = hero_str_len(t14);
#line 27 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t15);
#line 27 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 28 "tests/golden/run/crlf-literal.hero"
    t16 = h1_r;
#line 28 "tests/golden/run/crlf-literal.hero"
    t17 = h1_r;
#line 28 "tests/golden/run/crlf-literal.hero"
    t18 = hero_str_len(t17);
#line 28 "tests/golden/run/crlf-literal.hero"
    t19 = INT64_C(4);
#line 28 "tests/golden/run/crlf-literal.hero"
    if (__builtin_sub_overflow(t18, t19, &t20)) hero_panic_overflow();
#line 28 "tests/golden/run/crlf-literal.hero"
    t21 = hero_str_byte(t16, t20);
#line 28 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t21);
#line 28 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 29 "tests/golden/run/crlf-literal.hero"
    t22 = h1_r;
#line 29 "tests/golden/run/crlf-literal.hero"
    t23 = h1_r;
#line 29 "tests/golden/run/crlf-literal.hero"
    t24 = hero_str_len(t23);
#line 29 "tests/golden/run/crlf-literal.hero"
    t25 = INT64_C(3);
#line 29 "tests/golden/run/crlf-literal.hero"
    if (__builtin_sub_overflow(t24, t25, &t26)) hero_panic_overflow();
#line 29 "tests/golden/run/crlf-literal.hero"
    t27 = hero_str_byte(t22, t26);
#line 29 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t27);
#line 29 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 30 "tests/golden/run/crlf-literal.hero"
    t28 = h1_r;
#line 30 "tests/golden/run/crlf-literal.hero"
    t29 = h1_r;
#line 30 "tests/golden/run/crlf-literal.hero"
    t30 = hero_str_len(t29);
#line 30 "tests/golden/run/crlf-literal.hero"
    t31 = INT64_C(2);
#line 30 "tests/golden/run/crlf-literal.hero"
    if (__builtin_sub_overflow(t30, t31, &t32)) hero_panic_overflow();
#line 30 "tests/golden/run/crlf-literal.hero"
    t33 = hero_str_byte(t28, t32);
#line 30 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t33);
#line 30 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 31 "tests/golden/run/crlf-literal.hero"
    t34 = h1_r;
#line 31 "tests/golden/run/crlf-literal.hero"
    t35 = h1_r;
#line 31 "tests/golden/run/crlf-literal.hero"
    t36 = hero_str_len(t35);
#line 31 "tests/golden/run/crlf-literal.hero"
    t37 = INT64_C(1);
#line 31 "tests/golden/run/crlf-literal.hero"
    if (__builtin_sub_overflow(t36, t37, &t38)) hero_panic_overflow();
#line 31 "tests/golden/run/crlf-literal.hero"
    t39 = hero_str_byte(t34, t38);
#line 31 "tests/golden/run/crlf-literal.hero"
    hero_print_int(t39);
#line 31 "tests/golden/run/crlf-literal.hero"
    hero_print_end();
#line 490 "crlfliteral.c"
    hero_str_decref(h0_e);
#line 31 "tests/golden/run/crlf-literal.hero"
#line 493 "crlfliteral.c"
    hero_str_decref(h1_r);
#line 31 "tests/golden/run/crlf-literal.hero"
#line 496 "crlfliteral.c"
    hero_str_decref(h2_own2);
#line 31 "tests/golden/run/crlf-literal.hero"
#line 499 "crlfliteral.c"
    hero_str_decref(h3_own3);
    return;
}
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_crlfliteral_main();
    hero_runtime_check_leaks();
    return 0;
}
