/* Generated by heroes 0.2.0 from tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero. Do not edit. */
#include "heroes_unit.h"
#include <heroes_unit.h>
#include <hero_os.h>
#include <heroes_runtime.h>
#include "heroes_standard.h"

_Static_assert(HERO_RUNTIME_ABI == 30, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 8 : sizeof(c) <= 8))
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && (_Generic((c), _Bool:1, default:0) || (!HERO_C_UNSIGNED(c) && sizeof(c) == 1)))
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 2 : sizeof(c) <= 2))
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 4 : sizeof(c) <= 4))
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:(__LDBL_MANT_DIG__ <= __DBL_MANT_DIG__ && __LDBL_MAX_EXP__ <= __DBL_MAX_EXP__ && __LDBL_MIN_EXP__ >= __DBL_MIN_EXP__), default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_INT(HERO_OS_BAD_NAME), "heroes-ffi-return HERO_OS_BAD_NAME i64");
_Static_assert(__builtin_constant_p(HERO_OS_BAD_NAME), "heroes-ffi-const HERO_OS_BAD_NAME");
_Static_assert(HERO_RET_STR(hero_file_read_str((HeroStr){0}, 0)), "heroes-ffi-return hero_file_read_str str");
_Static_assert(HERO_RET_INT(hero_file_write_str((HeroStr){0}, (HeroStr){0})), "heroes-ffi-return hero_file_write_str i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 48 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read_str(HeroStr a0, int64_t * a1) { (void)(hero_file_read_str)(a0, (void *)a1); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write_str(HeroStr a0, HeroStr a1) { (void)(hero_file_write_str)(a0, a1); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 124 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 78 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

HeroStr h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_shown(uint8_t h0_v);
void h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_main(void);
HERO_TU_LOCAL uint8_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_3c17(uint8_t h0_a);
HERO_TU_LOCAL uint8_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_3c17(uint8_t h0_a, uint8_t h1_b);
HERO_TU_LOCAL int8_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_35f3(int8_t h0_a);
HERO_TU_LOCAL int64_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_1b9a87(int64_t h0_a, int64_t h1_b);
HERO_TU_LOCAL HeroArrayHeader * h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_4b7fe249(HeroArrayHeader * h0_a, HeroArrayHeader * h1_b);

#line 24 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
HeroStr h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_shown(uint8_t h0_v) {
#line 24 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    HeroStr h1_own1 = {0}; uint8_t t1; HeroStr t2; HeroStr t3; goto bb0;
#line 24 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = h0_v;
#line 25 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t2 = hero_int_to_str(t1);
#line 25 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t3 = h1_own1;
#line 25 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h1_own1 = t2;
#line 25 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_str_decref(t3);
#line 113 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
    hero_str_incref(t2);
    hero_str_release_at(&h1_own1);
    return t2;
}

#line 27 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
void h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_main(void) {
#line 27 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    uint8_t h0_b8; uint8_t h1_y; uint8_t h2_w; int8_t h3_n; uint8_t h4_g; uint8_t h5_h; HeroStr h6_own6 = {0}; HeroArrayHeader * h7_own7 = {0}; HeroArrayHeader * h8_own8 = {0}; HeroArrayHeader * h9_own9 = {0}; HeroArrayHeader * h10_own10 = {0}; HeroArrayHeader * h11_own11 = {0}; HeroArrayHeader * h12_own12 = {0}; uint8_t t1; uint8_t t2; uint8_t t3; uint8_t t4; uint8_t t5; uint8_t t6; uint8_t t7; uint8_t t8; uint8_t t9; uint8_t t10; uint8_t t11; uint8_t t12; int8_t t13; int8_t t14; int8_t t15; int8_t t16; int8_t t17; int8_t t18; uint8_t t19; uint8_t t20; uint8_t t21; uint8_t t22; uint8_t t23; uint8_t t24; uint8_t t25; uint8_t t26; uint8_t t27; uint8_t t28; uint8_t t29; uint8_t t30; uint8_t t31; uint8_t t32; uint8_t t33; uint8_t t34; HeroStr t35; uint8_t t36; uint8_t t37; uint8_t t38; uint8_t t39; uint8_t t40; uint8_t t41; uint8_t t42; uint8_t t43; uint8_t t44; uint8_t t45; int64_t t46; int64_t t47; int64_t t48; int64_t t49; int64_t t50; int64_t t51; int64_t t52; int64_t t53; int64_t t54; int64_t t55; int64_t t56; int64_t t57; int64_t t58; HeroArrayHeader * t59; HeroArrayHeader * t60; HeroArrayHeader * t61; int64_t t62; HeroArrayHeader * t63; int64_t t64; int64_t t65; int64_t t66; HeroArrayHeader * t67; HeroArrayHeader * t68; int64_t t69; HeroStr t70; HeroArrayHeader * t71; HeroArrayHeader * t72; HeroArrayHeader * t73; HeroArrayHeader * t74; HeroArrayHeader * t75; HeroArrayHeader * t76; goto bb0;
#line 27 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = UINT64_C(1);
#line 28 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h0_b8 = t1;
    t2 = UINT64_C(2);
#line 29 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t3 = UINT64_C(3);
#line 29 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t2, t3, &t4)) hero_panic_overflow();
#line 29 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t5 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_3c17(t4);
#line 29 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h1_y = t5;
    t6 = h1_y;
#line 30 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t6);
#line 30 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t7 = UINT64_C(2);
#line 31 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t8 = UINT64_C(3);
#line 31 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t7, t8, &t9)) hero_panic_overflow();
#line 31 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t10 = UINT64_C(1);
#line 31 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t11 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_3c17(t9, t10);
#line 31 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h2_w = t11;
    t12 = h2_w;
#line 32 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t12);
#line 32 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t13 = INT64_C(2);
#line 33 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t14 = INT64_C(3);
#line 33 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t13, t14, &t15)) hero_panic_overflow();
#line 33 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_sub_overflow(INT64_C(0), t15, &t16)) hero_panic_overflow();
#line 33 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t17 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_35f3(t16);
#line 33 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h3_n = t17;
    t18 = h3_n;
#line 34 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t18);
#line 34 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t19 = UINT64_C(2);
#line 35 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t20 = UINT64_C(3);
#line 35 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t19, t20, &t21)) hero_panic_overflow();
#line 35 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t22 = UINT64_C(4);
#line 35 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_mul_overflow(t21, t22, &t23)) hero_panic_overflow();
#line 35 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t24 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_3c17(t23);
#line 35 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h4_g = t24;
    t25 = h4_g;
#line 36 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t25);
#line 36 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t26 = UINT64_C(2);
#line 37 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t27 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_3c17(t26);
#line 37 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t28 = UINT64_C(3);
#line 37 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t27, t28, &t29)) hero_panic_overflow();
#line 37 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t30 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_3c17(t29);
#line 37 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h5_h = t30;
    t31 = h5_h;
#line 38 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t31);
#line 38 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t32 = UINT64_C(2);
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t33 = UINT64_C(3);
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t32, t33, &t34)) hero_panic_overflow();
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t35 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_shown(t34);
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t70 = h6_own6;
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h6_own6 = t35;
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_str_decref(t70);
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_str(t35);
#line 39 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t36 = UINT64_C(2);
#line 40 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t37 = UINT64_C(3);
#line 40 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t36, t37, &t38)) hero_panic_overflow();
#line 40 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t39 = h0_b8;
#line 40 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t40 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_3c17(t38, t39);
#line 40 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t40);
#line 40 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t41 = h0_b8;
#line 41 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t42 = UINT64_C(2);
#line 41 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t43 = UINT64_C(3);
#line 41 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t42, t43, &t44)) hero_panic_overflow();
#line 41 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t45 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_3c17(t41, t44);
#line 41 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t45);
#line 41 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t46 = INT64_C(2);
#line 42 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t47 = INT64_C(3);
#line 42 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t46, t47, &t48)) hero_panic_overflow();
#line 42 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t49 = INT64_C(1);
#line 42 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t50 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_1b9a87(t48, t49);
#line 42 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t50);
#line 42 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t51 = INT64_C(1);
#line 43 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t52 = INT64_C(2);
#line 43 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t53 = INT64_C(3);
#line 43 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t52, t53, &t54)) hero_panic_overflow();
#line 43 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t55 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_1b9a87(t51, t54);
#line 43 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t55);
#line 43 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t56 = INT64_C(2);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t57 = INT64_C(3);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t56, t57, &t58)) hero_panic_overflow();
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t59 = hero_array_new(&hero_desc_int, 1);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t59, &t58);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t71 = h7_own7;
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h7_own7 = t59;
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t71);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t60 = hero_array_new(&hero_desc_int, 1);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t72 = h8_own8;
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h8_own8 = t60;
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t72);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t61 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_4b7fe249(t59, t60);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t73 = h9_own9;
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h9_own9 = t61;
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t73);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t62 = ((void)(t61 == NULL ? ((void)hero_array_len(t61), hero_unreachable()) : (void)0), t61->len);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t62);
#line 44 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
    t63 = hero_array_new(&hero_desc_int, 1);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t74 = h10_own10;
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h10_own10 = t63;
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t74);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t64 = INT64_C(2);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t65 = INT64_C(3);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    if (__builtin_add_overflow(t64, t65, &t66)) hero_panic_overflow();
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t67 = hero_array_new(&hero_desc_int, 1);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t67, &t66);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t75 = h11_own11;
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h11_own11 = t67;
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t75);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t68 = h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_4b7fe249(t63, t67);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t76 = h12_own12;
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h12_own12 = t68;
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t76);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t69 = ((void)(t68 == NULL ? ((void)hero_array_len(t68), hero_unreachable()) : (void)0), t68->len);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_int(t69);
#line 45 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_print_end();
#line 351 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
    hero_str_release_at(&h6_own6);
    hero_array_release_at(&h7_own7);
    hero_array_release_at(&h8_own8);
    hero_array_release_at(&h9_own9);
    hero_array_release_at(&h10_own10);
    hero_array_release_at(&h11_own11);
    hero_array_release_at(&h12_own12);
    return;
}

#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
/* id<u8> */
#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
HERO_TU_LOCAL uint8_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_3c17(uint8_t h0_a) {
#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    uint8_t t1; goto bb0;
#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = h0_a;
#line 18 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    return t1;
#line 373 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
}

#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
/* first<u8> */
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
HERO_TU_LOCAL uint8_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_3c17(uint8_t h0_a, uint8_t h1_b) {
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    HeroArrayHeader * h2_pair = {0}; HeroArrayHeader * h3_own3 = {0}; uint8_t t1; uint8_t t2; HeroArrayHeader * t3; HeroArrayHeader * t4; int64_t t5; uint8_t t6; HeroArrayHeader * t7; HeroArrayHeader * t8; goto bb0;
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = h0_a;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t2 = h1_b;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t3 = hero_array_new(&hero_desc_u8, 2);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t3, &t1);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t3, &t2);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t7 = h3_own3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h3_own3 = t3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t7);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t8 = h2_pair;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_incref(t3);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h2_pair = t3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t8);
    t4 = h2_pair;
#line 22 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t5 = INT64_C(0);
#line 22 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t6 = ((void)((t4 == NULL || t5 < 0 || t5 >= t4->len) ? ((void)hero_array_at(t4, t5), hero_unreachable()) : (void)0), (void)(t4->elem->size != sizeof(uint8_t) ? hero_unreachable() : (void)0), ((uint8_t const *)(const void *)(t4 + 1))[t5]);
#line 412 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
    hero_array_release_at(&h2_pair);
    hero_array_release_at(&h3_own3);
    return t6;
}

#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
/* id<i8> */
#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
HERO_TU_LOCAL int8_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_id_35f3(int8_t h0_a) {
#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    int8_t t1; goto bb0;
#line 17 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = h0_a;
#line 18 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    return t1;
#line 429 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
}

#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
/* first<i64> */
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
HERO_TU_LOCAL int64_t h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_1b9a87(int64_t h0_a, int64_t h1_b) {
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    HeroArrayHeader * h2_pair = {0}; HeroArrayHeader * h3_own3 = {0}; int64_t t1; int64_t t2; HeroArrayHeader * t3; HeroArrayHeader * t4; int64_t t5; int64_t t6; HeroArrayHeader * t7; HeroArrayHeader * t8; goto bb0;
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = h0_a;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t2 = h1_b;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t3 = hero_array_new(&hero_desc_int, 2);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t3, &t1);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t3, &t2);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t7 = h3_own3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h3_own3 = t3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t7);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t8 = h2_pair;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_incref(t3);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h2_pair = t3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t8);
    t4 = h2_pair;
#line 22 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t5 = INT64_C(0);
#line 22 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t6 = ((void)((t4 == NULL || t5 < 0 || t5 >= t4->len) ? ((void)hero_array_at(t4, t5), hero_unreachable()) : (void)0), (void)(t4->elem->size != sizeof(int64_t) ? hero_unreachable() : (void)0), ((int64_t const *)(const void *)(t4 + 1))[t5]);
#line 468 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
    hero_array_release_at(&h2_pair);
    hero_array_release_at(&h3_own3);
    return t6;
}

#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
/* first<[i64]> */
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
HERO_TU_LOCAL HeroArrayHeader * h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_first_4b7fe249(HeroArrayHeader * h0_a, HeroArrayHeader * h1_b) {
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    HeroArrayHeader * h2_pair = {0}; HeroArrayHeader * h3_own3 = {0}; HeroArrayHeader * t1; HeroArrayHeader * t2; HeroArrayHeader * t3; HeroArrayHeader * t4; int64_t t5; HeroArrayHeader * t6; HeroArrayHeader * t7; HeroArrayHeader * t8; goto bb0;
#line 20 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
bb0:
    t1 = h0_a;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t2 = h1_b;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t3 = hero_array_new(&hero_desc_array, 2);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t3, &t1);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_push_owned(&t3, &t2);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t7 = h3_own3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h3_own3 = t3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t7);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t8 = h2_pair;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_incref(t3);
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    h2_pair = t3;
#line 21 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    hero_array_decref(t8);
    t4 = h2_pair;
#line 22 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t5 = INT64_C(0);
#line 22 "tests/golden/run/fixedbugs-578-an-operator-over-literals-at-a-generic-parameter-takes-its-type.hero"
    t6 = ((void)((t4 == NULL || t5 < 0 || t5 >= t4->len) ? ((void)hero_array_at(t4, t5), hero_unreachable()) : (void)0), (void)(t4->elem->size != sizeof(HeroArrayHeader *) ? hero_unreachable() : (void)0), ((HeroArrayHeader * const *)(const void *)(t4 + 1))[t5]);
#line 510 "fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype.c"
    hero_array_incref(t6);
    hero_array_release_at(&h2_pair);
    hero_array_release_at(&h3_own3);
    return t6;
}
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_fixedbugs578anoperatoroverliteralsatagenericparametertakesitstype_main();
    hero_runtime_check_leaks();
    return 0;
}
