/* Generated by heroes 0.2.0 from tests/golden/run/maps.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 21, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

HERO_STR_STATIC(hero_str_61, "a");
HERO_STR_STATIC(hero_str_62, "b");
HERO_STR_STATIC(hero_str_63, "c");
HERO_STR_STATIC(hero_str_7a, "z");
HERO_STR_STATIC(hero_str_6b, "k");
HERO_STR_STATIC(hero_str_1d4996, "one");
HERO_STR_STATIC(hero_str_21, "!");
HERO_STR_STATIC(hero_str_1e9d68, "two");
HERO_STR_STATIC(hero_str_edaa230, "none");
HERO_STR_STATIC(hero_str_6da4f223, "origin");
HERO_STR_STATIC(hero_str_fca7be4, "unit");
HERO_STR_STATIC(hero_str_78, "x");
HERO_STR_STATIC(hero_str_79, "y");

#line 59 "maps.c"
typedef struct h_maps_Point {
    int64_t f_x;
    int64_t f_y;
} h_maps_Point;

typedef struct h_0opt_e201354 {
    int64_t tag;
    union {
        int64_t ok;
        HeroFailure err;
    } as;
} h_0opt_e201354;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_23a6fed9 {
    int64_t tag;
    union {
        h_maps_Point ok;
        HeroFailure err;
    } as;
} h_0opt_23a6fed9;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 117 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 123 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 113 "maps.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL bool h_maps_Point_eq(const h_maps_Point *a, const h_maps_Point *b);
HERO_TU_LOCAL uint64_t h_maps_Point_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v);
HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v);
HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b);
HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_23a6fed9_retain(const h_0opt_23a6fed9 *v);
HERO_TU_LOCAL void h_0opt_23a6fed9_release(h_0opt_23a6fed9 *v);
HERO_TU_LOCAL bool h_0opt_23a6fed9_eq(const h_0opt_23a6fed9 *a, const h_0opt_23a6fed9 *b);
HERO_TU_LOCAL uint64_t h_0opt_23a6fed9_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

static void h_maps_Point_desc_copy(void *dst, const void *src) {
    *(h_maps_Point *)dst = *(const h_maps_Point *)src;
}
static void h_maps_Point_desc_drop(void *elem) {
    (void)elem;
}
static bool h_maps_Point_desc_eq(const void *a, const void *b) {
    return h_maps_Point_eq((const h_maps_Point *)a, (const h_maps_Point *)b);
}
HERO_TU_QUIET static const HeroDesc h_maps_Point_desc = {
    sizeof(h_maps_Point),
    h_maps_Point_desc_copy,
    h_maps_Point_desc_drop,
    h_maps_Point_desc_eq,
    h_maps_Point_hash,
};

void h_maps_main(void);

#line 34 "tests/golden/run/maps.hero"
void h_maps_main(void) {
#line 156 "maps.c"
    HeroMapHeader * h0_m = {0};
    h_0opt_e201354 h1_f0 = {0};
    h_0opt_e201354 h2_f1 = {0};
    h_0opt_e201354 h3_f2 = {0};
    int64_t h4_r0;
    h_0opt_e201354 h5_f3 = {0};
    int64_t h6_r1;
    h_0opt_e201354 h7_f4 = {0};
    HeroMapHeader * h8_d = {0};
    h_0opt_e201354 h9_f5 = {0};
    int64_t h10_r2;
    HeroMapHeader * h11_ns = {0};
    h_0opt_f87774a h12_f6 = {0};
    HeroStr h13_r3 = {0};
    h_0opt_f87774a h14_f7 = {0};
    HeroStr h15_r4 = {0};
    HeroMapHeader * h16_ps = {0};
    h_0opt_23a6fed9 h17_got = {0};
    h_0opt_23a6fed9 h18_f8 = {0};
    h_maps_Point h19_r5;
    HeroMapHeader * h20_e = {0};
    h_0opt_e201354 h21_f9 = {0};
    HeroMapHeader * h22_w = {0};
    h_0opt_e201354 h23_f10 = {0};
    int64_t h24_r6;
    h_0opt_e201354 h25_f11 = {0};
    int64_t h26_r7;
    HeroMapHeader * h27_big = {0};
    int64_t h28_i;
    int64_t h29_total;
    HeroArrayHeader * h30_xs0 = {0};
    int64_t h31_i0;
    HeroStr h32_k = {0};
    h_0opt_e201354 h33_f12 = {0};
    int64_t h34_r8;
    HeroMapHeader * h35_own35 = {0};
    h_0opt_e201354 h36_own36 = {0};
    h_0opt_e201354 h37_own37 = {0};
    h_0opt_e201354 h38_own38 = {0};
    h_0opt_e201354 h39_own39 = {0};
    h_0opt_e201354 h40_own40 = {0};
    HeroMapHeader * h41_own41 = {0};
    HeroMapHeader * h42_own42 = {0};
    HeroMapHeader * h43_own43 = {0};
    HeroMapHeader * h44_own44 = {0};
    h_0opt_e201354 h45_own45 = {0};
    HeroStr h46_own46 = {0};
    HeroStr h47_own47 = {0};
    HeroMapHeader * h48_own48 = {0};
    h_0opt_f87774a h49_own49 = {0};
    h_0opt_f87774a h50_own50 = {0};
    HeroMapHeader * h51_own51 = {0};
    h_0opt_23a6fed9 h52_own52 = {0};
    HeroMapHeader * h53_own53 = {0};
    HeroMapHeader * h54_own54 = {0};
    h_0opt_e201354 h55_own55 = {0};
    HeroMapHeader * h56_own56 = {0};
    HeroMapHeader * h57_own57 = {0};
    h_0opt_e201354 h58_own58 = {0};
    h_0opt_e201354 h59_own59 = {0};
    HeroMapHeader * h60_own60 = {0};
    HeroStr h61_own61 = {0};
    HeroStr h62_own62 = {0};
    HeroArrayHeader * h63_own63 = {0};
    h_0opt_e201354 h64_own64 = {0};
    HeroArrayHeader * h65_own65 = {0};
    HeroStr t1 = {0};
    int64_t t2;
    HeroStr t3 = {0};
    int64_t t4;
    HeroStr t5 = {0};
    int64_t t6;
    HeroMapHeader * t7 = {0};
    HeroMapHeader * t8 = {0};
    int64_t t9;
    HeroMapHeader * t10 = {0};
    HeroStr t11 = {0};
    h_0opt_e201354 t12 = {0};
    h_0opt_e201354 t13 = {0};
    int64_t t14;
    int64_t t15;
    bool t16;
    bool t17;
    HeroMapHeader * t18 = {0};
    HeroStr t19 = {0};
    h_0opt_e201354 t20 = {0};
    h_0opt_e201354 t21 = {0};
    int64_t t22;
    int64_t t23;
    bool t24;
    bool t25;
    HeroMapHeader * t26 = {0};
    HeroStr t27 = {0};
    h_0opt_e201354 t28 = {0};
    h_0opt_e201354 t29 = {0};
    int64_t t30;
    int64_t t31;
    bool t32;
    h_0opt_e201354 t33 = {0};
    int64_t t34;
    int64_t t35;
    int64_t t36;
    HeroMapHeader * t37 = {0};
    HeroStr t38 = {0};
    h_0opt_e201354 t39 = {0};
    h_0opt_e201354 t40 = {0};
    int64_t t41;
    int64_t t42;
    bool t43;
    h_0opt_e201354 t44 = {0};
    int64_t t45;
    int64_t t46;
    int64_t t47;
    HeroMapHeader * t48 = {0};
    HeroStr t49 = {0};
    h_0opt_e201354 t50 = {0};
    h_0opt_e201354 t51 = {0};
    int64_t t52;
    int64_t t53;
    bool t54;
    HeroMapHeader * t55 = {0};
    HeroStr t56 = {0};
    int64_t t57;
    HeroStr t58 = {0};
    int64_t t59;
    HeroStr t60 = {0};
    int64_t t61;
    HeroMapHeader * t62 = {0};
    bool t63;
    HeroMapHeader * t64 = {0};
    HeroStr t65 = {0};
    int64_t t66;
    HeroStr t67 = {0};
    int64_t t68;
    HeroMapHeader * t69 = {0};
    bool t70;
    HeroMapHeader * t71 = {0};
    HeroStr t72 = {0};
    int64_t t73;
    HeroStr t74 = {0};
    int64_t t75;
    HeroStr t76 = {0};
    int64_t t77;
    HeroMapHeader * t78 = {0};
    bool t79;
    HeroStr t80 = {0};
    int64_t t81;
    HeroStr t82 = {0};
    int64_t t83;
    HeroMapHeader * t84 = {0};
    HeroMapHeader * t85 = {0};
    int64_t t86;
    HeroMapHeader * t87 = {0};
    HeroStr t88 = {0};
    h_0opt_e201354 t89 = {0};
    h_0opt_e201354 t90 = {0};
    int64_t t91;
    int64_t t92;
    bool t93;
    h_0opt_e201354 t94 = {0};
    int64_t t95;
    int64_t t96;
    int64_t t97;
    int64_t t98;
    HeroStr t99 = {0};
    HeroStr t100 = {0};
    HeroStr t101 = {0};
    int64_t t102;
    HeroStr t103 = {0};
    HeroStr t104 = {0};
    HeroStr t105 = {0};
    HeroMapHeader * t106 = {0};
    HeroMapHeader * t107 = {0};
    int64_t t108;
    h_0opt_f87774a t109 = {0};
    h_0opt_f87774a t110 = {0};
    int64_t t111;
    int64_t t112;
    bool t113;
    h_0opt_f87774a t114 = {0};
    HeroStr t115 = {0};
    HeroStr t116 = {0};
    HeroStr t117 = {0};
    HeroMapHeader * t118 = {0};
    int64_t t119;
    h_0opt_f87774a t120 = {0};
    h_0opt_f87774a t121 = {0};
    int64_t t122;
    int64_t t123;
    bool t124;
    h_0opt_f87774a t125 = {0};
    HeroStr t126 = {0};
    HeroStr t127 = {0};
    HeroStr t128 = {0};
    HeroStr t129 = {0};
    int64_t t130;
    int64_t t131;
    h_maps_Point t132;
    HeroStr t133 = {0};
    int64_t t134;
    int64_t t135;
    h_maps_Point t136;
    HeroMapHeader * t137 = {0};
    HeroMapHeader * t138 = {0};
    HeroStr t139 = {0};
    h_0opt_23a6fed9 t140 = {0};
    h_0opt_23a6fed9 t141 = {0};
    h_0opt_23a6fed9 t142 = {0};
    int64_t t143;
    int64_t t144;
    bool t145;
    h_0opt_23a6fed9 t146 = {0};
    h_maps_Point t147;
    int64_t t148;
    int64_t t149;
    h_maps_Point t150;
    h_maps_Point t151;
    int64_t t152;
    HeroMapHeader * t153 = {0};
    HeroStr t154 = {0};
    int64_t t155;
    int64_t t156;
    h_maps_Point t157;
    HeroStr t158 = {0};
    int64_t t159;
    int64_t t160;
    h_maps_Point t161;
    HeroMapHeader * t162 = {0};
    bool t163;
    HeroMapHeader * t164 = {0};
    HeroMapHeader * t165 = {0};
    int64_t t166;
    HeroMapHeader * t167 = {0};
    HeroStr t168 = {0};
    h_0opt_e201354 t169 = {0};
    h_0opt_e201354 t170 = {0};
    int64_t t171;
    int64_t t172;
    bool t173;
    HeroMapHeader * t174 = {0};
    HeroMapHeader * t175 = {0};
    bool t176;
    HeroMapHeader * t177 = {0};
    HeroStr t178 = {0};
    int64_t t179;
    HeroStr t180 = {0};
    int64_t t181;
    HeroStr t182 = {0};
    int64_t t183;
    HeroMapHeader * t184 = {0};
    int64_t t185;
    HeroMapHeader * t186 = {0};
    HeroStr t187 = {0};
    h_0opt_e201354 t188 = {0};
    h_0opt_e201354 t189 = {0};
    int64_t t190;
    int64_t t191;
    bool t192;
    h_0opt_e201354 t193 = {0};
    int64_t t194;
    int64_t t195;
    int64_t t196;
    HeroMapHeader * t197 = {0};
    HeroStr t198 = {0};
    h_0opt_e201354 t199 = {0};
    h_0opt_e201354 t200 = {0};
    int64_t t201;
    int64_t t202;
    bool t203;
    h_0opt_e201354 t204 = {0};
    int64_t t205;
    int64_t t206;
    int64_t t207;
    HeroMapHeader * t208 = {0};
    int64_t t209;
    int64_t t210;
    int64_t t211;
    bool t212;
    HeroStr t213 = {0};
    int64_t t214;
    HeroStr t215 = {0};
    HeroStr t216 = {0};
    int64_t t217;
    int64_t t218;
    int64_t t219;
    int64_t t220;
    int64_t t221;
    HeroMapHeader * t222 = {0};
    HeroArrayHeader * t223 = {0};
    int64_t t224;
    int64_t t225;
    HeroArrayHeader * t226 = {0};
    int64_t t227;
    bool t228;
    HeroArrayHeader * t229 = {0};
    int64_t t230;
    HeroStr t231 = {0};
    int64_t t232;
    HeroMapHeader * t233 = {0};
    HeroStr t234 = {0};
    h_0opt_e201354 t235 = {0};
    h_0opt_e201354 t236 = {0};
    int64_t t237;
    int64_t t238;
    bool t239;
    h_0opt_e201354 t240 = {0};
    int64_t t241;
    int64_t t242;
    int64_t t243;
    int64_t t244;
    int64_t t245;
    int64_t t246;
    int64_t t247;
    HeroMapHeader * t248 = {0};
    int64_t t249;
    HeroMapHeader * t250 = {0};
    HeroArrayHeader * t251 = {0};
    int64_t t252;
    int64_t t253;
    HeroMapHeader * t254 = {0};
    HeroMapHeader * t255 = {0};
    h_0opt_e201354 t256 = {0};
    h_0opt_e201354 t257 = {0};
    h_0opt_e201354 t258 = {0};
    h_0opt_e201354 t259 = {0};
    h_0opt_e201354 t260 = {0};
    h_0opt_e201354 t261 = {0};
    h_0opt_e201354 t262 = {0};
    h_0opt_e201354 t263 = {0};
    h_0opt_e201354 t264 = {0};
    h_0opt_e201354 t265 = {0};
    HeroMapHeader * t266 = {0};
    HeroMapHeader * t267 = {0};
    HeroMapHeader * t268 = {0};
    HeroMapHeader * t269 = {0};
    HeroMapHeader * t270 = {0};
    h_0opt_e201354 t271 = {0};
    h_0opt_e201354 t272 = {0};
    HeroStr t273 = {0};
    HeroStr t274 = {0};
    HeroMapHeader * t275 = {0};
    HeroMapHeader * t276 = {0};
    h_0opt_f87774a t277 = {0};
    h_0opt_f87774a t278 = {0};
    HeroStr t279 = {0};
    HeroStr t280 = {0};
    h_0opt_f87774a t281 = {0};
    h_0opt_f87774a t282 = {0};
    HeroStr t283 = {0};
    HeroStr t284 = {0};
    HeroMapHeader * t285 = {0};
    HeroMapHeader * t286 = {0};
    h_0opt_23a6fed9 t287 = {0};
    h_0opt_23a6fed9 t288 = {0};
    h_0opt_23a6fed9 t289 = {0};
    HeroMapHeader * t290 = {0};
    HeroMapHeader * t291 = {0};
    HeroMapHeader * t292 = {0};
    h_0opt_e201354 t293 = {0};
    h_0opt_e201354 t294 = {0};
    HeroMapHeader * t295 = {0};
    HeroMapHeader * t296 = {0};
    HeroMapHeader * t297 = {0};
    h_0opt_e201354 t298 = {0};
    h_0opt_e201354 t299 = {0};
    h_0opt_e201354 t300 = {0};
    h_0opt_e201354 t301 = {0};
    HeroMapHeader * t302 = {0};
    HeroMapHeader * t303 = {0};
    HeroStr t304 = {0};
    HeroStr t305 = {0};
    HeroArrayHeader * t306 = {0};
    HeroArrayHeader * t307 = {0};
    HeroStr t308 = {0};
    h_0opt_e201354 t309 = {0};
    h_0opt_e201354 t310 = {0};
    HeroArrayHeader * t311 = {0};
    goto bb0;
bb0:
#line 35 "tests/golden/run/maps.hero"
    t1 = HERO_STR_LIT(hero_str_61);
#line 35 "tests/golden/run/maps.hero"
    t2 = INT64_C(1);
#line 35 "tests/golden/run/maps.hero"
    t3 = HERO_STR_LIT(hero_str_62);
#line 35 "tests/golden/run/maps.hero"
    t4 = INT64_C(2);
#line 35 "tests/golden/run/maps.hero"
    t5 = HERO_STR_LIT(hero_str_63);
#line 35 "tests/golden/run/maps.hero"
    t6 = INT64_C(3);
#line 35 "tests/golden/run/maps.hero"
    t7 = hero_map_new(&hero_desc_str, &hero_desc_int, 3);
#line 35 "tests/golden/run/maps.hero"
    hero_map_put(t7, &t1, &t2);
#line 35 "tests/golden/run/maps.hero"
    hero_map_put(t7, &t3, &t4);
#line 35 "tests/golden/run/maps.hero"
    hero_map_put(t7, &t5, &t6);
#line 35 "tests/golden/run/maps.hero"
    t254 = h35_own35;
#line 35 "tests/golden/run/maps.hero"
    h35_own35 = t7;
#line 560 "maps.c"
    hero_map_decref(t254);
#line 35 "tests/golden/run/maps.hero"
    t255 = h0_m;
#line 564 "maps.c"
    hero_map_incref(t7);
#line 35 "tests/golden/run/maps.hero"
    h0_m = t7;
#line 568 "maps.c"
    hero_map_decref(t255);
#line 36 "tests/golden/run/maps.hero"
    t8 = h0_m;
#line 36 "tests/golden/run/maps.hero"
    t9 = hero_map_len(t8);
#line 36 "tests/golden/run/maps.hero"
    hero_print_int(t9);
#line 36 "tests/golden/run/maps.hero"
    hero_print_end();
#line 37 "tests/golden/run/maps.hero"
    t10 = h0_m;
#line 37 "tests/golden/run/maps.hero"
    t11 = HERO_STR_LIT(hero_str_61);
#line 37 "tests/golden/run/maps.hero"
    {
#line 37 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t10, &t11);
#line 37 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 37 "tests/golden/run/maps.hero"
        t12 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 37 "tests/golden/run/maps.hero"
      } else {
#line 37 "tests/golden/run/maps.hero"
        t12.tag = INT64_C(0);
#line 37 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t12.as.ok, found);
#line 37 "tests/golden/run/maps.hero"
      }
#line 37 "tests/golden/run/maps.hero"
    }
#line 37 "tests/golden/run/maps.hero"
    t256 = h36_own36;
#line 37 "tests/golden/run/maps.hero"
    h36_own36 = t12;
#line 604 "maps.c"
    h_0opt_e201354_release(&t256);
#line 37 "tests/golden/run/maps.hero"
    t257 = h1_f0;
#line 608 "maps.c"
    h_0opt_e201354_retain(&t12);
#line 37 "tests/golden/run/maps.hero"
    h1_f0 = t12;
#line 612 "maps.c"
    h_0opt_e201354_release(&t257);
#line 37 "tests/golden/run/maps.hero"
    t13 = h1_f0;
#line 37 "tests/golden/run/maps.hero"
    t14 = t13.tag;
#line 37 "tests/golden/run/maps.hero"
    t15 = INT64_C(1);
#line 37 "tests/golden/run/maps.hero"
    t16 = t14 == t15;
#line 37 "tests/golden/run/maps.hero"
    t17 = !t16;
#line 37 "tests/golden/run/maps.hero"
    t18 = h0_m;
#line 37 "tests/golden/run/maps.hero"
    t19 = HERO_STR_LIT(hero_str_7a);
#line 37 "tests/golden/run/maps.hero"
    {
#line 37 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t18, &t19);
#line 37 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 37 "tests/golden/run/maps.hero"
        t20 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 37 "tests/golden/run/maps.hero"
      } else {
#line 37 "tests/golden/run/maps.hero"
        t20.tag = INT64_C(0);
#line 37 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t20.as.ok, found);
#line 37 "tests/golden/run/maps.hero"
      }
#line 37 "tests/golden/run/maps.hero"
    }
#line 37 "tests/golden/run/maps.hero"
    t258 = h37_own37;
#line 37 "tests/golden/run/maps.hero"
    h37_own37 = t20;
#line 650 "maps.c"
    h_0opt_e201354_release(&t258);
#line 37 "tests/golden/run/maps.hero"
    t259 = h2_f1;
#line 654 "maps.c"
    h_0opt_e201354_retain(&t20);
#line 37 "tests/golden/run/maps.hero"
    h2_f1 = t20;
#line 658 "maps.c"
    h_0opt_e201354_release(&t259);
#line 37 "tests/golden/run/maps.hero"
    t21 = h2_f1;
#line 37 "tests/golden/run/maps.hero"
    t22 = t21.tag;
#line 37 "tests/golden/run/maps.hero"
    t23 = INT64_C(1);
#line 37 "tests/golden/run/maps.hero"
    t24 = t22 == t23;
#line 37 "tests/golden/run/maps.hero"
    t25 = !t24;
#line 37 "tests/golden/run/maps.hero"
    hero_print_bool(t17);
#line 37 "tests/golden/run/maps.hero"
    hero_print_bool(t25);
#line 37 "tests/golden/run/maps.hero"
    hero_print_end();
#line 38 "tests/golden/run/maps.hero"
    t26 = h0_m;
#line 38 "tests/golden/run/maps.hero"
    t27 = HERO_STR_LIT(hero_str_62);
#line 38 "tests/golden/run/maps.hero"
    {
#line 38 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t26, &t27);
#line 38 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 38 "tests/golden/run/maps.hero"
        t28 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 38 "tests/golden/run/maps.hero"
      } else {
#line 38 "tests/golden/run/maps.hero"
        t28.tag = INT64_C(0);
#line 38 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t28.as.ok, found);
#line 38 "tests/golden/run/maps.hero"
      }
#line 38 "tests/golden/run/maps.hero"
    }
#line 38 "tests/golden/run/maps.hero"
    t260 = h38_own38;
#line 38 "tests/golden/run/maps.hero"
    h38_own38 = t28;
#line 702 "maps.c"
    h_0opt_e201354_release(&t260);
#line 38 "tests/golden/run/maps.hero"
    t261 = h3_f2;
#line 706 "maps.c"
    h_0opt_e201354_retain(&t28);
#line 38 "tests/golden/run/maps.hero"
    h3_f2 = t28;
#line 710 "maps.c"
    h_0opt_e201354_release(&t261);
#line 38 "tests/golden/run/maps.hero"
    t29 = h3_f2;
#line 38 "tests/golden/run/maps.hero"
    t30 = t29.tag;
#line 38 "tests/golden/run/maps.hero"
    t31 = INT64_C(0);
#line 38 "tests/golden/run/maps.hero"
    t32 = t30 == t31;
#line 38 "tests/golden/run/maps.hero"
    if (t32) goto bb1; else goto bb2;
#line 38 "tests/golden/run/maps.hero"
bb1:
#line 38 "tests/golden/run/maps.hero"
    t33 = h3_f2;
#line 38 "tests/golden/run/maps.hero"
    t34 = t33.as.ok;
#line 38 "tests/golden/run/maps.hero"
    h4_r0 = t34;
#line 38 "tests/golden/run/maps.hero"
    goto bb3;
#line 38 "tests/golden/run/maps.hero"
bb2:
#line 38 "tests/golden/run/maps.hero"
    t35 = INT64_C(0);
#line 38 "tests/golden/run/maps.hero"
    h4_r0 = t35;
#line 38 "tests/golden/run/maps.hero"
    goto bb3;
#line 38 "tests/golden/run/maps.hero"
bb3:
#line 38 "tests/golden/run/maps.hero"
    t36 = h4_r0;
#line 38 "tests/golden/run/maps.hero"
    hero_print_int(t36);
#line 38 "tests/golden/run/maps.hero"
    hero_print_end();
#line 39 "tests/golden/run/maps.hero"
    t37 = h0_m;
#line 39 "tests/golden/run/maps.hero"
    t38 = HERO_STR_LIT(hero_str_7a);
#line 39 "tests/golden/run/maps.hero"
    {
#line 39 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t37, &t38);
#line 39 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 39 "tests/golden/run/maps.hero"
        t39 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 39 "tests/golden/run/maps.hero"
      } else {
#line 39 "tests/golden/run/maps.hero"
        t39.tag = INT64_C(0);
#line 39 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t39.as.ok, found);
#line 39 "tests/golden/run/maps.hero"
      }
#line 39 "tests/golden/run/maps.hero"
    }
#line 39 "tests/golden/run/maps.hero"
    t262 = h39_own39;
#line 39 "tests/golden/run/maps.hero"
    h39_own39 = t39;
#line 774 "maps.c"
    h_0opt_e201354_release(&t262);
#line 39 "tests/golden/run/maps.hero"
    t263 = h5_f3;
#line 778 "maps.c"
    h_0opt_e201354_retain(&t39);
#line 39 "tests/golden/run/maps.hero"
    h5_f3 = t39;
#line 782 "maps.c"
    h_0opt_e201354_release(&t263);
#line 39 "tests/golden/run/maps.hero"
    t40 = h5_f3;
#line 39 "tests/golden/run/maps.hero"
    t41 = t40.tag;
#line 39 "tests/golden/run/maps.hero"
    t42 = INT64_C(0);
#line 39 "tests/golden/run/maps.hero"
    t43 = t41 == t42;
#line 39 "tests/golden/run/maps.hero"
    if (t43) goto bb4; else goto bb5;
#line 39 "tests/golden/run/maps.hero"
bb4:
#line 39 "tests/golden/run/maps.hero"
    t44 = h5_f3;
#line 39 "tests/golden/run/maps.hero"
    t45 = t44.as.ok;
#line 39 "tests/golden/run/maps.hero"
    h6_r1 = t45;
#line 39 "tests/golden/run/maps.hero"
    goto bb6;
#line 39 "tests/golden/run/maps.hero"
bb5:
#line 39 "tests/golden/run/maps.hero"
    t46 = INT64_C(-1);
#line 39 "tests/golden/run/maps.hero"
    h6_r1 = t46;
#line 39 "tests/golden/run/maps.hero"
    goto bb6;
#line 39 "tests/golden/run/maps.hero"
bb6:
#line 39 "tests/golden/run/maps.hero"
    t47 = h6_r1;
#line 39 "tests/golden/run/maps.hero"
    hero_print_int(t47);
#line 39 "tests/golden/run/maps.hero"
    hero_print_end();
#line 40 "tests/golden/run/maps.hero"
    t48 = h0_m;
#line 40 "tests/golden/run/maps.hero"
    t49 = HERO_STR_LIT(hero_str_7a);
#line 40 "tests/golden/run/maps.hero"
    {
#line 40 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t48, &t49);
#line 40 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 40 "tests/golden/run/maps.hero"
        t50 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 40 "tests/golden/run/maps.hero"
      } else {
#line 40 "tests/golden/run/maps.hero"
        t50.tag = INT64_C(0);
#line 40 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t50.as.ok, found);
#line 40 "tests/golden/run/maps.hero"
      }
#line 40 "tests/golden/run/maps.hero"
    }
#line 40 "tests/golden/run/maps.hero"
    t264 = h40_own40;
#line 40 "tests/golden/run/maps.hero"
    h40_own40 = t50;
#line 846 "maps.c"
    h_0opt_e201354_release(&t264);
#line 40 "tests/golden/run/maps.hero"
    t265 = h7_f4;
#line 850 "maps.c"
    h_0opt_e201354_retain(&t50);
#line 40 "tests/golden/run/maps.hero"
    h7_f4 = t50;
#line 854 "maps.c"
    h_0opt_e201354_release(&t265);
#line 40 "tests/golden/run/maps.hero"
    t51 = h7_f4;
#line 40 "tests/golden/run/maps.hero"
    t52 = t51.tag;
#line 40 "tests/golden/run/maps.hero"
    t53 = INT64_C(1);
#line 40 "tests/golden/run/maps.hero"
    t54 = t52 == t53;
#line 40 "tests/golden/run/maps.hero"
    hero_print_bool(t54);
#line 40 "tests/golden/run/maps.hero"
    hero_print_end();
#line 43 "tests/golden/run/maps.hero"
    t55 = h0_m;
#line 43 "tests/golden/run/maps.hero"
    t56 = HERO_STR_LIT(hero_str_63);
#line 43 "tests/golden/run/maps.hero"
    t57 = INT64_C(3);
#line 43 "tests/golden/run/maps.hero"
    t58 = HERO_STR_LIT(hero_str_62);
#line 43 "tests/golden/run/maps.hero"
    t59 = INT64_C(2);
#line 43 "tests/golden/run/maps.hero"
    t60 = HERO_STR_LIT(hero_str_61);
#line 43 "tests/golden/run/maps.hero"
    t61 = INT64_C(1);
#line 43 "tests/golden/run/maps.hero"
    t62 = hero_map_new(&hero_desc_str, &hero_desc_int, 3);
#line 43 "tests/golden/run/maps.hero"
    hero_map_put(t62, &t56, &t57);
#line 43 "tests/golden/run/maps.hero"
    hero_map_put(t62, &t58, &t59);
#line 43 "tests/golden/run/maps.hero"
    hero_map_put(t62, &t60, &t61);
#line 43 "tests/golden/run/maps.hero"
    t266 = h41_own41;
#line 43 "tests/golden/run/maps.hero"
    h41_own41 = t62;
#line 894 "maps.c"
    hero_map_decref(t266);
#line 43 "tests/golden/run/maps.hero"
    t63 = hero_map_eq(t55, t62);
#line 43 "tests/golden/run/maps.hero"
    hero_print_bool(t63);
#line 43 "tests/golden/run/maps.hero"
    hero_print_end();
#line 44 "tests/golden/run/maps.hero"
    t64 = h0_m;
#line 44 "tests/golden/run/maps.hero"
    t65 = HERO_STR_LIT(hero_str_61);
#line 44 "tests/golden/run/maps.hero"
    t66 = INT64_C(1);
#line 44 "tests/golden/run/maps.hero"
    t67 = HERO_STR_LIT(hero_str_62);
#line 44 "tests/golden/run/maps.hero"
    t68 = INT64_C(2);
#line 44 "tests/golden/run/maps.hero"
    t69 = hero_map_new(&hero_desc_str, &hero_desc_int, 2);
#line 44 "tests/golden/run/maps.hero"
    hero_map_put(t69, &t65, &t66);
#line 44 "tests/golden/run/maps.hero"
    hero_map_put(t69, &t67, &t68);
#line 44 "tests/golden/run/maps.hero"
    t267 = h42_own42;
#line 44 "tests/golden/run/maps.hero"
    h42_own42 = t69;
#line 922 "maps.c"
    hero_map_decref(t267);
#line 44 "tests/golden/run/maps.hero"
    t70 = hero_map_eq(t64, t69);
#line 44 "tests/golden/run/maps.hero"
    hero_print_bool(t70);
#line 44 "tests/golden/run/maps.hero"
    hero_print_end();
#line 45 "tests/golden/run/maps.hero"
    t71 = h0_m;
#line 45 "tests/golden/run/maps.hero"
    t72 = HERO_STR_LIT(hero_str_61);
#line 45 "tests/golden/run/maps.hero"
    t73 = INT64_C(1);
#line 45 "tests/golden/run/maps.hero"
    t74 = HERO_STR_LIT(hero_str_62);
#line 45 "tests/golden/run/maps.hero"
    t75 = INT64_C(2);
#line 45 "tests/golden/run/maps.hero"
    t76 = HERO_STR_LIT(hero_str_63);
#line 45 "tests/golden/run/maps.hero"
    t77 = INT64_C(4);
#line 45 "tests/golden/run/maps.hero"
    t78 = hero_map_new(&hero_desc_str, &hero_desc_int, 3);
#line 45 "tests/golden/run/maps.hero"
    hero_map_put(t78, &t72, &t73);
#line 45 "tests/golden/run/maps.hero"
    hero_map_put(t78, &t74, &t75);
#line 45 "tests/golden/run/maps.hero"
    hero_map_put(t78, &t76, &t77);
#line 45 "tests/golden/run/maps.hero"
    t268 = h43_own43;
#line 45 "tests/golden/run/maps.hero"
    h43_own43 = t78;
#line 956 "maps.c"
    hero_map_decref(t268);
#line 45 "tests/golden/run/maps.hero"
    t79 = hero_map_eq(t71, t78);
#line 45 "tests/golden/run/maps.hero"
    hero_print_bool(t79);
#line 45 "tests/golden/run/maps.hero"
    hero_print_end();
#line 48 "tests/golden/run/maps.hero"
    t80 = HERO_STR_LIT(hero_str_6b);
#line 48 "tests/golden/run/maps.hero"
    t81 = INT64_C(1);
#line 48 "tests/golden/run/maps.hero"
    t82 = HERO_STR_LIT(hero_str_6b);
#line 48 "tests/golden/run/maps.hero"
    t83 = INT64_C(2);
#line 48 "tests/golden/run/maps.hero"
    t84 = hero_map_new(&hero_desc_str, &hero_desc_int, 2);
#line 48 "tests/golden/run/maps.hero"
    hero_map_put(t84, &t80, &t81);
#line 48 "tests/golden/run/maps.hero"
    hero_map_put(t84, &t82, &t83);
#line 48 "tests/golden/run/maps.hero"
    t269 = h44_own44;
#line 48 "tests/golden/run/maps.hero"
    h44_own44 = t84;
#line 982 "maps.c"
    hero_map_decref(t269);
#line 48 "tests/golden/run/maps.hero"
    t270 = h8_d;
#line 986 "maps.c"
    hero_map_incref(t84);
#line 48 "tests/golden/run/maps.hero"
    h8_d = t84;
#line 990 "maps.c"
    hero_map_decref(t270);
#line 49 "tests/golden/run/maps.hero"
    t85 = h8_d;
#line 49 "tests/golden/run/maps.hero"
    t86 = hero_map_len(t85);
#line 49 "tests/golden/run/maps.hero"
    t87 = h8_d;
#line 49 "tests/golden/run/maps.hero"
    t88 = HERO_STR_LIT(hero_str_6b);
#line 49 "tests/golden/run/maps.hero"
    {
#line 49 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t87, &t88);
#line 49 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 49 "tests/golden/run/maps.hero"
        t89 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 49 "tests/golden/run/maps.hero"
      } else {
#line 49 "tests/golden/run/maps.hero"
        t89.tag = INT64_C(0);
#line 49 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t89.as.ok, found);
#line 49 "tests/golden/run/maps.hero"
      }
#line 49 "tests/golden/run/maps.hero"
    }
#line 49 "tests/golden/run/maps.hero"
    t271 = h45_own45;
#line 49 "tests/golden/run/maps.hero"
    h45_own45 = t89;
#line 1022 "maps.c"
    h_0opt_e201354_release(&t271);
#line 49 "tests/golden/run/maps.hero"
    t272 = h9_f5;
#line 1026 "maps.c"
    h_0opt_e201354_retain(&t89);
#line 49 "tests/golden/run/maps.hero"
    h9_f5 = t89;
#line 1030 "maps.c"
    h_0opt_e201354_release(&t272);
#line 49 "tests/golden/run/maps.hero"
    t90 = h9_f5;
#line 49 "tests/golden/run/maps.hero"
    t91 = t90.tag;
#line 49 "tests/golden/run/maps.hero"
    t92 = INT64_C(0);
#line 49 "tests/golden/run/maps.hero"
    t93 = t91 == t92;
#line 49 "tests/golden/run/maps.hero"
    if (t93) goto bb7; else goto bb8;
#line 49 "tests/golden/run/maps.hero"
bb7:
#line 49 "tests/golden/run/maps.hero"
    t94 = h9_f5;
#line 49 "tests/golden/run/maps.hero"
    t95 = t94.as.ok;
#line 49 "tests/golden/run/maps.hero"
    h10_r2 = t95;
#line 49 "tests/golden/run/maps.hero"
    goto bb9;
#line 49 "tests/golden/run/maps.hero"
bb8:
#line 49 "tests/golden/run/maps.hero"
    t96 = INT64_C(0);
#line 49 "tests/golden/run/maps.hero"
    h10_r2 = t96;
#line 49 "tests/golden/run/maps.hero"
    goto bb9;
#line 49 "tests/golden/run/maps.hero"
bb9:
#line 49 "tests/golden/run/maps.hero"
    t97 = h10_r2;
#line 49 "tests/golden/run/maps.hero"
    hero_print_int(t86);
#line 49 "tests/golden/run/maps.hero"
    hero_print_int(t97);
#line 49 "tests/golden/run/maps.hero"
    hero_print_end();
#line 52 "tests/golden/run/maps.hero"
    t98 = INT64_C(1);
#line 52 "tests/golden/run/maps.hero"
    t99 = HERO_STR_LIT(hero_str_1d4996);
#line 52 "tests/golden/run/maps.hero"
    t100 = HERO_STR_LIT(hero_str_21);
#line 52 "tests/golden/run/maps.hero"
    t101 = hero_str_concat(t99, t100);
#line 52 "tests/golden/run/maps.hero"
    t273 = h46_own46;
#line 52 "tests/golden/run/maps.hero"
    h46_own46 = t101;
#line 1082 "maps.c"
    hero_str_decref(t273);
#line 52 "tests/golden/run/maps.hero"
    t102 = INT64_C(2);
#line 52 "tests/golden/run/maps.hero"
    t103 = HERO_STR_LIT(hero_str_1e9d68);
#line 52 "tests/golden/run/maps.hero"
    t104 = HERO_STR_LIT(hero_str_21);
#line 52 "tests/golden/run/maps.hero"
    t105 = hero_str_concat(t103, t104);
#line 52 "tests/golden/run/maps.hero"
    t274 = h47_own47;
#line 52 "tests/golden/run/maps.hero"
    h47_own47 = t105;
#line 1096 "maps.c"
    hero_str_decref(t274);
#line 52 "tests/golden/run/maps.hero"
    t106 = hero_map_new(&hero_desc_int, &hero_desc_str, 2);
#line 52 "tests/golden/run/maps.hero"
    hero_map_put(t106, &t98, &t101);
#line 52 "tests/golden/run/maps.hero"
    hero_map_put(t106, &t102, &t105);
#line 52 "tests/golden/run/maps.hero"
    t275 = h48_own48;
#line 52 "tests/golden/run/maps.hero"
    h48_own48 = t106;
#line 1108 "maps.c"
    hero_map_decref(t275);
#line 52 "tests/golden/run/maps.hero"
    t276 = h11_ns;
#line 1112 "maps.c"
    hero_map_incref(t106);
#line 52 "tests/golden/run/maps.hero"
    h11_ns = t106;
#line 1116 "maps.c"
    hero_map_decref(t276);
#line 53 "tests/golden/run/maps.hero"
    t107 = h11_ns;
#line 53 "tests/golden/run/maps.hero"
    t108 = INT64_C(1);
#line 53 "tests/golden/run/maps.hero"
    {
#line 53 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t107, &t108);
#line 53 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 53 "tests/golden/run/maps.hero"
        t109 = (h_0opt_f87774a){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 53 "tests/golden/run/maps.hero"
      } else {
#line 53 "tests/golden/run/maps.hero"
        t109.tag = INT64_C(0);
#line 53 "tests/golden/run/maps.hero"
        (&hero_desc_str)->copy(&t109.as.ok, found);
#line 53 "tests/golden/run/maps.hero"
      }
#line 53 "tests/golden/run/maps.hero"
    }
#line 53 "tests/golden/run/maps.hero"
    t277 = h49_own49;
#line 53 "tests/golden/run/maps.hero"
    h49_own49 = t109;
#line 1144 "maps.c"
    h_0opt_f87774a_release(&t277);
#line 53 "tests/golden/run/maps.hero"
    t278 = h12_f6;
#line 1148 "maps.c"
    h_0opt_f87774a_retain(&t109);
#line 53 "tests/golden/run/maps.hero"
    h12_f6 = t109;
#line 1152 "maps.c"
    h_0opt_f87774a_release(&t278);
#line 53 "tests/golden/run/maps.hero"
    t110 = h12_f6;
#line 53 "tests/golden/run/maps.hero"
    t111 = t110.tag;
#line 53 "tests/golden/run/maps.hero"
    t112 = INT64_C(0);
#line 53 "tests/golden/run/maps.hero"
    t113 = t111 == t112;
#line 53 "tests/golden/run/maps.hero"
    if (t113) goto bb10; else goto bb11;
#line 53 "tests/golden/run/maps.hero"
bb10:
#line 53 "tests/golden/run/maps.hero"
    t114 = h12_f6;
#line 53 "tests/golden/run/maps.hero"
    t115 = t114.as.ok;
#line 53 "tests/golden/run/maps.hero"
    t279 = h13_r3;
#line 1172 "maps.c"
    hero_str_incref(t115);
#line 53 "tests/golden/run/maps.hero"
    h13_r3 = t115;
#line 1176 "maps.c"
    hero_str_decref(t279);
    goto bb12;
bb11:
#line 53 "tests/golden/run/maps.hero"
    t116 = HERO_STR_LIT(hero_str_edaa230);
#line 53 "tests/golden/run/maps.hero"
    t280 = h13_r3;
#line 1184 "maps.c"
    hero_str_incref(t116);
#line 53 "tests/golden/run/maps.hero"
    h13_r3 = t116;
#line 1188 "maps.c"
    hero_str_decref(t280);
    goto bb12;
bb12:
#line 53 "tests/golden/run/maps.hero"
    t117 = h13_r3;
#line 53 "tests/golden/run/maps.hero"
    hero_print_str(t117);
#line 53 "tests/golden/run/maps.hero"
    hero_print_end();
#line 54 "tests/golden/run/maps.hero"
    t118 = h11_ns;
#line 54 "tests/golden/run/maps.hero"
    t119 = INT64_C(9);
#line 54 "tests/golden/run/maps.hero"
    {
#line 54 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t118, &t119);
#line 54 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 54 "tests/golden/run/maps.hero"
        t120 = (h_0opt_f87774a){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 54 "tests/golden/run/maps.hero"
      } else {
#line 54 "tests/golden/run/maps.hero"
        t120.tag = INT64_C(0);
#line 54 "tests/golden/run/maps.hero"
        (&hero_desc_str)->copy(&t120.as.ok, found);
#line 54 "tests/golden/run/maps.hero"
      }
#line 54 "tests/golden/run/maps.hero"
    }
#line 54 "tests/golden/run/maps.hero"
    t281 = h50_own50;
#line 54 "tests/golden/run/maps.hero"
    h50_own50 = t120;
#line 1224 "maps.c"
    h_0opt_f87774a_release(&t281);
#line 54 "tests/golden/run/maps.hero"
    t282 = h14_f7;
#line 1228 "maps.c"
    h_0opt_f87774a_retain(&t120);
#line 54 "tests/golden/run/maps.hero"
    h14_f7 = t120;
#line 1232 "maps.c"
    h_0opt_f87774a_release(&t282);
#line 54 "tests/golden/run/maps.hero"
    t121 = h14_f7;
#line 54 "tests/golden/run/maps.hero"
    t122 = t121.tag;
#line 54 "tests/golden/run/maps.hero"
    t123 = INT64_C(0);
#line 54 "tests/golden/run/maps.hero"
    t124 = t122 == t123;
#line 54 "tests/golden/run/maps.hero"
    if (t124) goto bb13; else goto bb14;
#line 54 "tests/golden/run/maps.hero"
bb13:
#line 54 "tests/golden/run/maps.hero"
    t125 = h14_f7;
#line 54 "tests/golden/run/maps.hero"
    t126 = t125.as.ok;
#line 54 "tests/golden/run/maps.hero"
    t283 = h15_r4;
#line 1252 "maps.c"
    hero_str_incref(t126);
#line 54 "tests/golden/run/maps.hero"
    h15_r4 = t126;
#line 1256 "maps.c"
    hero_str_decref(t283);
    goto bb15;
bb14:
#line 54 "tests/golden/run/maps.hero"
    t127 = HERO_STR_LIT(hero_str_edaa230);
#line 54 "tests/golden/run/maps.hero"
    t284 = h15_r4;
#line 1264 "maps.c"
    hero_str_incref(t127);
#line 54 "tests/golden/run/maps.hero"
    h15_r4 = t127;
#line 1268 "maps.c"
    hero_str_decref(t284);
    goto bb15;
bb15:
#line 54 "tests/golden/run/maps.hero"
    t128 = h15_r4;
#line 54 "tests/golden/run/maps.hero"
    hero_print_str(t128);
#line 54 "tests/golden/run/maps.hero"
    hero_print_end();
#line 57 "tests/golden/run/maps.hero"
    t129 = HERO_STR_LIT(hero_str_6da4f223);
#line 57 "tests/golden/run/maps.hero"
    t130 = INT64_C(0);
#line 57 "tests/golden/run/maps.hero"
    t131 = INT64_C(0);
#line 57 "tests/golden/run/maps.hero"
    t132 = (h_maps_Point){.f_x = t130, .f_y = t131};
#line 57 "tests/golden/run/maps.hero"
    t133 = HERO_STR_LIT(hero_str_fca7be4);
#line 57 "tests/golden/run/maps.hero"
    t134 = INT64_C(1);
#line 57 "tests/golden/run/maps.hero"
    t135 = INT64_C(1);
#line 57 "tests/golden/run/maps.hero"
    t136 = (h_maps_Point){.f_x = t134, .f_y = t135};
#line 57 "tests/golden/run/maps.hero"
    t137 = hero_map_new(&hero_desc_str, &h_maps_Point_desc, 2);
#line 57 "tests/golden/run/maps.hero"
    hero_map_put(t137, &t129, &t132);
#line 57 "tests/golden/run/maps.hero"
    hero_map_put(t137, &t133, &t136);
#line 57 "tests/golden/run/maps.hero"
    t285 = h51_own51;
#line 57 "tests/golden/run/maps.hero"
    h51_own51 = t137;
#line 1304 "maps.c"
    hero_map_decref(t285);
#line 57 "tests/golden/run/maps.hero"
    t286 = h16_ps;
#line 1308 "maps.c"
    hero_map_incref(t137);
#line 57 "tests/golden/run/maps.hero"
    h16_ps = t137;
#line 1312 "maps.c"
    hero_map_decref(t286);
#line 58 "tests/golden/run/maps.hero"
    t138 = h16_ps;
#line 58 "tests/golden/run/maps.hero"
    t139 = HERO_STR_LIT(hero_str_fca7be4);
#line 58 "tests/golden/run/maps.hero"
    {
#line 58 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t138, &t139);
#line 58 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 58 "tests/golden/run/maps.hero"
        t140 = (h_0opt_23a6fed9){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 58 "tests/golden/run/maps.hero"
      } else {
#line 58 "tests/golden/run/maps.hero"
        t140.tag = INT64_C(0);
#line 58 "tests/golden/run/maps.hero"
        (&h_maps_Point_desc)->copy(&t140.as.ok, found);
#line 58 "tests/golden/run/maps.hero"
      }
#line 58 "tests/golden/run/maps.hero"
    }
#line 58 "tests/golden/run/maps.hero"
    t287 = h52_own52;
#line 58 "tests/golden/run/maps.hero"
    h52_own52 = t140;
#line 1340 "maps.c"
    h_0opt_23a6fed9_release(&t287);
#line 58 "tests/golden/run/maps.hero"
    t288 = h17_got;
#line 1344 "maps.c"
    h_0opt_23a6fed9_retain(&t140);
#line 58 "tests/golden/run/maps.hero"
    h17_got = t140;
#line 1348 "maps.c"
    h_0opt_23a6fed9_release(&t288);
#line 59 "tests/golden/run/maps.hero"
    t141 = h17_got;
#line 59 "tests/golden/run/maps.hero"
    t289 = h18_f8;
#line 1354 "maps.c"
    h_0opt_23a6fed9_retain(&t141);
#line 59 "tests/golden/run/maps.hero"
    h18_f8 = t141;
#line 1358 "maps.c"
    h_0opt_23a6fed9_release(&t289);
#line 59 "tests/golden/run/maps.hero"
    t142 = h18_f8;
#line 59 "tests/golden/run/maps.hero"
    t143 = t142.tag;
#line 59 "tests/golden/run/maps.hero"
    t144 = INT64_C(0);
#line 59 "tests/golden/run/maps.hero"
    t145 = t143 == t144;
#line 59 "tests/golden/run/maps.hero"
    if (t145) goto bb16; else goto bb17;
#line 59 "tests/golden/run/maps.hero"
bb16:
#line 59 "tests/golden/run/maps.hero"
    t146 = h18_f8;
#line 59 "tests/golden/run/maps.hero"
    t147 = t146.as.ok;
#line 59 "tests/golden/run/maps.hero"
    h19_r5 = t147;
#line 59 "tests/golden/run/maps.hero"
    goto bb18;
#line 59 "tests/golden/run/maps.hero"
bb17:
#line 59 "tests/golden/run/maps.hero"
    t148 = INT64_C(-1);
#line 59 "tests/golden/run/maps.hero"
    t149 = INT64_C(-1);
#line 59 "tests/golden/run/maps.hero"
    t150 = (h_maps_Point){.f_x = t148, .f_y = t149};
#line 59 "tests/golden/run/maps.hero"
    h19_r5 = t150;
#line 59 "tests/golden/run/maps.hero"
    goto bb18;
#line 59 "tests/golden/run/maps.hero"
bb18:
#line 59 "tests/golden/run/maps.hero"
    t151 = h19_r5;
#line 59 "tests/golden/run/maps.hero"
    t152 = t151.f_x;
#line 59 "tests/golden/run/maps.hero"
    hero_print_int(t152);
#line 59 "tests/golden/run/maps.hero"
    hero_print_end();
#line 60 "tests/golden/run/maps.hero"
    t153 = h16_ps;
#line 60 "tests/golden/run/maps.hero"
    t154 = HERO_STR_LIT(hero_str_fca7be4);
#line 60 "tests/golden/run/maps.hero"
    t155 = INT64_C(1);
#line 60 "tests/golden/run/maps.hero"
    t156 = INT64_C(1);
#line 60 "tests/golden/run/maps.hero"
    t157 = (h_maps_Point){.f_x = t155, .f_y = t156};
#line 60 "tests/golden/run/maps.hero"
    t158 = HERO_STR_LIT(hero_str_6da4f223);
#line 60 "tests/golden/run/maps.hero"
    t159 = INT64_C(0);
#line 60 "tests/golden/run/maps.hero"
    t160 = INT64_C(0);
#line 60 "tests/golden/run/maps.hero"
    t161 = (h_maps_Point){.f_x = t159, .f_y = t160};
#line 60 "tests/golden/run/maps.hero"
    t162 = hero_map_new(&hero_desc_str, &h_maps_Point_desc, 2);
#line 60 "tests/golden/run/maps.hero"
    hero_map_put(t162, &t154, &t157);
#line 60 "tests/golden/run/maps.hero"
    hero_map_put(t162, &t158, &t161);
#line 60 "tests/golden/run/maps.hero"
    t290 = h53_own53;
#line 60 "tests/golden/run/maps.hero"
    h53_own53 = t162;
#line 1430 "maps.c"
    hero_map_decref(t290);
#line 60 "tests/golden/run/maps.hero"
    t163 = hero_map_eq(t153, t162);
#line 60 "tests/golden/run/maps.hero"
    hero_print_bool(t163);
#line 60 "tests/golden/run/maps.hero"
    hero_print_end();
#line 63 "tests/golden/run/maps.hero"
    t164 = hero_map_new(&hero_desc_str, &hero_desc_int, 0);
#line 63 "tests/golden/run/maps.hero"
    t291 = h54_own54;
#line 63 "tests/golden/run/maps.hero"
    h54_own54 = t164;
#line 1444 "maps.c"
    hero_map_decref(t291);
#line 63 "tests/golden/run/maps.hero"
    t292 = h20_e;
#line 1448 "maps.c"
    hero_map_incref(t164);
#line 63 "tests/golden/run/maps.hero"
    h20_e = t164;
#line 1452 "maps.c"
    hero_map_decref(t292);
#line 64 "tests/golden/run/maps.hero"
    t165 = h20_e;
#line 64 "tests/golden/run/maps.hero"
    t166 = hero_map_len(t165);
#line 64 "tests/golden/run/maps.hero"
    t167 = h20_e;
#line 64 "tests/golden/run/maps.hero"
    t168 = HERO_STR_LIT(hero_str_61);
#line 64 "tests/golden/run/maps.hero"
    {
#line 64 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t167, &t168);
#line 64 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 64 "tests/golden/run/maps.hero"
        t169 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 64 "tests/golden/run/maps.hero"
      } else {
#line 64 "tests/golden/run/maps.hero"
        t169.tag = INT64_C(0);
#line 64 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t169.as.ok, found);
#line 64 "tests/golden/run/maps.hero"
      }
#line 64 "tests/golden/run/maps.hero"
    }
#line 64 "tests/golden/run/maps.hero"
    t293 = h55_own55;
#line 64 "tests/golden/run/maps.hero"
    h55_own55 = t169;
#line 1484 "maps.c"
    h_0opt_e201354_release(&t293);
#line 64 "tests/golden/run/maps.hero"
    t294 = h21_f9;
#line 1488 "maps.c"
    h_0opt_e201354_retain(&t169);
#line 64 "tests/golden/run/maps.hero"
    h21_f9 = t169;
#line 1492 "maps.c"
    h_0opt_e201354_release(&t294);
#line 64 "tests/golden/run/maps.hero"
    t170 = h21_f9;
#line 64 "tests/golden/run/maps.hero"
    t171 = t170.tag;
#line 64 "tests/golden/run/maps.hero"
    t172 = INT64_C(1);
#line 64 "tests/golden/run/maps.hero"
    t173 = t171 == t172;
#line 64 "tests/golden/run/maps.hero"
    hero_print_int(t166);
#line 64 "tests/golden/run/maps.hero"
    hero_print_bool(t173);
#line 64 "tests/golden/run/maps.hero"
    hero_print_end();
#line 65 "tests/golden/run/maps.hero"
    t174 = h20_e;
#line 65 "tests/golden/run/maps.hero"
    t175 = hero_map_new(&hero_desc_str, &hero_desc_int, 0);
#line 65 "tests/golden/run/maps.hero"
    t295 = h56_own56;
#line 65 "tests/golden/run/maps.hero"
    h56_own56 = t175;
#line 1516 "maps.c"
    hero_map_decref(t295);
#line 65 "tests/golden/run/maps.hero"
    t176 = hero_map_eq(t174, t175);
#line 65 "tests/golden/run/maps.hero"
    hero_print_bool(t176);
#line 65 "tests/golden/run/maps.hero"
    hero_print_end();
#line 69 "tests/golden/run/maps.hero"
    t177 = hero_map_new(&hero_desc_str, &hero_desc_int, 0);
#line 69 "tests/golden/run/maps.hero"
    t296 = h57_own57;
#line 69 "tests/golden/run/maps.hero"
    h57_own57 = t177;
#line 1530 "maps.c"
    hero_map_decref(t296);
#line 69 "tests/golden/run/maps.hero"
    t297 = h22_w;
#line 1534 "maps.c"
    hero_map_incref(t177);
#line 69 "tests/golden/run/maps.hero"
    h22_w = t177;
#line 1538 "maps.c"
    hero_map_decref(t297);
#line 70 "tests/golden/run/maps.hero"
    t178 = HERO_STR_LIT(hero_str_78);
#line 70 "tests/golden/run/maps.hero"
    t179 = INT64_C(1);
#line 70 "tests/golden/run/maps.hero"
    hero_map_set(&(h22_w), &t178, &t179);
#line 71 "tests/golden/run/maps.hero"
    t180 = HERO_STR_LIT(hero_str_79);
#line 71 "tests/golden/run/maps.hero"
    t181 = INT64_C(2);
#line 71 "tests/golden/run/maps.hero"
    hero_map_set(&(h22_w), &t180, &t181);
#line 72 "tests/golden/run/maps.hero"
    t182 = HERO_STR_LIT(hero_str_78);
#line 72 "tests/golden/run/maps.hero"
    t183 = INT64_C(9);
#line 72 "tests/golden/run/maps.hero"
    hero_map_set(&(h22_w), &t182, &t183);
#line 73 "tests/golden/run/maps.hero"
    t184 = h22_w;
#line 73 "tests/golden/run/maps.hero"
    t185 = hero_map_len(t184);
#line 73 "tests/golden/run/maps.hero"
    t186 = h22_w;
#line 73 "tests/golden/run/maps.hero"
    t187 = HERO_STR_LIT(hero_str_78);
#line 73 "tests/golden/run/maps.hero"
    {
#line 73 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t186, &t187);
#line 73 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 73 "tests/golden/run/maps.hero"
        t188 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 73 "tests/golden/run/maps.hero"
      } else {
#line 73 "tests/golden/run/maps.hero"
        t188.tag = INT64_C(0);
#line 73 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t188.as.ok, found);
#line 73 "tests/golden/run/maps.hero"
      }
#line 73 "tests/golden/run/maps.hero"
    }
#line 73 "tests/golden/run/maps.hero"
    t298 = h58_own58;
#line 73 "tests/golden/run/maps.hero"
    h58_own58 = t188;
#line 1588 "maps.c"
    h_0opt_e201354_release(&t298);
#line 73 "tests/golden/run/maps.hero"
    t299 = h23_f10;
#line 1592 "maps.c"
    h_0opt_e201354_retain(&t188);
#line 73 "tests/golden/run/maps.hero"
    h23_f10 = t188;
#line 1596 "maps.c"
    h_0opt_e201354_release(&t299);
#line 73 "tests/golden/run/maps.hero"
    t189 = h23_f10;
#line 73 "tests/golden/run/maps.hero"
    t190 = t189.tag;
#line 73 "tests/golden/run/maps.hero"
    t191 = INT64_C(0);
#line 73 "tests/golden/run/maps.hero"
    t192 = t190 == t191;
#line 73 "tests/golden/run/maps.hero"
    if (t192) goto bb19; else goto bb20;
#line 73 "tests/golden/run/maps.hero"
bb19:
#line 73 "tests/golden/run/maps.hero"
    t193 = h23_f10;
#line 73 "tests/golden/run/maps.hero"
    t194 = t193.as.ok;
#line 73 "tests/golden/run/maps.hero"
    h24_r6 = t194;
#line 73 "tests/golden/run/maps.hero"
    goto bb21;
#line 73 "tests/golden/run/maps.hero"
bb20:
#line 73 "tests/golden/run/maps.hero"
    t195 = INT64_C(0);
#line 73 "tests/golden/run/maps.hero"
    h24_r6 = t195;
#line 73 "tests/golden/run/maps.hero"
    goto bb21;
#line 73 "tests/golden/run/maps.hero"
bb21:
#line 73 "tests/golden/run/maps.hero"
    t196 = h24_r6;
#line 73 "tests/golden/run/maps.hero"
    t197 = h22_w;
#line 73 "tests/golden/run/maps.hero"
    t198 = HERO_STR_LIT(hero_str_79);
#line 73 "tests/golden/run/maps.hero"
    {
#line 73 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t197, &t198);
#line 73 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 73 "tests/golden/run/maps.hero"
        t199 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 73 "tests/golden/run/maps.hero"
      } else {
#line 73 "tests/golden/run/maps.hero"
        t199.tag = INT64_C(0);
#line 73 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t199.as.ok, found);
#line 73 "tests/golden/run/maps.hero"
      }
#line 73 "tests/golden/run/maps.hero"
    }
#line 73 "tests/golden/run/maps.hero"
    t300 = h59_own59;
#line 73 "tests/golden/run/maps.hero"
    h59_own59 = t199;
#line 1656 "maps.c"
    h_0opt_e201354_release(&t300);
#line 73 "tests/golden/run/maps.hero"
    t301 = h25_f11;
#line 1660 "maps.c"
    h_0opt_e201354_retain(&t199);
#line 73 "tests/golden/run/maps.hero"
    h25_f11 = t199;
#line 1664 "maps.c"
    h_0opt_e201354_release(&t301);
#line 73 "tests/golden/run/maps.hero"
    t200 = h25_f11;
#line 73 "tests/golden/run/maps.hero"
    t201 = t200.tag;
#line 73 "tests/golden/run/maps.hero"
    t202 = INT64_C(0);
#line 73 "tests/golden/run/maps.hero"
    t203 = t201 == t202;
#line 73 "tests/golden/run/maps.hero"
    if (t203) goto bb22; else goto bb23;
#line 73 "tests/golden/run/maps.hero"
bb22:
#line 73 "tests/golden/run/maps.hero"
    t204 = h25_f11;
#line 73 "tests/golden/run/maps.hero"
    t205 = t204.as.ok;
#line 73 "tests/golden/run/maps.hero"
    h26_r7 = t205;
#line 73 "tests/golden/run/maps.hero"
    goto bb24;
#line 73 "tests/golden/run/maps.hero"
bb23:
#line 73 "tests/golden/run/maps.hero"
    t206 = INT64_C(0);
#line 73 "tests/golden/run/maps.hero"
    h26_r7 = t206;
#line 73 "tests/golden/run/maps.hero"
    goto bb24;
#line 73 "tests/golden/run/maps.hero"
bb24:
#line 73 "tests/golden/run/maps.hero"
    t207 = h26_r7;
#line 73 "tests/golden/run/maps.hero"
    hero_print_int(t185);
#line 73 "tests/golden/run/maps.hero"
    hero_print_int(t196);
#line 73 "tests/golden/run/maps.hero"
    hero_print_int(t207);
#line 73 "tests/golden/run/maps.hero"
    hero_print_end();
#line 77 "tests/golden/run/maps.hero"
    t208 = hero_map_new(&hero_desc_str, &hero_desc_int, 0);
#line 77 "tests/golden/run/maps.hero"
    t302 = h60_own60;
#line 77 "tests/golden/run/maps.hero"
    h60_own60 = t208;
#line 1712 "maps.c"
    hero_map_decref(t302);
#line 77 "tests/golden/run/maps.hero"
    t303 = h27_big;
#line 1716 "maps.c"
    hero_map_incref(t208);
#line 77 "tests/golden/run/maps.hero"
    h27_big = t208;
#line 1720 "maps.c"
    hero_map_decref(t303);
#line 78 "tests/golden/run/maps.hero"
    t209 = INT64_C(0);
#line 78 "tests/golden/run/maps.hero"
    h28_i = t209;
#line 78 "tests/golden/run/maps.hero"
    goto bb25;
#line 78 "tests/golden/run/maps.hero"
bb25:
#line 80 "tests/golden/run/maps.hero"
    t210 = h28_i;
#line 80 "tests/golden/run/maps.hero"
    t211 = INT64_C(40);
#line 80 "tests/golden/run/maps.hero"
    t212 = t210 < t211;
#line 80 "tests/golden/run/maps.hero"
    if (t212) goto bb26; else goto bb27;
#line 80 "tests/golden/run/maps.hero"
bb26:
#line 81 "tests/golden/run/maps.hero"
    t213 = HERO_STR_LIT(hero_str_6b);
#line 81 "tests/golden/run/maps.hero"
    t214 = h28_i;
#line 81 "tests/golden/run/maps.hero"
    t215 = hero_int_to_str(t214);
#line 81 "tests/golden/run/maps.hero"
    t304 = h61_own61;
#line 81 "tests/golden/run/maps.hero"
    h61_own61 = t215;
#line 1750 "maps.c"
    hero_str_decref(t304);
#line 81 "tests/golden/run/maps.hero"
    t216 = hero_str_concat(t213, t215);
#line 81 "tests/golden/run/maps.hero"
    t305 = h62_own62;
#line 81 "tests/golden/run/maps.hero"
    h62_own62 = t216;
#line 1758 "maps.c"
    hero_str_decref(t305);
#line 81 "tests/golden/run/maps.hero"
    t217 = h28_i;
#line 81 "tests/golden/run/maps.hero"
    hero_map_set(&(h27_big), &t216, &t217);
#line 82 "tests/golden/run/maps.hero"
    t218 = h28_i;
#line 82 "tests/golden/run/maps.hero"
    t219 = INT64_C(1);
#line 82 "tests/golden/run/maps.hero"
    if (__builtin_add_overflow(t218, t219, &t220)) hero_panic_overflow();
#line 82 "tests/golden/run/maps.hero"
    h28_i = t220;
#line 82 "tests/golden/run/maps.hero"
    goto bb25;
#line 82 "tests/golden/run/maps.hero"
bb27:
#line 84 "tests/golden/run/maps.hero"
    t221 = INT64_C(0);
#line 84 "tests/golden/run/maps.hero"
    h29_total = t221;
#line 86 "tests/golden/run/maps.hero"
    t222 = h27_big;
#line 86 "tests/golden/run/maps.hero"
    t223 = hero_map_keys(t222);
#line 86 "tests/golden/run/maps.hero"
    t306 = h63_own63;
#line 86 "tests/golden/run/maps.hero"
    h63_own63 = t223;
#line 1788 "maps.c"
    hero_array_decref(t306);
#line 86 "tests/golden/run/maps.hero"
    t307 = h30_xs0;
#line 1792 "maps.c"
    hero_array_incref(t223);
#line 86 "tests/golden/run/maps.hero"
    h30_xs0 = t223;
#line 1796 "maps.c"
    hero_array_decref(t307);
#line 86 "tests/golden/run/maps.hero"
    t224 = INT64_C(0);
#line 86 "tests/golden/run/maps.hero"
    h31_i0 = t224;
#line 86 "tests/golden/run/maps.hero"
    goto bb28;
#line 86 "tests/golden/run/maps.hero"
bb28:
#line 86 "tests/golden/run/maps.hero"
    t225 = h31_i0;
#line 86 "tests/golden/run/maps.hero"
    t226 = h30_xs0;
#line 86 "tests/golden/run/maps.hero"
    t227 = hero_array_len(t226);
#line 86 "tests/golden/run/maps.hero"
    t228 = t225 < t227;
#line 86 "tests/golden/run/maps.hero"
    if (t228) goto bb29; else goto bb31;
#line 86 "tests/golden/run/maps.hero"
bb29:
#line 86 "tests/golden/run/maps.hero"
    t229 = h30_xs0;
#line 86 "tests/golden/run/maps.hero"
    t230 = h31_i0;
#line 86 "tests/golden/run/maps.hero"
    t231 = *(HeroStr const *)hero_array_at(t229, t230);
#line 86 "tests/golden/run/maps.hero"
    t308 = h32_k;
#line 1826 "maps.c"
    hero_str_incref(t231);
#line 86 "tests/golden/run/maps.hero"
    h32_k = t231;
#line 1830 "maps.c"
    hero_str_decref(t308);
#line 87 "tests/golden/run/maps.hero"
    t232 = h29_total;
#line 87 "tests/golden/run/maps.hero"
    t233 = h27_big;
#line 87 "tests/golden/run/maps.hero"
    t234 = h32_k;
#line 87 "tests/golden/run/maps.hero"
    {
#line 87 "tests/golden/run/maps.hero"
      const void *found = hero_map_find(t233, &t234);
#line 87 "tests/golden/run/maps.hero"
      if (found == NULL) {
#line 87 "tests/golden/run/maps.hero"
        t235 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_missing_key()};
#line 87 "tests/golden/run/maps.hero"
      } else {
#line 87 "tests/golden/run/maps.hero"
        t235.tag = INT64_C(0);
#line 87 "tests/golden/run/maps.hero"
        (&hero_desc_int)->copy(&t235.as.ok, found);
#line 87 "tests/golden/run/maps.hero"
      }
#line 87 "tests/golden/run/maps.hero"
    }
#line 87 "tests/golden/run/maps.hero"
    t309 = h64_own64;
#line 87 "tests/golden/run/maps.hero"
    h64_own64 = t235;
#line 1860 "maps.c"
    h_0opt_e201354_release(&t309);
#line 87 "tests/golden/run/maps.hero"
    t310 = h33_f12;
#line 1864 "maps.c"
    h_0opt_e201354_retain(&t235);
#line 87 "tests/golden/run/maps.hero"
    h33_f12 = t235;
#line 1868 "maps.c"
    h_0opt_e201354_release(&t310);
#line 87 "tests/golden/run/maps.hero"
    t236 = h33_f12;
#line 87 "tests/golden/run/maps.hero"
    t237 = t236.tag;
#line 87 "tests/golden/run/maps.hero"
    t238 = INT64_C(0);
#line 87 "tests/golden/run/maps.hero"
    t239 = t237 == t238;
#line 87 "tests/golden/run/maps.hero"
    if (t239) goto bb32; else goto bb33;
#line 87 "tests/golden/run/maps.hero"
bb30:
#line 86 "tests/golden/run/maps.hero"
    t245 = h31_i0;
#line 86 "tests/golden/run/maps.hero"
    t246 = INT64_C(1);
#line 86 "tests/golden/run/maps.hero"
    if (__builtin_add_overflow(t245, t246, &t247)) hero_panic_overflow();
#line 86 "tests/golden/run/maps.hero"
    h31_i0 = t247;
#line 86 "tests/golden/run/maps.hero"
    goto bb28;
#line 86 "tests/golden/run/maps.hero"
bb31:
#line 89 "tests/golden/run/maps.hero"
    t248 = h27_big;
#line 89 "tests/golden/run/maps.hero"
    t249 = hero_map_len(t248);
#line 89 "tests/golden/run/maps.hero"
    t250 = h27_big;
#line 89 "tests/golden/run/maps.hero"
    t251 = hero_map_keys(t250);
#line 89 "tests/golden/run/maps.hero"
    t311 = h65_own65;
#line 89 "tests/golden/run/maps.hero"
    h65_own65 = t251;
#line 1906 "maps.c"
    hero_array_decref(t311);
#line 89 "tests/golden/run/maps.hero"
    t252 = hero_array_len(t251);
#line 89 "tests/golden/run/maps.hero"
    t253 = h29_total;
#line 89 "tests/golden/run/maps.hero"
    hero_print_int(t249);
#line 89 "tests/golden/run/maps.hero"
    hero_print_int(t252);
#line 89 "tests/golden/run/maps.hero"
    hero_print_int(t253);
#line 89 "tests/golden/run/maps.hero"
    hero_print_end();
#line 1920 "maps.c"
    hero_map_decref(h0_m);
#line 89 "tests/golden/run/maps.hero"
#line 1923 "maps.c"
    h_0opt_e201354_release(&h1_f0);
#line 89 "tests/golden/run/maps.hero"
#line 1926 "maps.c"
    h_0opt_e201354_release(&h2_f1);
#line 89 "tests/golden/run/maps.hero"
#line 1929 "maps.c"
    h_0opt_e201354_release(&h3_f2);
#line 89 "tests/golden/run/maps.hero"
#line 1932 "maps.c"
    h_0opt_e201354_release(&h5_f3);
#line 89 "tests/golden/run/maps.hero"
#line 1935 "maps.c"
    h_0opt_e201354_release(&h7_f4);
#line 89 "tests/golden/run/maps.hero"
#line 1938 "maps.c"
    hero_map_decref(h8_d);
#line 89 "tests/golden/run/maps.hero"
#line 1941 "maps.c"
    h_0opt_e201354_release(&h9_f5);
#line 89 "tests/golden/run/maps.hero"
#line 1944 "maps.c"
    hero_map_decref(h11_ns);
#line 89 "tests/golden/run/maps.hero"
#line 1947 "maps.c"
    h_0opt_f87774a_release(&h12_f6);
#line 89 "tests/golden/run/maps.hero"
#line 1950 "maps.c"
    hero_str_decref(h13_r3);
#line 89 "tests/golden/run/maps.hero"
#line 1953 "maps.c"
    h_0opt_f87774a_release(&h14_f7);
#line 89 "tests/golden/run/maps.hero"
#line 1956 "maps.c"
    hero_str_decref(h15_r4);
#line 89 "tests/golden/run/maps.hero"
#line 1959 "maps.c"
    hero_map_decref(h16_ps);
#line 89 "tests/golden/run/maps.hero"
#line 1962 "maps.c"
    h_0opt_23a6fed9_release(&h17_got);
#line 89 "tests/golden/run/maps.hero"
#line 1965 "maps.c"
    h_0opt_23a6fed9_release(&h18_f8);
#line 89 "tests/golden/run/maps.hero"
#line 1968 "maps.c"
    hero_map_decref(h20_e);
#line 89 "tests/golden/run/maps.hero"
#line 1971 "maps.c"
    h_0opt_e201354_release(&h21_f9);
#line 89 "tests/golden/run/maps.hero"
#line 1974 "maps.c"
    hero_map_decref(h22_w);
#line 89 "tests/golden/run/maps.hero"
#line 1977 "maps.c"
    h_0opt_e201354_release(&h23_f10);
#line 89 "tests/golden/run/maps.hero"
#line 1980 "maps.c"
    h_0opt_e201354_release(&h25_f11);
#line 89 "tests/golden/run/maps.hero"
#line 1983 "maps.c"
    hero_map_decref(h27_big);
#line 89 "tests/golden/run/maps.hero"
#line 1986 "maps.c"
    hero_array_decref(h30_xs0);
#line 89 "tests/golden/run/maps.hero"
#line 1989 "maps.c"
    hero_str_decref(h32_k);
#line 89 "tests/golden/run/maps.hero"
#line 1992 "maps.c"
    h_0opt_e201354_release(&h33_f12);
#line 89 "tests/golden/run/maps.hero"
#line 1995 "maps.c"
    hero_map_decref(h35_own35);
#line 89 "tests/golden/run/maps.hero"
#line 1998 "maps.c"
    h_0opt_e201354_release(&h36_own36);
#line 89 "tests/golden/run/maps.hero"
#line 2001 "maps.c"
    h_0opt_e201354_release(&h37_own37);
#line 89 "tests/golden/run/maps.hero"
#line 2004 "maps.c"
    h_0opt_e201354_release(&h38_own38);
#line 89 "tests/golden/run/maps.hero"
#line 2007 "maps.c"
    h_0opt_e201354_release(&h39_own39);
#line 89 "tests/golden/run/maps.hero"
#line 2010 "maps.c"
    h_0opt_e201354_release(&h40_own40);
#line 89 "tests/golden/run/maps.hero"
#line 2013 "maps.c"
    hero_map_decref(h41_own41);
#line 89 "tests/golden/run/maps.hero"
#line 2016 "maps.c"
    hero_map_decref(h42_own42);
#line 89 "tests/golden/run/maps.hero"
#line 2019 "maps.c"
    hero_map_decref(h43_own43);
#line 89 "tests/golden/run/maps.hero"
#line 2022 "maps.c"
    hero_map_decref(h44_own44);
#line 89 "tests/golden/run/maps.hero"
#line 2025 "maps.c"
    h_0opt_e201354_release(&h45_own45);
#line 89 "tests/golden/run/maps.hero"
#line 2028 "maps.c"
    hero_str_decref(h46_own46);
#line 89 "tests/golden/run/maps.hero"
#line 2031 "maps.c"
    hero_str_decref(h47_own47);
#line 89 "tests/golden/run/maps.hero"
#line 2034 "maps.c"
    hero_map_decref(h48_own48);
#line 89 "tests/golden/run/maps.hero"
#line 2037 "maps.c"
    h_0opt_f87774a_release(&h49_own49);
#line 89 "tests/golden/run/maps.hero"
#line 2040 "maps.c"
    h_0opt_f87774a_release(&h50_own50);
#line 89 "tests/golden/run/maps.hero"
#line 2043 "maps.c"
    hero_map_decref(h51_own51);
#line 89 "tests/golden/run/maps.hero"
#line 2046 "maps.c"
    h_0opt_23a6fed9_release(&h52_own52);
#line 89 "tests/golden/run/maps.hero"
#line 2049 "maps.c"
    hero_map_decref(h53_own53);
#line 89 "tests/golden/run/maps.hero"
#line 2052 "maps.c"
    hero_map_decref(h54_own54);
#line 89 "tests/golden/run/maps.hero"
#line 2055 "maps.c"
    h_0opt_e201354_release(&h55_own55);
#line 89 "tests/golden/run/maps.hero"
#line 2058 "maps.c"
    hero_map_decref(h56_own56);
#line 89 "tests/golden/run/maps.hero"
#line 2061 "maps.c"
    hero_map_decref(h57_own57);
#line 89 "tests/golden/run/maps.hero"
#line 2064 "maps.c"
    h_0opt_e201354_release(&h58_own58);
#line 89 "tests/golden/run/maps.hero"
#line 2067 "maps.c"
    h_0opt_e201354_release(&h59_own59);
#line 89 "tests/golden/run/maps.hero"
#line 2070 "maps.c"
    hero_map_decref(h60_own60);
#line 89 "tests/golden/run/maps.hero"
#line 2073 "maps.c"
    hero_str_decref(h61_own61);
#line 89 "tests/golden/run/maps.hero"
#line 2076 "maps.c"
    hero_str_decref(h62_own62);
#line 89 "tests/golden/run/maps.hero"
#line 2079 "maps.c"
    hero_array_decref(h63_own63);
#line 89 "tests/golden/run/maps.hero"
#line 2082 "maps.c"
    h_0opt_e201354_release(&h64_own64);
#line 89 "tests/golden/run/maps.hero"
#line 2085 "maps.c"
    hero_array_decref(h65_own65);
    return;
bb32:
#line 87 "tests/golden/run/maps.hero"
    t240 = h33_f12;
#line 87 "tests/golden/run/maps.hero"
    t241 = t240.as.ok;
#line 87 "tests/golden/run/maps.hero"
    h34_r8 = t241;
#line 87 "tests/golden/run/maps.hero"
    goto bb34;
#line 87 "tests/golden/run/maps.hero"
bb33:
#line 87 "tests/golden/run/maps.hero"
    t242 = INT64_C(0);
#line 87 "tests/golden/run/maps.hero"
    h34_r8 = t242;
#line 87 "tests/golden/run/maps.hero"
    goto bb34;
#line 87 "tests/golden/run/maps.hero"
bb34:
#line 87 "tests/golden/run/maps.hero"
    t243 = h34_r8;
#line 87 "tests/golden/run/maps.hero"
    if (__builtin_add_overflow(t232, t243, &t244)) hero_panic_overflow();
#line 87 "tests/golden/run/maps.hero"
    h29_total = t244;
#line 87 "tests/golden/run/maps.hero"
    goto bb30;
#line 2115 "maps.c"
}
HERO_TU_LOCAL bool h_maps_Point_eq(const h_maps_Point *a, const h_maps_Point *b) {
    if (!(a->f_x == b->f_x)) return false;
    if (!(a->f_y == b->f_y)) return false;
    return true;
}

HERO_TU_LOCAL uint64_t h_maps_Point_hash(const void *elem) {
    const h_maps_Point *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (&hero_desc_int)->hash(&v->f_x)) * UINT64_C(0x100000001b3);
    h = (h ^ (&hero_desc_int)->hash(&v->f_y)) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_int)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem) {
    const h_0opt_e201354 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_int)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_23a6fed9_retain(const h_0opt_23a6fed9 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_23a6fed9_release(h_0opt_23a6fed9 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_23a6fed9_eq(const h_0opt_23a6fed9 *a, const h_0opt_23a6fed9 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&h_maps_Point_desc)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_23a6fed9_hash(const void *elem) {
    const h_0opt_23a6fed9 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&h_maps_Point_desc)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_maps_main();
    hero_runtime_check_leaks();
    return 0;
}
