/* Generated by heroes 0.2.0 from tests/golden/run/builtins.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 21, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_STR(hero_file_read(0, 0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

HERO_STR_STATIC(hero_str_3ba202d1, "pearl");
HERO_STR_STATIC(hero_str_47b33001, "aladdin");
HERO_STR_STATIC(hero_str_f827bb9, "sane");
HERO_STR_STATIC(hero_str_7c, "|");
HERO_STR_STATIC(hero_str_20, " ");
HERO_STR_STATIC(hero_str_2d, "-");
HERO_STR_STATIC(hero_str_5b, "[");
HERO_STR_STATIC(hero_str_2c, ",");
HERO_STR_STATIC(hero_str_5d, "]");
HERO_STR_STATIC(hero_str_efcabd0, "only");
HERO_STR_STATIC(hero_str_78a14ef2, "caff\303\250");
HERO_STR_STATIC(hero_str_2e, ".");
HERO_STR_STATIC(hero_str_0, "");

#line 59 "builtins.c"
typedef struct h_0opt_e201354 {
    int64_t tag;
    union {
        int64_t ok;
        HeroFailure err;
    } as;
} h_0opt_e201354;

typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, (void *)a1); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 117 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 123 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 100 "builtins.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v);
HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v);
HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b);
HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

void h_builtins_main(void);

#line 19 "tests/golden/run/builtins.hero"
void h_builtins_main(void) {
#line 120 "builtins.c"
    HeroArrayHeader * h0_xs = {0};
    HeroArrayHeader * h1_sorted = {0};
    HeroArrayHeader * h2_names = {0};
    HeroArrayHeader * h3_fs = {0};
    HeroArrayHeader * h4_flags = {0};
    HeroArrayHeader * h5_ordered = {0};
    HeroArrayHeader * h6_tail = {0};
    HeroArrayHeader * h7_empty = {0};
    HeroStr h8_word = {0};
    h_0opt_e201354 h9_f0 = {0};
    h_0opt_e201354 h10_f1 = {0};
    h_0opt_e201354 h11_f2 = {0};
    HeroArrayHeader * h12_own12 = {0};
    HeroArrayHeader * h13_own13 = {0};
    HeroArrayHeader * h14_own14 = {0};
    HeroArrayHeader * h15_own15 = {0};
    HeroStr h16_own16 = {0};
    HeroArrayHeader * h17_own17 = {0};
    HeroArrayHeader * h18_own18 = {0};
    HeroArrayHeader * h19_own19 = {0};
    HeroArrayHeader * h20_own20 = {0};
    HeroArrayHeader * h21_own21 = {0};
    HeroArrayHeader * h22_own22 = {0};
    HeroStr h23_own23 = {0};
    HeroArrayHeader * h24_own24 = {0};
    HeroArrayHeader * h25_own25 = {0};
    HeroArrayHeader * h26_own26 = {0};
    HeroStr h27_own27 = {0};
    HeroArrayHeader * h28_own28 = {0};
    HeroStr h29_own29 = {0};
    HeroArrayHeader * h30_own30 = {0};
    HeroArrayHeader * h31_own31 = {0};
    HeroStr h32_own32 = {0};
    HeroArrayHeader * h33_own33 = {0};
    HeroStr h34_own34 = {0};
    HeroArrayHeader * h35_own35 = {0};
    HeroStr h36_own36 = {0};
    h_0opt_e201354 h37_own37 = {0};
    h_0opt_e201354 h38_own38 = {0};
    h_0opt_e201354 h39_own39 = {0};
    int64_t t1;
    int64_t t2;
    int64_t t3;
    HeroArrayHeader * t4 = {0};
    HeroArrayHeader * t5 = {0};
    HeroArrayHeader * t6 = {0};
    HeroArrayHeader * t7 = {0};
    int64_t t8;
    int64_t t9;
    HeroArrayHeader * t10 = {0};
    int64_t t11;
    int64_t t12;
    HeroArrayHeader * t13 = {0};
    int64_t t14;
    int64_t t15;
    HeroArrayHeader * t16 = {0};
    int64_t t17;
    int64_t t18;
    HeroArrayHeader * t19 = {0};
    int64_t t20;
    int64_t t21;
    HeroArrayHeader * t22 = {0};
    int64_t t23;
    int64_t t24;
    HeroStr t25 = {0};
    HeroStr t26 = {0};
    HeroStr t27 = {0};
    HeroStr t28 = {0};
    HeroArrayHeader * t29 = {0};
    HeroArrayHeader * t30 = {0};
    HeroArrayHeader * t31 = {0};
    HeroStr t32 = {0};
    HeroStr t33 = {0};
    double t34;
    double t35;
    double t36;
    HeroArrayHeader * t37 = {0};
    HeroArrayHeader * t38 = {0};
    HeroArrayHeader * t39 = {0};
    int64_t t40;
    double t41;
    HeroStr t42 = {0};
    HeroArrayHeader * t43 = {0};
    HeroArrayHeader * t44 = {0};
    int64_t t45;
    double t46;
    bool t47;
    bool t48;
    bool t49;
    bool t50;
    bool t51;
    HeroArrayHeader * t52 = {0};
    HeroArrayHeader * t53 = {0};
    HeroArrayHeader * t54 = {0};
    HeroArrayHeader * t55 = {0};
    int64_t t56;
    bool t57;
    HeroArrayHeader * t58 = {0};
    int64_t t59;
    bool t60;
    HeroArrayHeader * t61 = {0};
    int64_t t62;
    bool t63;
    HeroArrayHeader * t64 = {0};
    int64_t t65;
    bool t66;
    HeroArrayHeader * t67 = {0};
    int64_t t68;
    bool t69;
    HeroArrayHeader * t70 = {0};
    int64_t t71;
    int64_t t72;
    HeroArrayHeader * t73 = {0};
    HeroArrayHeader * t74 = {0};
    int64_t t75;
    HeroArrayHeader * t76 = {0};
    HeroStr t77 = {0};
    HeroStr t78 = {0};
    HeroArrayHeader * t79 = {0};
    int64_t t80;
    int64_t t81;
    HeroArrayHeader * t82 = {0};
    int64_t t83;
    HeroArrayHeader * t84 = {0};
    int64_t t85;
    int64_t t86;
    HeroArrayHeader * t87 = {0};
    int64_t t88;
    HeroArrayHeader * t89 = {0};
    HeroStr t90 = {0};
    HeroArrayHeader * t91 = {0};
    HeroStr t92 = {0};
    HeroStr t93 = {0};
    HeroStr t94 = {0};
    HeroStr t95 = {0};
    HeroStr t96 = {0};
    HeroArrayHeader * t97 = {0};
    HeroStr t98 = {0};
    HeroStr t99 = {0};
    HeroStr t100 = {0};
    HeroStr t101 = {0};
    HeroStr t102 = {0};
    int64_t t103;
    HeroStr t104 = {0};
    HeroStr t105 = {0};
    HeroArrayHeader * t106 = {0};
    int64_t t107;
    HeroStr t108 = {0};
    HeroArrayHeader * t109 = {0};
    HeroStr t110 = {0};
    HeroStr t111 = {0};
    HeroStr t112 = {0};
    HeroArrayHeader * t113 = {0};
    HeroStr t114 = {0};
    HeroStr t115 = {0};
    HeroStr t116 = {0};
    bool t117;
    HeroStr t118 = {0};
    HeroArrayHeader * t119 = {0};
    HeroStr t120 = {0};
    HeroStr t121 = {0};
    HeroStr t122 = {0};
    bool t123;
    double t124;
    h_0opt_e201354 t125 = {0};
    h_0opt_e201354 t126 = {0};
    int64_t t127;
    int64_t t128;
    bool t129;
    h_0opt_e201354 t130 = {0};
    HeroFailure t131 = {0};
    h_0opt_e201354 t132 = {0};
    int64_t t133;
    double t134;
    double t135;
    h_0opt_e201354 t136 = {0};
    h_0opt_e201354 t137 = {0};
    int64_t t138;
    int64_t t139;
    bool t140;
    h_0opt_e201354 t141 = {0};
    HeroFailure t142 = {0};
    h_0opt_e201354 t143 = {0};
    int64_t t144;
    double t145;
    h_0opt_e201354 t146 = {0};
    h_0opt_e201354 t147 = {0};
    int64_t t148;
    int64_t t149;
    bool t150;
    h_0opt_e201354 t151 = {0};
    HeroFailure t152 = {0};
    h_0opt_e201354 t153 = {0};
    int64_t t154;
    int64_t t155;
    double t156;
    HeroStr t157 = {0};
    int64_t t158;
    double t159;
    HeroArrayHeader * t160 = {0};
    HeroArrayHeader * t161 = {0};
    HeroArrayHeader * t162 = {0};
    HeroArrayHeader * t163 = {0};
    HeroArrayHeader * t164 = {0};
    HeroArrayHeader * t165 = {0};
    HeroArrayHeader * t166 = {0};
    HeroStr t167 = {0};
    HeroArrayHeader * t168 = {0};
    HeroArrayHeader * t169 = {0};
    HeroArrayHeader * t170 = {0};
    HeroArrayHeader * t171 = {0};
    HeroArrayHeader * t172 = {0};
    HeroArrayHeader * t173 = {0};
    HeroArrayHeader * t174 = {0};
    HeroArrayHeader * t175 = {0};
    HeroArrayHeader * t176 = {0};
    HeroArrayHeader * t177 = {0};
    HeroStr t178 = {0};
    HeroArrayHeader * t179 = {0};
    HeroArrayHeader * t180 = {0};
    HeroArrayHeader * t181 = {0};
    HeroArrayHeader * t182 = {0};
    HeroStr t183 = {0};
    HeroArrayHeader * t184 = {0};
    HeroStr t185 = {0};
    HeroStr t186 = {0};
    HeroArrayHeader * t187 = {0};
    HeroArrayHeader * t188 = {0};
    HeroStr t189 = {0};
    HeroArrayHeader * t190 = {0};
    HeroStr t191 = {0};
    HeroArrayHeader * t192 = {0};
    HeroStr t193 = {0};
    h_0opt_e201354 t194 = {0};
    h_0opt_e201354 t195 = {0};
    h_0opt_e201354 t196 = {0};
    h_0opt_e201354 t197 = {0};
    h_0opt_e201354 t198 = {0};
    h_0opt_e201354 t199 = {0};
    goto bb0;
bb0:
#line 20 "tests/golden/run/builtins.hero"
    t1 = INT64_C(3);
#line 20 "tests/golden/run/builtins.hero"
    t2 = INT64_C(1);
#line 20 "tests/golden/run/builtins.hero"
    t3 = INT64_C(2);
#line 20 "tests/golden/run/builtins.hero"
    t4 = hero_array_new(&hero_desc_int, 3);
#line 20 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t4, &t1);
#line 20 "tests/golden/run/builtins.hero"
      hero_array_decref(t4); t4 = grown; }
#line 20 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t4, &t2);
#line 20 "tests/golden/run/builtins.hero"
      hero_array_decref(t4); t4 = grown; }
#line 20 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t4, &t3);
#line 20 "tests/golden/run/builtins.hero"
      hero_array_decref(t4); t4 = grown; }
#line 20 "tests/golden/run/builtins.hero"
    t160 = h12_own12;
#line 20 "tests/golden/run/builtins.hero"
    h12_own12 = t4;
#line 386 "builtins.c"
    hero_array_decref(t160);
#line 20 "tests/golden/run/builtins.hero"
    t161 = h0_xs;
#line 390 "builtins.c"
    hero_array_incref(t4);
#line 20 "tests/golden/run/builtins.hero"
    h0_xs = t4;
#line 394 "builtins.c"
    hero_array_decref(t161);
#line 21 "tests/golden/run/builtins.hero"
    t5 = h0_xs;
#line 21 "tests/golden/run/builtins.hero"
    t6 = hero_array_sort(t5);
#line 21 "tests/golden/run/builtins.hero"
    t162 = h13_own13;
#line 21 "tests/golden/run/builtins.hero"
    h13_own13 = t6;
#line 404 "builtins.c"
    hero_array_decref(t162);
#line 21 "tests/golden/run/builtins.hero"
    t163 = h1_sorted;
#line 408 "builtins.c"
    hero_array_incref(t6);
#line 21 "tests/golden/run/builtins.hero"
    h1_sorted = t6;
#line 412 "builtins.c"
    hero_array_decref(t163);
#line 22 "tests/golden/run/builtins.hero"
    t7 = h1_sorted;
#line 22 "tests/golden/run/builtins.hero"
    t8 = INT64_C(0);
#line 22 "tests/golden/run/builtins.hero"
    t9 = *(int64_t const *)hero_array_at(t7, t8);
#line 22 "tests/golden/run/builtins.hero"
    t10 = h1_sorted;
#line 22 "tests/golden/run/builtins.hero"
    t11 = INT64_C(1);
#line 22 "tests/golden/run/builtins.hero"
    t12 = *(int64_t const *)hero_array_at(t10, t11);
#line 22 "tests/golden/run/builtins.hero"
    t13 = h1_sorted;
#line 22 "tests/golden/run/builtins.hero"
    t14 = INT64_C(2);
#line 22 "tests/golden/run/builtins.hero"
    t15 = *(int64_t const *)hero_array_at(t13, t14);
#line 22 "tests/golden/run/builtins.hero"
    hero_print_int(t9);
#line 22 "tests/golden/run/builtins.hero"
    hero_print_int(t12);
#line 22 "tests/golden/run/builtins.hero"
    hero_print_int(t15);
#line 22 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 25 "tests/golden/run/builtins.hero"
    t16 = h0_xs;
#line 25 "tests/golden/run/builtins.hero"
    t17 = INT64_C(0);
#line 25 "tests/golden/run/builtins.hero"
    t18 = *(int64_t const *)hero_array_at(t16, t17);
#line 25 "tests/golden/run/builtins.hero"
    t19 = h0_xs;
#line 25 "tests/golden/run/builtins.hero"
    t20 = INT64_C(1);
#line 25 "tests/golden/run/builtins.hero"
    t21 = *(int64_t const *)hero_array_at(t19, t20);
#line 25 "tests/golden/run/builtins.hero"
    t22 = h0_xs;
#line 25 "tests/golden/run/builtins.hero"
    t23 = INT64_C(2);
#line 25 "tests/golden/run/builtins.hero"
    t24 = *(int64_t const *)hero_array_at(t22, t23);
#line 25 "tests/golden/run/builtins.hero"
    hero_print_int(t18);
#line 25 "tests/golden/run/builtins.hero"
    hero_print_int(t21);
#line 25 "tests/golden/run/builtins.hero"
    hero_print_int(t24);
#line 25 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 27 "tests/golden/run/builtins.hero"
    t25 = HERO_STR_LIT(hero_str_3ba202d1);
#line 27 "tests/golden/run/builtins.hero"
    t26 = HERO_STR_LIT(hero_str_47b33001);
#line 27 "tests/golden/run/builtins.hero"
    t27 = HERO_STR_LIT(hero_str_f827bb9);
#line 27 "tests/golden/run/builtins.hero"
    t28 = HERO_STR_LIT(hero_str_47b33001);
#line 27 "tests/golden/run/builtins.hero"
    t29 = hero_array_new(&hero_desc_str, 4);
#line 27 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t29, &t25);
#line 27 "tests/golden/run/builtins.hero"
      hero_array_decref(t29); t29 = grown; }
#line 27 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t29, &t26);
#line 27 "tests/golden/run/builtins.hero"
      hero_array_decref(t29); t29 = grown; }
#line 27 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t29, &t27);
#line 27 "tests/golden/run/builtins.hero"
      hero_array_decref(t29); t29 = grown; }
#line 27 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t29, &t28);
#line 27 "tests/golden/run/builtins.hero"
      hero_array_decref(t29); t29 = grown; }
#line 27 "tests/golden/run/builtins.hero"
    t164 = h14_own14;
#line 27 "tests/golden/run/builtins.hero"
    h14_own14 = t29;
#line 496 "builtins.c"
    hero_array_decref(t164);
#line 27 "tests/golden/run/builtins.hero"
    t165 = h2_names;
#line 500 "builtins.c"
    hero_array_incref(t29);
#line 27 "tests/golden/run/builtins.hero"
    h2_names = t29;
#line 504 "builtins.c"
    hero_array_decref(t165);
#line 28 "tests/golden/run/builtins.hero"
    t30 = h2_names;
#line 28 "tests/golden/run/builtins.hero"
    t31 = hero_array_sort(t30);
#line 28 "tests/golden/run/builtins.hero"
    t166 = h15_own15;
#line 28 "tests/golden/run/builtins.hero"
    h15_own15 = t31;
#line 514 "builtins.c"
    hero_array_decref(t166);
#line 28 "tests/golden/run/builtins.hero"
    t32 = HERO_STR_LIT(hero_str_7c);
#line 28 "tests/golden/run/builtins.hero"
    t33 = hero_str_join(t31, t32);
#line 28 "tests/golden/run/builtins.hero"
    t167 = h16_own16;
#line 28 "tests/golden/run/builtins.hero"
    h16_own16 = t33;
#line 524 "builtins.c"
    hero_str_decref(t167);
#line 28 "tests/golden/run/builtins.hero"
    hero_print_str(t33);
#line 28 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 30 "tests/golden/run/builtins.hero"
    t34 = 0x1.4p+1;
#line 30 "tests/golden/run/builtins.hero"
    t35 = 0x1p-1;
#line 30 "tests/golden/run/builtins.hero"
    t36 = 0x1.8p+0;
#line 30 "tests/golden/run/builtins.hero"
    t37 = hero_array_new(&hero_desc_f64, 3);
#line 30 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t37, &t34);
#line 30 "tests/golden/run/builtins.hero"
      hero_array_decref(t37); t37 = grown; }
#line 30 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t37, &t35);
#line 30 "tests/golden/run/builtins.hero"
      hero_array_decref(t37); t37 = grown; }
#line 30 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t37, &t36);
#line 30 "tests/golden/run/builtins.hero"
      hero_array_decref(t37); t37 = grown; }
#line 30 "tests/golden/run/builtins.hero"
    t168 = h17_own17;
#line 30 "tests/golden/run/builtins.hero"
    h17_own17 = t37;
#line 554 "builtins.c"
    hero_array_decref(t168);
#line 30 "tests/golden/run/builtins.hero"
    t169 = h3_fs;
#line 558 "builtins.c"
    hero_array_incref(t37);
#line 30 "tests/golden/run/builtins.hero"
    h3_fs = t37;
#line 562 "builtins.c"
    hero_array_decref(t169);
#line 31 "tests/golden/run/builtins.hero"
    t38 = h3_fs;
#line 31 "tests/golden/run/builtins.hero"
    t39 = hero_array_sort(t38);
#line 31 "tests/golden/run/builtins.hero"
    t170 = h18_own18;
#line 31 "tests/golden/run/builtins.hero"
    h18_own18 = t39;
#line 572 "builtins.c"
    hero_array_decref(t170);
#line 31 "tests/golden/run/builtins.hero"
    t40 = INT64_C(0);
#line 31 "tests/golden/run/builtins.hero"
    t41 = *(double const *)hero_array_at(t39, t40);
#line 31 "tests/golden/run/builtins.hero"
    t42 = HERO_STR_LIT(hero_str_20);
#line 31 "tests/golden/run/builtins.hero"
    t43 = h3_fs;
#line 31 "tests/golden/run/builtins.hero"
    t44 = hero_array_sort(t43);
#line 31 "tests/golden/run/builtins.hero"
    t171 = h19_own19;
#line 31 "tests/golden/run/builtins.hero"
    h19_own19 = t44;
#line 588 "builtins.c"
    hero_array_decref(t171);
#line 31 "tests/golden/run/builtins.hero"
    t45 = INT64_C(2);
#line 31 "tests/golden/run/builtins.hero"
    t46 = *(double const *)hero_array_at(t44, t45);
#line 31 "tests/golden/run/builtins.hero"
    hero_print_f64(t41);
#line 31 "tests/golden/run/builtins.hero"
    hero_print_str(t42);
#line 31 "tests/golden/run/builtins.hero"
    hero_print_f64(t46);
#line 31 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 35 "tests/golden/run/builtins.hero"
    t47 = true;
#line 35 "tests/golden/run/builtins.hero"
    t48 = false;
#line 35 "tests/golden/run/builtins.hero"
    t49 = true;
#line 35 "tests/golden/run/builtins.hero"
    t50 = false;
#line 35 "tests/golden/run/builtins.hero"
    t51 = true;
#line 35 "tests/golden/run/builtins.hero"
    t52 = hero_array_new(&hero_desc_bool, 5);
#line 35 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t52, &t47);
#line 35 "tests/golden/run/builtins.hero"
      hero_array_decref(t52); t52 = grown; }
#line 35 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t52, &t48);
#line 35 "tests/golden/run/builtins.hero"
      hero_array_decref(t52); t52 = grown; }
#line 35 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t52, &t49);
#line 35 "tests/golden/run/builtins.hero"
      hero_array_decref(t52); t52 = grown; }
#line 35 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t52, &t50);
#line 35 "tests/golden/run/builtins.hero"
      hero_array_decref(t52); t52 = grown; }
#line 35 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t52, &t51);
#line 35 "tests/golden/run/builtins.hero"
      hero_array_decref(t52); t52 = grown; }
#line 35 "tests/golden/run/builtins.hero"
    t172 = h20_own20;
#line 35 "tests/golden/run/builtins.hero"
    h20_own20 = t52;
#line 638 "builtins.c"
    hero_array_decref(t172);
#line 35 "tests/golden/run/builtins.hero"
    t173 = h4_flags;
#line 642 "builtins.c"
    hero_array_incref(t52);
#line 35 "tests/golden/run/builtins.hero"
    h4_flags = t52;
#line 646 "builtins.c"
    hero_array_decref(t173);
#line 36 "tests/golden/run/builtins.hero"
    t53 = h4_flags;
#line 36 "tests/golden/run/builtins.hero"
    t54 = hero_array_sort(t53);
#line 36 "tests/golden/run/builtins.hero"
    t174 = h21_own21;
#line 36 "tests/golden/run/builtins.hero"
    h21_own21 = t54;
#line 656 "builtins.c"
    hero_array_decref(t174);
#line 36 "tests/golden/run/builtins.hero"
    t175 = h5_ordered;
#line 660 "builtins.c"
    hero_array_incref(t54);
#line 36 "tests/golden/run/builtins.hero"
    h5_ordered = t54;
#line 664 "builtins.c"
    hero_array_decref(t175);
#line 37 "tests/golden/run/builtins.hero"
    t55 = h5_ordered;
#line 37 "tests/golden/run/builtins.hero"
    t56 = INT64_C(0);
#line 37 "tests/golden/run/builtins.hero"
    t57 = *(bool const *)hero_array_at(t55, t56);
#line 37 "tests/golden/run/builtins.hero"
    t58 = h5_ordered;
#line 37 "tests/golden/run/builtins.hero"
    t59 = INT64_C(1);
#line 37 "tests/golden/run/builtins.hero"
    t60 = *(bool const *)hero_array_at(t58, t59);
#line 37 "tests/golden/run/builtins.hero"
    t61 = h5_ordered;
#line 37 "tests/golden/run/builtins.hero"
    t62 = INT64_C(2);
#line 37 "tests/golden/run/builtins.hero"
    t63 = *(bool const *)hero_array_at(t61, t62);
#line 37 "tests/golden/run/builtins.hero"
    t64 = h5_ordered;
#line 37 "tests/golden/run/builtins.hero"
    t65 = INT64_C(3);
#line 37 "tests/golden/run/builtins.hero"
    t66 = *(bool const *)hero_array_at(t64, t65);
#line 37 "tests/golden/run/builtins.hero"
    t67 = h5_ordered;
#line 37 "tests/golden/run/builtins.hero"
    t68 = INT64_C(4);
#line 37 "tests/golden/run/builtins.hero"
    t69 = *(bool const *)hero_array_at(t67, t68);
#line 37 "tests/golden/run/builtins.hero"
    hero_print_bool(t57);
#line 37 "tests/golden/run/builtins.hero"
    hero_print_bool(t60);
#line 37 "tests/golden/run/builtins.hero"
    hero_print_bool(t63);
#line 37 "tests/golden/run/builtins.hero"
    hero_print_bool(t66);
#line 37 "tests/golden/run/builtins.hero"
    hero_print_bool(t69);
#line 37 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 40 "tests/golden/run/builtins.hero"
    t70 = h2_names;
#line 40 "tests/golden/run/builtins.hero"
    t71 = INT64_C(1);
#line 40 "tests/golden/run/builtins.hero"
    t72 = INT64_C(3);
#line 40 "tests/golden/run/builtins.hero"
    t73 = hero_array_slice(t70, t71, t72);
#line 40 "tests/golden/run/builtins.hero"
    t176 = h22_own22;
#line 40 "tests/golden/run/builtins.hero"
    h22_own22 = t73;
#line 720 "builtins.c"
    hero_array_decref(t176);
#line 40 "tests/golden/run/builtins.hero"
    t177 = h6_tail;
#line 724 "builtins.c"
    hero_array_incref(t73);
#line 40 "tests/golden/run/builtins.hero"
    h6_tail = t73;
#line 728 "builtins.c"
    hero_array_decref(t177);
#line 41 "tests/golden/run/builtins.hero"
    t74 = h6_tail;
#line 41 "tests/golden/run/builtins.hero"
    t75 = hero_array_len(t74);
#line 41 "tests/golden/run/builtins.hero"
    t76 = h6_tail;
#line 41 "tests/golden/run/builtins.hero"
    t77 = HERO_STR_LIT(hero_str_2d);
#line 41 "tests/golden/run/builtins.hero"
    t78 = hero_str_join(t76, t77);
#line 41 "tests/golden/run/builtins.hero"
    t178 = h23_own23;
#line 41 "tests/golden/run/builtins.hero"
    h23_own23 = t78;
#line 744 "builtins.c"
    hero_str_decref(t178);
#line 41 "tests/golden/run/builtins.hero"
    hero_print_int(t75);
#line 41 "tests/golden/run/builtins.hero"
    hero_print_str(t78);
#line 41 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 42 "tests/golden/run/builtins.hero"
    t79 = h2_names;
#line 42 "tests/golden/run/builtins.hero"
    t80 = INT64_C(0);
#line 42 "tests/golden/run/builtins.hero"
    t81 = INT64_C(0);
#line 42 "tests/golden/run/builtins.hero"
    t82 = hero_array_slice(t79, t80, t81);
#line 42 "tests/golden/run/builtins.hero"
    t179 = h24_own24;
#line 42 "tests/golden/run/builtins.hero"
    h24_own24 = t82;
#line 764 "builtins.c"
    hero_array_decref(t179);
#line 42 "tests/golden/run/builtins.hero"
    t83 = hero_array_len(t82);
#line 42 "tests/golden/run/builtins.hero"
    t84 = h2_names;
#line 42 "tests/golden/run/builtins.hero"
    t85 = INT64_C(4);
#line 42 "tests/golden/run/builtins.hero"
    t86 = INT64_C(4);
#line 42 "tests/golden/run/builtins.hero"
    t87 = hero_array_slice(t84, t85, t86);
#line 42 "tests/golden/run/builtins.hero"
    t180 = h25_own25;
#line 42 "tests/golden/run/builtins.hero"
    h25_own25 = t87;
#line 780 "builtins.c"
    hero_array_decref(t180);
#line 42 "tests/golden/run/builtins.hero"
    t88 = hero_array_len(t87);
#line 42 "tests/golden/run/builtins.hero"
    hero_print_int(t83);
#line 42 "tests/golden/run/builtins.hero"
    hero_print_int(t88);
#line 42 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 45 "tests/golden/run/builtins.hero"
    t89 = hero_array_new(&hero_desc_str, 1);
#line 45 "tests/golden/run/builtins.hero"
    t181 = h26_own26;
#line 45 "tests/golden/run/builtins.hero"
    h26_own26 = t89;
#line 796 "builtins.c"
    hero_array_decref(t181);
#line 45 "tests/golden/run/builtins.hero"
    t182 = h7_empty;
#line 800 "builtins.c"
    hero_array_incref(t89);
#line 45 "tests/golden/run/builtins.hero"
    h7_empty = t89;
#line 804 "builtins.c"
    hero_array_decref(t182);
#line 46 "tests/golden/run/builtins.hero"
    t90 = HERO_STR_LIT(hero_str_5b);
#line 46 "tests/golden/run/builtins.hero"
    t91 = h7_empty;
#line 46 "tests/golden/run/builtins.hero"
    t92 = HERO_STR_LIT(hero_str_2c);
#line 46 "tests/golden/run/builtins.hero"
    t93 = hero_str_join(t91, t92);
#line 46 "tests/golden/run/builtins.hero"
    t183 = h27_own27;
#line 46 "tests/golden/run/builtins.hero"
    h27_own27 = t93;
#line 818 "builtins.c"
    hero_str_decref(t183);
#line 46 "tests/golden/run/builtins.hero"
    t94 = HERO_STR_LIT(hero_str_5d);
#line 46 "tests/golden/run/builtins.hero"
    hero_print_str(t90);
#line 46 "tests/golden/run/builtins.hero"
    hero_print_str(t93);
#line 46 "tests/golden/run/builtins.hero"
    hero_print_str(t94);
#line 46 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 47 "tests/golden/run/builtins.hero"
    t95 = HERO_STR_LIT(hero_str_5b);
#line 47 "tests/golden/run/builtins.hero"
    t96 = HERO_STR_LIT(hero_str_efcabd0);
#line 47 "tests/golden/run/builtins.hero"
    t97 = hero_array_new(&hero_desc_str, 1);
#line 47 "tests/golden/run/builtins.hero"
    { HeroArrayHeader *grown = hero_array_push(t97, &t96);
#line 47 "tests/golden/run/builtins.hero"
      hero_array_decref(t97); t97 = grown; }
#line 47 "tests/golden/run/builtins.hero"
    t184 = h28_own28;
#line 47 "tests/golden/run/builtins.hero"
    h28_own28 = t97;
#line 844 "builtins.c"
    hero_array_decref(t184);
#line 47 "tests/golden/run/builtins.hero"
    t98 = HERO_STR_LIT(hero_str_2c);
#line 47 "tests/golden/run/builtins.hero"
    t99 = hero_str_join(t97, t98);
#line 47 "tests/golden/run/builtins.hero"
    t185 = h29_own29;
#line 47 "tests/golden/run/builtins.hero"
    h29_own29 = t99;
#line 854 "builtins.c"
    hero_str_decref(t185);
#line 47 "tests/golden/run/builtins.hero"
    t100 = HERO_STR_LIT(hero_str_5d);
#line 47 "tests/golden/run/builtins.hero"
    hero_print_str(t95);
#line 47 "tests/golden/run/builtins.hero"
    hero_print_str(t99);
#line 47 "tests/golden/run/builtins.hero"
    hero_print_str(t100);
#line 47 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 50 "tests/golden/run/builtins.hero"
    t101 = HERO_STR_LIT(hero_str_78a14ef2);
#line 50 "tests/golden/run/builtins.hero"
    t186 = h8_word;
#line 870 "builtins.c"
    hero_str_incref(t101);
#line 50 "tests/golden/run/builtins.hero"
    h8_word = t101;
#line 874 "builtins.c"
    hero_str_decref(t186);
#line 51 "tests/golden/run/builtins.hero"
    t102 = h8_word;
#line 51 "tests/golden/run/builtins.hero"
    t103 = hero_str_len(t102);
#line 51 "tests/golden/run/builtins.hero"
    t104 = HERO_STR_LIT(hero_str_20);
#line 51 "tests/golden/run/builtins.hero"
    t105 = h8_word;
#line 51 "tests/golden/run/builtins.hero"
    t106 = hero_str_chars(t105);
#line 51 "tests/golden/run/builtins.hero"
    t187 = h30_own30;
#line 51 "tests/golden/run/builtins.hero"
    h30_own30 = t106;
#line 890 "builtins.c"
    hero_array_decref(t187);
#line 51 "tests/golden/run/builtins.hero"
    t107 = hero_array_len(t106);
#line 51 "tests/golden/run/builtins.hero"
    hero_print_int(t103);
#line 51 "tests/golden/run/builtins.hero"
    hero_print_str(t104);
#line 51 "tests/golden/run/builtins.hero"
    hero_print_int(t107);
#line 51 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 52 "tests/golden/run/builtins.hero"
    t108 = h8_word;
#line 52 "tests/golden/run/builtins.hero"
    t109 = hero_str_chars(t108);
#line 52 "tests/golden/run/builtins.hero"
    t188 = h31_own31;
#line 52 "tests/golden/run/builtins.hero"
    h31_own31 = t109;
#line 910 "builtins.c"
    hero_array_decref(t188);
#line 52 "tests/golden/run/builtins.hero"
    t110 = HERO_STR_LIT(hero_str_2e);
#line 52 "tests/golden/run/builtins.hero"
    t111 = hero_str_join(t109, t110);
#line 52 "tests/golden/run/builtins.hero"
    t189 = h32_own32;
#line 52 "tests/golden/run/builtins.hero"
    h32_own32 = t111;
#line 920 "builtins.c"
    hero_str_decref(t189);
#line 52 "tests/golden/run/builtins.hero"
    hero_print_str(t111);
#line 52 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 55 "tests/golden/run/builtins.hero"
    t112 = h8_word;
#line 55 "tests/golden/run/builtins.hero"
    t113 = hero_str_chars(t112);
#line 55 "tests/golden/run/builtins.hero"
    t190 = h33_own33;
#line 55 "tests/golden/run/builtins.hero"
    h33_own33 = t113;
#line 934 "builtins.c"
    hero_array_decref(t190);
#line 55 "tests/golden/run/builtins.hero"
    t114 = HERO_STR_LIT(hero_str_0);
#line 55 "tests/golden/run/builtins.hero"
    t115 = hero_str_join(t113, t114);
#line 55 "tests/golden/run/builtins.hero"
    t191 = h34_own34;
#line 55 "tests/golden/run/builtins.hero"
    h34_own34 = t115;
#line 944 "builtins.c"
    hero_str_decref(t191);
#line 55 "tests/golden/run/builtins.hero"
    t116 = h8_word;
#line 55 "tests/golden/run/builtins.hero"
    t117 = hero_str_eq(t115, t116);
#line 55 "tests/golden/run/builtins.hero"
    hero_print_bool(t117);
#line 55 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 56 "tests/golden/run/builtins.hero"
    t118 = HERO_STR_LIT(hero_str_0);
#line 56 "tests/golden/run/builtins.hero"
    t119 = hero_str_chars(t118);
#line 56 "tests/golden/run/builtins.hero"
    t192 = h35_own35;
#line 56 "tests/golden/run/builtins.hero"
    h35_own35 = t119;
#line 962 "builtins.c"
    hero_array_decref(t192);
#line 56 "tests/golden/run/builtins.hero"
    t120 = HERO_STR_LIT(hero_str_0);
#line 56 "tests/golden/run/builtins.hero"
    t121 = hero_str_join(t119, t120);
#line 56 "tests/golden/run/builtins.hero"
    t193 = h36_own36;
#line 56 "tests/golden/run/builtins.hero"
    h36_own36 = t121;
#line 972 "builtins.c"
    hero_str_decref(t193);
#line 56 "tests/golden/run/builtins.hero"
    t122 = HERO_STR_LIT(hero_str_0);
#line 56 "tests/golden/run/builtins.hero"
    t123 = hero_str_eq(t121, t122);
#line 56 "tests/golden/run/builtins.hero"
    hero_print_bool(t123);
#line 56 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 58 "tests/golden/run/builtins.hero"
    t124 = 0x1.f333333333333p+1;
#line 58 "tests/golden/run/builtins.hero"
    if (hero_f64_fits_int(t124)) {
#line 58 "tests/golden/run/builtins.hero"
        t125 = (h_0opt_e201354){.tag = INT64_C(0), .as.ok = hero_f64_to_int(t124)};
#line 58 "tests/golden/run/builtins.hero"
    } else {
#line 58 "tests/golden/run/builtins.hero"
        t125 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_does_not_fit()};
#line 58 "tests/golden/run/builtins.hero"
    }
#line 58 "tests/golden/run/builtins.hero"
    t194 = h37_own37;
#line 58 "tests/golden/run/builtins.hero"
    h37_own37 = t125;
#line 998 "builtins.c"
    h_0opt_e201354_release(&t194);
#line 58 "tests/golden/run/builtins.hero"
    t195 = h9_f0;
#line 1002 "builtins.c"
    h_0opt_e201354_retain(&t125);
#line 58 "tests/golden/run/builtins.hero"
    h9_f0 = t125;
#line 1006 "builtins.c"
    h_0opt_e201354_release(&t195);
#line 58 "tests/golden/run/builtins.hero"
    t126 = h9_f0;
#line 58 "tests/golden/run/builtins.hero"
    t127 = t126.tag;
#line 58 "tests/golden/run/builtins.hero"
    t128 = INT64_C(0);
#line 58 "tests/golden/run/builtins.hero"
    t129 = t127 == t128;
#line 58 "tests/golden/run/builtins.hero"
    if (t129) goto bb1; else goto bb2;
#line 58 "tests/golden/run/builtins.hero"
bb1:
#line 58 "tests/golden/run/builtins.hero"
    t132 = h9_f0;
#line 58 "tests/golden/run/builtins.hero"
    t133 = t132.as.ok;
#line 58 "tests/golden/run/builtins.hero"
    t134 = 0x1.f333333333333p+1;
#line 58 "tests/golden/run/builtins.hero"
    t135 = -t134;
#line 58 "tests/golden/run/builtins.hero"
    if (hero_f64_fits_int(t135)) {
#line 58 "tests/golden/run/builtins.hero"
        t136 = (h_0opt_e201354){.tag = INT64_C(0), .as.ok = hero_f64_to_int(t135)};
#line 58 "tests/golden/run/builtins.hero"
    } else {
#line 58 "tests/golden/run/builtins.hero"
        t136 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_does_not_fit()};
#line 58 "tests/golden/run/builtins.hero"
    }
#line 58 "tests/golden/run/builtins.hero"
    t196 = h38_own38;
#line 58 "tests/golden/run/builtins.hero"
    h38_own38 = t136;
#line 1042 "builtins.c"
    h_0opt_e201354_release(&t196);
#line 58 "tests/golden/run/builtins.hero"
    t197 = h10_f1;
#line 1046 "builtins.c"
    h_0opt_e201354_retain(&t136);
#line 58 "tests/golden/run/builtins.hero"
    h10_f1 = t136;
#line 1050 "builtins.c"
    h_0opt_e201354_release(&t197);
#line 58 "tests/golden/run/builtins.hero"
    t137 = h10_f1;
#line 58 "tests/golden/run/builtins.hero"
    t138 = t137.tag;
#line 58 "tests/golden/run/builtins.hero"
    t139 = INT64_C(0);
#line 58 "tests/golden/run/builtins.hero"
    t140 = t138 == t139;
#line 58 "tests/golden/run/builtins.hero"
    if (t140) goto bb3; else goto bb4;
#line 58 "tests/golden/run/builtins.hero"
bb2:
#line 58 "tests/golden/run/builtins.hero"
    t130 = h9_f0;
#line 58 "tests/golden/run/builtins.hero"
    t131 = t130.as.err;
#line 1068 "builtins.c"
    hero_panic_must(t131);
    hero_unreachable();
bb3:
#line 58 "tests/golden/run/builtins.hero"
    t143 = h10_f1;
#line 58 "tests/golden/run/builtins.hero"
    t144 = t143.as.ok;
#line 58 "tests/golden/run/builtins.hero"
    t145 = 0x0p+0;
#line 58 "tests/golden/run/builtins.hero"
    if (hero_f64_fits_int(t145)) {
#line 58 "tests/golden/run/builtins.hero"
        t146 = (h_0opt_e201354){.tag = INT64_C(0), .as.ok = hero_f64_to_int(t145)};
#line 58 "tests/golden/run/builtins.hero"
    } else {
#line 58 "tests/golden/run/builtins.hero"
        t146 = (h_0opt_e201354){.tag = INT64_C(1), .as.err = hero_failure_does_not_fit()};
#line 58 "tests/golden/run/builtins.hero"
    }
#line 58 "tests/golden/run/builtins.hero"
    t198 = h39_own39;
#line 58 "tests/golden/run/builtins.hero"
    h39_own39 = t146;
#line 1092 "builtins.c"
    h_0opt_e201354_release(&t198);
#line 58 "tests/golden/run/builtins.hero"
    t199 = h11_f2;
#line 1096 "builtins.c"
    h_0opt_e201354_retain(&t146);
#line 58 "tests/golden/run/builtins.hero"
    h11_f2 = t146;
#line 1100 "builtins.c"
    h_0opt_e201354_release(&t199);
#line 58 "tests/golden/run/builtins.hero"
    t147 = h11_f2;
#line 58 "tests/golden/run/builtins.hero"
    t148 = t147.tag;
#line 58 "tests/golden/run/builtins.hero"
    t149 = INT64_C(0);
#line 58 "tests/golden/run/builtins.hero"
    t150 = t148 == t149;
#line 58 "tests/golden/run/builtins.hero"
    if (t150) goto bb5; else goto bb6;
#line 58 "tests/golden/run/builtins.hero"
bb4:
#line 58 "tests/golden/run/builtins.hero"
    t141 = h10_f1;
#line 58 "tests/golden/run/builtins.hero"
    t142 = t141.as.err;
#line 1118 "builtins.c"
    hero_panic_must(t142);
    hero_unreachable();
bb5:
#line 58 "tests/golden/run/builtins.hero"
    t153 = h11_f2;
#line 58 "tests/golden/run/builtins.hero"
    t154 = t153.as.ok;
#line 58 "tests/golden/run/builtins.hero"
    hero_print_int(t133);
#line 58 "tests/golden/run/builtins.hero"
    hero_print_int(t144);
#line 58 "tests/golden/run/builtins.hero"
    hero_print_int(t154);
#line 58 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 59 "tests/golden/run/builtins.hero"
    t155 = INT64_C(3);
#line 59 "tests/golden/run/builtins.hero"
    t156 = hero_int_to_f64(t155);
#line 59 "tests/golden/run/builtins.hero"
    t157 = HERO_STR_LIT(hero_str_20);
#line 59 "tests/golden/run/builtins.hero"
    t158 = INT64_C(-1);
#line 59 "tests/golden/run/builtins.hero"
    t159 = hero_int_to_f64(t158);
#line 59 "tests/golden/run/builtins.hero"
    hero_print_f64(t156);
#line 59 "tests/golden/run/builtins.hero"
    hero_print_str(t157);
#line 59 "tests/golden/run/builtins.hero"
    hero_print_f64(t159);
#line 59 "tests/golden/run/builtins.hero"
    hero_print_end();
#line 1152 "builtins.c"
    hero_array_decref(h0_xs);
#line 59 "tests/golden/run/builtins.hero"
#line 1155 "builtins.c"
    hero_array_decref(h1_sorted);
#line 59 "tests/golden/run/builtins.hero"
#line 1158 "builtins.c"
    hero_array_decref(h2_names);
#line 59 "tests/golden/run/builtins.hero"
#line 1161 "builtins.c"
    hero_array_decref(h3_fs);
#line 59 "tests/golden/run/builtins.hero"
#line 1164 "builtins.c"
    hero_array_decref(h4_flags);
#line 59 "tests/golden/run/builtins.hero"
#line 1167 "builtins.c"
    hero_array_decref(h5_ordered);
#line 59 "tests/golden/run/builtins.hero"
#line 1170 "builtins.c"
    hero_array_decref(h6_tail);
#line 59 "tests/golden/run/builtins.hero"
#line 1173 "builtins.c"
    hero_array_decref(h7_empty);
#line 59 "tests/golden/run/builtins.hero"
#line 1176 "builtins.c"
    hero_str_decref(h8_word);
#line 59 "tests/golden/run/builtins.hero"
#line 1179 "builtins.c"
    h_0opt_e201354_release(&h9_f0);
#line 59 "tests/golden/run/builtins.hero"
#line 1182 "builtins.c"
    h_0opt_e201354_release(&h10_f1);
#line 59 "tests/golden/run/builtins.hero"
#line 1185 "builtins.c"
    h_0opt_e201354_release(&h11_f2);
#line 59 "tests/golden/run/builtins.hero"
#line 1188 "builtins.c"
    hero_array_decref(h12_own12);
#line 59 "tests/golden/run/builtins.hero"
#line 1191 "builtins.c"
    hero_array_decref(h13_own13);
#line 59 "tests/golden/run/builtins.hero"
#line 1194 "builtins.c"
    hero_array_decref(h14_own14);
#line 59 "tests/golden/run/builtins.hero"
#line 1197 "builtins.c"
    hero_array_decref(h15_own15);
#line 59 "tests/golden/run/builtins.hero"
#line 1200 "builtins.c"
    hero_str_decref(h16_own16);
#line 59 "tests/golden/run/builtins.hero"
#line 1203 "builtins.c"
    hero_array_decref(h17_own17);
#line 59 "tests/golden/run/builtins.hero"
#line 1206 "builtins.c"
    hero_array_decref(h18_own18);
#line 59 "tests/golden/run/builtins.hero"
#line 1209 "builtins.c"
    hero_array_decref(h19_own19);
#line 59 "tests/golden/run/builtins.hero"
#line 1212 "builtins.c"
    hero_array_decref(h20_own20);
#line 59 "tests/golden/run/builtins.hero"
#line 1215 "builtins.c"
    hero_array_decref(h21_own21);
#line 59 "tests/golden/run/builtins.hero"
#line 1218 "builtins.c"
    hero_array_decref(h22_own22);
#line 59 "tests/golden/run/builtins.hero"
#line 1221 "builtins.c"
    hero_str_decref(h23_own23);
#line 59 "tests/golden/run/builtins.hero"
#line 1224 "builtins.c"
    hero_array_decref(h24_own24);
#line 59 "tests/golden/run/builtins.hero"
#line 1227 "builtins.c"
    hero_array_decref(h25_own25);
#line 59 "tests/golden/run/builtins.hero"
#line 1230 "builtins.c"
    hero_array_decref(h26_own26);
#line 59 "tests/golden/run/builtins.hero"
#line 1233 "builtins.c"
    hero_str_decref(h27_own27);
#line 59 "tests/golden/run/builtins.hero"
#line 1236 "builtins.c"
    hero_array_decref(h28_own28);
#line 59 "tests/golden/run/builtins.hero"
#line 1239 "builtins.c"
    hero_str_decref(h29_own29);
#line 59 "tests/golden/run/builtins.hero"
#line 1242 "builtins.c"
    hero_array_decref(h30_own30);
#line 59 "tests/golden/run/builtins.hero"
#line 1245 "builtins.c"
    hero_array_decref(h31_own31);
#line 59 "tests/golden/run/builtins.hero"
#line 1248 "builtins.c"
    hero_str_decref(h32_own32);
#line 59 "tests/golden/run/builtins.hero"
#line 1251 "builtins.c"
    hero_array_decref(h33_own33);
#line 59 "tests/golden/run/builtins.hero"
#line 1254 "builtins.c"
    hero_str_decref(h34_own34);
#line 59 "tests/golden/run/builtins.hero"
#line 1257 "builtins.c"
    hero_array_decref(h35_own35);
#line 59 "tests/golden/run/builtins.hero"
#line 1260 "builtins.c"
    hero_str_decref(h36_own36);
#line 59 "tests/golden/run/builtins.hero"
#line 1263 "builtins.c"
    h_0opt_e201354_release(&h37_own37);
#line 59 "tests/golden/run/builtins.hero"
#line 1266 "builtins.c"
    h_0opt_e201354_release(&h38_own38);
#line 59 "tests/golden/run/builtins.hero"
#line 1269 "builtins.c"
    h_0opt_e201354_release(&h39_own39);
    return;
bb6:
#line 58 "tests/golden/run/builtins.hero"
    t151 = h11_f2;
#line 58 "tests/golden/run/builtins.hero"
    t152 = t151.as.err;
#line 1277 "builtins.c"
    hero_panic_must(t152);
    hero_unreachable();
}
HERO_TU_LOCAL void h_0opt_e201354_retain(const h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_e201354_release(h_0opt_e201354 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_e201354_eq(const h_0opt_e201354 *a, const h_0opt_e201354 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_int)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_e201354_hash(const void *elem) {
    const h_0opt_e201354 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_int)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_builtins_main();
    hero_runtime_check_leaks();
    return 0;
}
