/* Generated by heroes 0.0.1 from tests/golden/run/generics.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>

_Static_assert(HERO_RUNTIME_ABI == 16, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) _Generic((c), signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, default:0)
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && !HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:1, default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_STR(hero_file_read(0, (int64_t *)0)), "heroes-ffi-return hero_file_read str");
_Static_assert(HERO_RET_INT(hero_file_write(0, (HeroStr){0})), "heroes-ffi-return hero_file_write i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, (int64_t *)0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 43 "generics.c"
#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 111 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read(const char * a0, int64_t * a1) { (void)(hero_file_read)(a0, a1); }
#line 112 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write(const char * a0, HeroStr a1) { (void)(hero_file_write)(a0, a1); }
#line 114 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
#line 115 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 122 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, a1); }
#line 61 "generics.c"
#pragma clang diagnostic pop

HERO_STR_STATIC(hero_str_23, "#");
HERO_STR_STATIC(hero_str_6bb5e50a, "ziggy");
HERO_STR_STATIC(hero_str_5a47bc97, "starman");
HERO_STR_STATIC(hero_str_20, " ");
HERO_STR_STATIC(hero_str_2d, "-");
HERO_STR_STATIC(hero_str_61, "a");
HERO_STR_STATIC(hero_str_62, "b");
HERO_STR_STATIC(hero_str_63, "c");

typedef HeroStr (*h_0fn_4a13fb08)(int64_t);
typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

HeroStr h_generics_label(int64_t h0_n);
void h_generics_main(void);
HERO_TU_LOCAL HeroStr h_generics_first_1e58d9(HeroArrayHeader * h0_xs);
HERO_TU_LOCAL int64_t h_generics_first_1b9a87(HeroArrayHeader * h0_xs);
HERO_TU_LOCAL HeroStr h_generics_last_1e58d9(HeroArrayHeader * h0_xs);
HERO_TU_LOCAL int64_t h_generics_last_1b9a87(HeroArrayHeader * h0_xs);
HERO_TU_LOCAL HeroArrayHeader * h_generics_convert_37fb3fcc(HeroArrayHeader * h0_xs, h_0fn_4a13fb08 h1_f);
HERO_TU_LOCAL HeroArrayHeader * h_generics_first_4ce7463f(HeroArrayHeader * h0_xs);

#line 29 "tests/golden/run/generics.hero"
HeroStr h_generics_label(int64_t h0_n) {
#line 109 "generics.c"
    HeroStr h1_own1 = {0};
    HeroStr h2_own2 = {0};
    HeroStr t1 = {0};
    int64_t t2;
    HeroStr t3 = {0};
    HeroStr t4 = {0};
    HeroStr t5 = {0};
    HeroStr t6 = {0};
    HeroStr t7 = {0};
    HeroStr t8 = {0};
    goto bb0;
bb0:
#line 30 "tests/golden/run/generics.hero"
    t1 = HERO_STR_LIT(hero_str_23);
#line 30 "tests/golden/run/generics.hero"
    t2 = h0_n;
#line 30 "tests/golden/run/generics.hero"
    t3 = hero_int_to_str(t2);
#line 30 "tests/golden/run/generics.hero"
    t5 = h1_own1;
#line 30 "tests/golden/run/generics.hero"
    h1_own1 = t3;
#line 132 "generics.c"
    hero_str_decref(t5);
#line 30 "tests/golden/run/generics.hero"
    t4 = hero_str_concat(t1, t3);
#line 30 "tests/golden/run/generics.hero"
    t6 = h2_own2;
#line 30 "tests/golden/run/generics.hero"
    h2_own2 = t4;
#line 140 "generics.c"
    hero_str_decref(t6);
#line 30 "tests/golden/run/generics.hero"
#line 143 "generics.c"
    hero_str_incref(t4);
#line 30 "tests/golden/run/generics.hero"
    t7 = h1_own1;
#line 147 "generics.c"
    hero_str_decref(t7);
#line 30 "tests/golden/run/generics.hero"
    t8 = h2_own2;
#line 151 "generics.c"
    hero_str_decref(t8);
    return t4;
}

#line 32 "tests/golden/run/generics.hero"
void h_generics_main(void) {
#line 158 "generics.c"
    HeroArrayHeader * h0_rows = {0};
    HeroArrayHeader * h1_own1 = {0};
    HeroStr h2_own2 = {0};
    HeroArrayHeader * h3_own3 = {0};
    HeroArrayHeader * h4_own4 = {0};
    HeroStr h5_own5 = {0};
    HeroArrayHeader * h6_own6 = {0};
    HeroArrayHeader * h7_own7 = {0};
    HeroArrayHeader * h8_own8 = {0};
    HeroStr h9_own9 = {0};
    HeroArrayHeader * h10_own10 = {0};
    HeroArrayHeader * h11_own11 = {0};
    HeroArrayHeader * h12_own12 = {0};
    HeroArrayHeader * h13_own13 = {0};
    HeroArrayHeader * h14_own14 = {0};
    HeroArrayHeader * h15_own15 = {0};
    HeroArrayHeader * h16_own16 = {0};
    HeroStr h17_own17 = {0};
    HeroStr t1 = {0};
    HeroStr t2 = {0};
    HeroArrayHeader * t3 = {0};
    HeroStr t4 = {0};
    HeroStr t5 = {0};
    int64_t t6;
    int64_t t7;
    int64_t t8;
    HeroArrayHeader * t9 = {0};
    int64_t t10;
    HeroStr t11 = {0};
    HeroStr t12 = {0};
    HeroArrayHeader * t13 = {0};
    HeroStr t14 = {0};
    HeroStr t15 = {0};
    int64_t t16;
    int64_t t17;
    int64_t t18;
    HeroArrayHeader * t19 = {0};
    int64_t t20;
    int64_t t21;
    int64_t t22;
    int64_t t23;
    HeroArrayHeader * t24 = {0};
    h_0fn_4a13fb08 t25;
    HeroArrayHeader * t26 = {0};
    HeroStr t27 = {0};
    HeroStr t28 = {0};
    int64_t t29;
    int64_t t30;
    HeroArrayHeader * t31 = {0};
    int64_t t32;
    int64_t t33;
    int64_t t34;
    HeroArrayHeader * t35 = {0};
    int64_t t36;
    HeroStr t37 = {0};
    HeroStr t38 = {0};
    HeroArrayHeader * t39 = {0};
    HeroStr t40 = {0};
    HeroArrayHeader * t41 = {0};
    HeroArrayHeader * t42 = {0};
    HeroArrayHeader * t43 = {0};
    HeroArrayHeader * t44 = {0};
    int64_t t45;
    HeroStr t46 = {0};
    HeroArrayHeader * t47 = {0};
    HeroArrayHeader * t48 = {0};
    HeroStr t49 = {0};
    HeroArrayHeader * t50 = {0};
    HeroStr t51 = {0};
    HeroArrayHeader * t52 = {0};
    HeroArrayHeader * t53 = {0};
    HeroStr t54 = {0};
    HeroArrayHeader * t55 = {0};
    HeroArrayHeader * t56 = {0};
    HeroArrayHeader * t57 = {0};
    HeroStr t58 = {0};
    HeroArrayHeader * t59 = {0};
    HeroArrayHeader * t60 = {0};
    HeroArrayHeader * t61 = {0};
    HeroArrayHeader * t62 = {0};
    HeroArrayHeader * t63 = {0};
    HeroArrayHeader * t64 = {0};
    HeroArrayHeader * t65 = {0};
    HeroArrayHeader * t66 = {0};
    HeroStr t67 = {0};
    HeroArrayHeader * t68 = {0};
    HeroArrayHeader * t69 = {0};
    HeroStr t70 = {0};
    HeroArrayHeader * t71 = {0};
    HeroArrayHeader * t72 = {0};
    HeroStr t73 = {0};
    HeroArrayHeader * t74 = {0};
    HeroArrayHeader * t75 = {0};
    HeroArrayHeader * t76 = {0};
    HeroStr t77 = {0};
    HeroArrayHeader * t78 = {0};
    HeroArrayHeader * t79 = {0};
    HeroArrayHeader * t80 = {0};
    HeroArrayHeader * t81 = {0};
    HeroArrayHeader * t82 = {0};
    HeroArrayHeader * t83 = {0};
    HeroArrayHeader * t84 = {0};
    HeroStr t85 = {0};
    goto bb0;
bb0:
#line 34 "tests/golden/run/generics.hero"
    t1 = HERO_STR_LIT(hero_str_6bb5e50a);
#line 34 "tests/golden/run/generics.hero"
    t2 = HERO_STR_LIT(hero_str_5a47bc97);
#line 34 "tests/golden/run/generics.hero"
    t3 = hero_array_new(&hero_desc_str, 2);
#line 34 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t3, &t1);
#line 34 "tests/golden/run/generics.hero"
      hero_array_decref(t3); t3 = grown; }
#line 34 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t3, &t2);
#line 34 "tests/golden/run/generics.hero"
      hero_array_decref(t3); t3 = grown; }
#line 34 "tests/golden/run/generics.hero"
    t50 = h1_own1;
#line 34 "tests/golden/run/generics.hero"
    h1_own1 = t3;
#line 282 "generics.c"
    hero_array_decref(t50);
#line 34 "tests/golden/run/generics.hero"
    t4 = h_generics_first_1e58d9(t3);
#line 34 "tests/golden/run/generics.hero"
    t51 = h2_own2;
#line 34 "tests/golden/run/generics.hero"
    h2_own2 = t4;
#line 290 "generics.c"
    hero_str_decref(t51);
#line 34 "tests/golden/run/generics.hero"
    t5 = HERO_STR_LIT(hero_str_20);
#line 34 "tests/golden/run/generics.hero"
    t6 = INT64_C(1);
#line 34 "tests/golden/run/generics.hero"
    t7 = INT64_C(2);
#line 34 "tests/golden/run/generics.hero"
    t8 = INT64_C(3);
#line 34 "tests/golden/run/generics.hero"
    t9 = hero_array_new(&hero_desc_int, 3);
#line 34 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t9, &t6);
#line 34 "tests/golden/run/generics.hero"
      hero_array_decref(t9); t9 = grown; }
#line 34 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t9, &t7);
#line 34 "tests/golden/run/generics.hero"
      hero_array_decref(t9); t9 = grown; }
#line 34 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t9, &t8);
#line 34 "tests/golden/run/generics.hero"
      hero_array_decref(t9); t9 = grown; }
#line 34 "tests/golden/run/generics.hero"
    t52 = h3_own3;
#line 34 "tests/golden/run/generics.hero"
    h3_own3 = t9;
#line 318 "generics.c"
    hero_array_decref(t52);
#line 34 "tests/golden/run/generics.hero"
    t10 = h_generics_first_1b9a87(t9);
#line 34 "tests/golden/run/generics.hero"
    hero_print_str(t4);
#line 34 "tests/golden/run/generics.hero"
    hero_print_str(t5);
#line 34 "tests/golden/run/generics.hero"
    hero_print_int(t10);
#line 34 "tests/golden/run/generics.hero"
    hero_print_end();
#line 35 "tests/golden/run/generics.hero"
    t11 = HERO_STR_LIT(hero_str_6bb5e50a);
#line 35 "tests/golden/run/generics.hero"
    t12 = HERO_STR_LIT(hero_str_5a47bc97);
#line 35 "tests/golden/run/generics.hero"
    t13 = hero_array_new(&hero_desc_str, 2);
#line 35 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t13, &t11);
#line 35 "tests/golden/run/generics.hero"
      hero_array_decref(t13); t13 = grown; }
#line 35 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t13, &t12);
#line 35 "tests/golden/run/generics.hero"
      hero_array_decref(t13); t13 = grown; }
#line 35 "tests/golden/run/generics.hero"
    t53 = h4_own4;
#line 35 "tests/golden/run/generics.hero"
    h4_own4 = t13;
#line 348 "generics.c"
    hero_array_decref(t53);
#line 35 "tests/golden/run/generics.hero"
    t14 = h_generics_last_1e58d9(t13);
#line 35 "tests/golden/run/generics.hero"
    t54 = h5_own5;
#line 35 "tests/golden/run/generics.hero"
    h5_own5 = t14;
#line 356 "generics.c"
    hero_str_decref(t54);
#line 35 "tests/golden/run/generics.hero"
    t15 = HERO_STR_LIT(hero_str_20);
#line 35 "tests/golden/run/generics.hero"
    t16 = INT64_C(1);
#line 35 "tests/golden/run/generics.hero"
    t17 = INT64_C(2);
#line 35 "tests/golden/run/generics.hero"
    t18 = INT64_C(3);
#line 35 "tests/golden/run/generics.hero"
    t19 = hero_array_new(&hero_desc_int, 3);
#line 35 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t19, &t16);
#line 35 "tests/golden/run/generics.hero"
      hero_array_decref(t19); t19 = grown; }
#line 35 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t19, &t17);
#line 35 "tests/golden/run/generics.hero"
      hero_array_decref(t19); t19 = grown; }
#line 35 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t19, &t18);
#line 35 "tests/golden/run/generics.hero"
      hero_array_decref(t19); t19 = grown; }
#line 35 "tests/golden/run/generics.hero"
    t55 = h6_own6;
#line 35 "tests/golden/run/generics.hero"
    h6_own6 = t19;
#line 384 "generics.c"
    hero_array_decref(t55);
#line 35 "tests/golden/run/generics.hero"
    t20 = h_generics_last_1b9a87(t19);
#line 35 "tests/golden/run/generics.hero"
    hero_print_str(t14);
#line 35 "tests/golden/run/generics.hero"
    hero_print_str(t15);
#line 35 "tests/golden/run/generics.hero"
    hero_print_int(t20);
#line 35 "tests/golden/run/generics.hero"
    hero_print_end();
#line 38 "tests/golden/run/generics.hero"
    t21 = INT64_C(1);
#line 38 "tests/golden/run/generics.hero"
    t22 = INT64_C(2);
#line 38 "tests/golden/run/generics.hero"
    t23 = INT64_C(3);
#line 38 "tests/golden/run/generics.hero"
    t24 = hero_array_new(&hero_desc_int, 3);
#line 38 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t24, &t21);
#line 38 "tests/golden/run/generics.hero"
      hero_array_decref(t24); t24 = grown; }
#line 38 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t24, &t22);
#line 38 "tests/golden/run/generics.hero"
      hero_array_decref(t24); t24 = grown; }
#line 38 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t24, &t23);
#line 38 "tests/golden/run/generics.hero"
      hero_array_decref(t24); t24 = grown; }
#line 38 "tests/golden/run/generics.hero"
    t56 = h7_own7;
#line 38 "tests/golden/run/generics.hero"
    h7_own7 = t24;
#line 420 "generics.c"
    hero_array_decref(t56);
#line 38 "tests/golden/run/generics.hero"
    t25 = h_generics_label;
#line 38 "tests/golden/run/generics.hero"
    t26 = h_generics_convert_37fb3fcc(t24, t25);
#line 38 "tests/golden/run/generics.hero"
    t57 = h8_own8;
#line 38 "tests/golden/run/generics.hero"
    h8_own8 = t26;
#line 430 "generics.c"
    hero_array_decref(t57);
#line 38 "tests/golden/run/generics.hero"
    t27 = HERO_STR_LIT(hero_str_2d);
#line 38 "tests/golden/run/generics.hero"
    t28 = hero_str_join(t26, t27);
#line 38 "tests/golden/run/generics.hero"
    t58 = h9_own9;
#line 38 "tests/golden/run/generics.hero"
    h9_own9 = t28;
#line 440 "generics.c"
    hero_str_decref(t58);
#line 38 "tests/golden/run/generics.hero"
    hero_print_str(t28);
#line 38 "tests/golden/run/generics.hero"
    hero_print_end();
#line 41 "tests/golden/run/generics.hero"
    t29 = INT64_C(10);
#line 41 "tests/golden/run/generics.hero"
    t30 = INT64_C(20);
#line 41 "tests/golden/run/generics.hero"
    t31 = hero_array_new(&hero_desc_int, 2);
#line 41 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t31, &t29);
#line 41 "tests/golden/run/generics.hero"
      hero_array_decref(t31); t31 = grown; }
#line 41 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t31, &t30);
#line 41 "tests/golden/run/generics.hero"
      hero_array_decref(t31); t31 = grown; }
#line 41 "tests/golden/run/generics.hero"
    t59 = h10_own10;
#line 41 "tests/golden/run/generics.hero"
    h10_own10 = t31;
#line 464 "generics.c"
    hero_array_decref(t59);
#line 41 "tests/golden/run/generics.hero"
    t32 = h_generics_first_1b9a87(t31);
#line 41 "tests/golden/run/generics.hero"
    t33 = INT64_C(30);
#line 41 "tests/golden/run/generics.hero"
    t34 = INT64_C(40);
#line 41 "tests/golden/run/generics.hero"
    t35 = hero_array_new(&hero_desc_int, 2);
#line 41 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t35, &t33);
#line 41 "tests/golden/run/generics.hero"
      hero_array_decref(t35); t35 = grown; }
#line 41 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t35, &t34);
#line 41 "tests/golden/run/generics.hero"
      hero_array_decref(t35); t35 = grown; }
#line 41 "tests/golden/run/generics.hero"
    t60 = h11_own11;
#line 41 "tests/golden/run/generics.hero"
    h11_own11 = t35;
#line 486 "generics.c"
    hero_array_decref(t60);
#line 41 "tests/golden/run/generics.hero"
    t36 = h_generics_first_1b9a87(t35);
#line 41 "tests/golden/run/generics.hero"
    hero_print_int(t32);
#line 41 "tests/golden/run/generics.hero"
    hero_print_int(t36);
#line 41 "tests/golden/run/generics.hero"
    hero_print_end();
#line 45 "tests/golden/run/generics.hero"
    t37 = HERO_STR_LIT(hero_str_61);
#line 45 "tests/golden/run/generics.hero"
    t38 = HERO_STR_LIT(hero_str_62);
#line 45 "tests/golden/run/generics.hero"
    t39 = hero_array_new(&hero_desc_str, 2);
#line 45 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t39, &t37);
#line 45 "tests/golden/run/generics.hero"
      hero_array_decref(t39); t39 = grown; }
#line 45 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t39, &t38);
#line 45 "tests/golden/run/generics.hero"
      hero_array_decref(t39); t39 = grown; }
#line 45 "tests/golden/run/generics.hero"
    t61 = h12_own12;
#line 45 "tests/golden/run/generics.hero"
    h12_own12 = t39;
#line 514 "generics.c"
    hero_array_decref(t61);
#line 45 "tests/golden/run/generics.hero"
    t40 = HERO_STR_LIT(hero_str_63);
#line 45 "tests/golden/run/generics.hero"
    t41 = hero_array_new(&hero_desc_str, 1);
#line 45 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t41, &t40);
#line 45 "tests/golden/run/generics.hero"
      hero_array_decref(t41); t41 = grown; }
#line 45 "tests/golden/run/generics.hero"
    t62 = h13_own13;
#line 45 "tests/golden/run/generics.hero"
    h13_own13 = t41;
#line 528 "generics.c"
    hero_array_decref(t62);
#line 45 "tests/golden/run/generics.hero"
    t42 = hero_array_new(&hero_desc_array, 2);
#line 45 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t42, &t39);
#line 45 "tests/golden/run/generics.hero"
      hero_array_decref(t42); t42 = grown; }
#line 45 "tests/golden/run/generics.hero"
    { HeroArrayHeader *grown = hero_array_push(t42, &t41);
#line 45 "tests/golden/run/generics.hero"
      hero_array_decref(t42); t42 = grown; }
#line 45 "tests/golden/run/generics.hero"
    t63 = h14_own14;
#line 45 "tests/golden/run/generics.hero"
    h14_own14 = t42;
#line 544 "generics.c"
    hero_array_decref(t63);
#line 45 "tests/golden/run/generics.hero"
    t64 = h0_rows;
#line 548 "generics.c"
    hero_array_incref(t42);
#line 45 "tests/golden/run/generics.hero"
    h0_rows = t42;
#line 552 "generics.c"
    hero_array_decref(t64);
#line 46 "tests/golden/run/generics.hero"
    t43 = h0_rows;
#line 46 "tests/golden/run/generics.hero"
    t44 = h_generics_first_4ce7463f(t43);
#line 46 "tests/golden/run/generics.hero"
    t65 = h15_own15;
#line 46 "tests/golden/run/generics.hero"
    h15_own15 = t44;
#line 562 "generics.c"
    hero_array_decref(t65);
#line 46 "tests/golden/run/generics.hero"
    t45 = hero_array_len(t44);
#line 46 "tests/golden/run/generics.hero"
    t46 = HERO_STR_LIT(hero_str_20);
#line 46 "tests/golden/run/generics.hero"
    t47 = h0_rows;
#line 46 "tests/golden/run/generics.hero"
    t48 = h_generics_first_4ce7463f(t47);
#line 46 "tests/golden/run/generics.hero"
    t66 = h16_own16;
#line 46 "tests/golden/run/generics.hero"
    h16_own16 = t48;
#line 576 "generics.c"
    hero_array_decref(t66);
#line 46 "tests/golden/run/generics.hero"
    t49 = h_generics_first_1e58d9(t48);
#line 46 "tests/golden/run/generics.hero"
    t67 = h17_own17;
#line 46 "tests/golden/run/generics.hero"
    h17_own17 = t49;
#line 584 "generics.c"
    hero_str_decref(t67);
#line 46 "tests/golden/run/generics.hero"
    hero_print_int(t45);
#line 46 "tests/golden/run/generics.hero"
    hero_print_str(t46);
#line 46 "tests/golden/run/generics.hero"
    hero_print_str(t49);
#line 46 "tests/golden/run/generics.hero"
    hero_print_end();
#line 46 "tests/golden/run/generics.hero"
    t68 = h0_rows;
#line 596 "generics.c"
    hero_array_decref(t68);
#line 46 "tests/golden/run/generics.hero"
    t69 = h1_own1;
#line 600 "generics.c"
    hero_array_decref(t69);
#line 46 "tests/golden/run/generics.hero"
    t70 = h2_own2;
#line 604 "generics.c"
    hero_str_decref(t70);
#line 46 "tests/golden/run/generics.hero"
    t71 = h3_own3;
#line 608 "generics.c"
    hero_array_decref(t71);
#line 46 "tests/golden/run/generics.hero"
    t72 = h4_own4;
#line 612 "generics.c"
    hero_array_decref(t72);
#line 46 "tests/golden/run/generics.hero"
    t73 = h5_own5;
#line 616 "generics.c"
    hero_str_decref(t73);
#line 46 "tests/golden/run/generics.hero"
    t74 = h6_own6;
#line 620 "generics.c"
    hero_array_decref(t74);
#line 46 "tests/golden/run/generics.hero"
    t75 = h7_own7;
#line 624 "generics.c"
    hero_array_decref(t75);
#line 46 "tests/golden/run/generics.hero"
    t76 = h8_own8;
#line 628 "generics.c"
    hero_array_decref(t76);
#line 46 "tests/golden/run/generics.hero"
    t77 = h9_own9;
#line 632 "generics.c"
    hero_str_decref(t77);
#line 46 "tests/golden/run/generics.hero"
    t78 = h10_own10;
#line 636 "generics.c"
    hero_array_decref(t78);
#line 46 "tests/golden/run/generics.hero"
    t79 = h11_own11;
#line 640 "generics.c"
    hero_array_decref(t79);
#line 46 "tests/golden/run/generics.hero"
    t80 = h12_own12;
#line 644 "generics.c"
    hero_array_decref(t80);
#line 46 "tests/golden/run/generics.hero"
    t81 = h13_own13;
#line 648 "generics.c"
    hero_array_decref(t81);
#line 46 "tests/golden/run/generics.hero"
    t82 = h14_own14;
#line 652 "generics.c"
    hero_array_decref(t82);
#line 46 "tests/golden/run/generics.hero"
    t83 = h15_own15;
#line 656 "generics.c"
    hero_array_decref(t83);
#line 46 "tests/golden/run/generics.hero"
    t84 = h16_own16;
#line 660 "generics.c"
    hero_array_decref(t84);
#line 46 "tests/golden/run/generics.hero"
    t85 = h17_own17;
#line 664 "generics.c"
    hero_str_decref(t85);
    return;
}

#line 16 "tests/golden/run/generics.hero"
/* first<str> */
#line 16 "tests/golden/run/generics.hero"
HERO_TU_LOCAL HeroStr h_generics_first_1e58d9(HeroArrayHeader * h0_xs) {
#line 673 "generics.c"
    HeroArrayHeader * t1 = {0};
    int64_t t2;
    HeroStr t3 = {0};
    goto bb0;
bb0:
#line 17 "tests/golden/run/generics.hero"
    t1 = h0_xs;
#line 17 "tests/golden/run/generics.hero"
    t2 = INT64_C(0);
#line 17 "tests/golden/run/generics.hero"
    t3 = *(HeroStr const *)hero_array_at(t1, t2);
#line 685 "generics.c"
    hero_str_incref(t3);
    return t3;
}

#line 16 "tests/golden/run/generics.hero"
/* first<i64> */
#line 16 "tests/golden/run/generics.hero"
HERO_TU_LOCAL int64_t h_generics_first_1b9a87(HeroArrayHeader * h0_xs) {
#line 694 "generics.c"
    HeroArrayHeader * t1 = {0};
    int64_t t2;
    int64_t t3;
    goto bb0;
bb0:
#line 17 "tests/golden/run/generics.hero"
    t1 = h0_xs;
#line 17 "tests/golden/run/generics.hero"
    t2 = INT64_C(0);
#line 17 "tests/golden/run/generics.hero"
    t3 = *(int64_t const *)hero_array_at(t1, t2);
#line 17 "tests/golden/run/generics.hero"
    return t3;
#line 708 "generics.c"
}

#line 19 "tests/golden/run/generics.hero"
/* last<str> */
#line 19 "tests/golden/run/generics.hero"
HERO_TU_LOCAL HeroStr h_generics_last_1e58d9(HeroArrayHeader * h0_xs) {
#line 715 "generics.c"
    HeroArrayHeader * t1 = {0};
    HeroArrayHeader * t2 = {0};
    int64_t t3;
    int64_t t4;
    int64_t t5;
    HeroStr t6 = {0};
    goto bb0;
bb0:
#line 20 "tests/golden/run/generics.hero"
    t1 = h0_xs;
#line 20 "tests/golden/run/generics.hero"
    t2 = h0_xs;
#line 20 "tests/golden/run/generics.hero"
    t3 = hero_array_len(t2);
#line 20 "tests/golden/run/generics.hero"
    t4 = INT64_C(1);
#line 20 "tests/golden/run/generics.hero"
    if (__builtin_sub_overflow(t3, t4, &t5)) hero_panic_overflow();
#line 20 "tests/golden/run/generics.hero"
    t6 = *(HeroStr const *)hero_array_at(t1, t5);
#line 736 "generics.c"
    hero_str_incref(t6);
    return t6;
}

#line 19 "tests/golden/run/generics.hero"
/* last<i64> */
#line 19 "tests/golden/run/generics.hero"
HERO_TU_LOCAL int64_t h_generics_last_1b9a87(HeroArrayHeader * h0_xs) {
#line 745 "generics.c"
    HeroArrayHeader * t1 = {0};
    HeroArrayHeader * t2 = {0};
    int64_t t3;
    int64_t t4;
    int64_t t5;
    int64_t t6;
    goto bb0;
bb0:
#line 20 "tests/golden/run/generics.hero"
    t1 = h0_xs;
#line 20 "tests/golden/run/generics.hero"
    t2 = h0_xs;
#line 20 "tests/golden/run/generics.hero"
    t3 = hero_array_len(t2);
#line 20 "tests/golden/run/generics.hero"
    t4 = INT64_C(1);
#line 20 "tests/golden/run/generics.hero"
    if (__builtin_sub_overflow(t3, t4, &t5)) hero_panic_overflow();
#line 20 "tests/golden/run/generics.hero"
    t6 = *(int64_t const *)hero_array_at(t1, t5);
#line 20 "tests/golden/run/generics.hero"
    return t6;
#line 768 "generics.c"
}

#line 23 "tests/golden/run/generics.hero"
/* convert<i64, str> */
#line 23 "tests/golden/run/generics.hero"
HERO_TU_LOCAL HeroArrayHeader * h_generics_convert_37fb3fcc(HeroArrayHeader * h0_xs, h_0fn_4a13fb08 h1_f) {
#line 775 "generics.c"
    HeroArrayHeader * h2_out = {0};
    HeroArrayHeader * h3_xs0 = {0};
    int64_t h4_i0;
    int64_t h5_x;
    HeroArrayHeader * h6_own6 = {0};
    HeroStr h7_own7 = {0};
    HeroArrayHeader * t1 = {0};
    HeroArrayHeader * t2 = {0};
    int64_t t3;
    int64_t t4;
    HeroArrayHeader * t5 = {0};
    int64_t t6;
    bool t7;
    HeroArrayHeader * t8 = {0};
    int64_t t9;
    int64_t t10;
    h_0fn_4a13fb08 t12;
    int64_t t13;
    HeroStr t14 = {0};
    int64_t t16;
    int64_t t17;
    int64_t t18;
    HeroArrayHeader * t19 = {0};
    HeroArrayHeader * t20 = {0};
    HeroArrayHeader * t21 = {0};
    HeroArrayHeader * t22 = {0};
    HeroStr t23 = {0};
    HeroArrayHeader * t24 = {0};
    HeroArrayHeader * t25 = {0};
    HeroArrayHeader * t26 = {0};
    HeroStr t27 = {0};
    goto bb0;
bb0:
#line 24 "tests/golden/run/generics.hero"
    t1 = hero_array_new(&hero_desc_str, 1);
#line 24 "tests/golden/run/generics.hero"
    t20 = h6_own6;
#line 24 "tests/golden/run/generics.hero"
    h6_own6 = t1;
#line 815 "generics.c"
    hero_array_decref(t20);
#line 24 "tests/golden/run/generics.hero"
    t21 = h2_out;
#line 819 "generics.c"
    hero_array_incref(t1);
#line 24 "tests/golden/run/generics.hero"
    h2_out = t1;
#line 823 "generics.c"
    hero_array_decref(t21);
#line 25 "tests/golden/run/generics.hero"
    t2 = h0_xs;
#line 25 "tests/golden/run/generics.hero"
    t22 = h3_xs0;
#line 829 "generics.c"
    hero_array_incref(t2);
#line 25 "tests/golden/run/generics.hero"
    h3_xs0 = t2;
#line 833 "generics.c"
    hero_array_decref(t22);
#line 25 "tests/golden/run/generics.hero"
    t3 = INT64_C(0);
#line 25 "tests/golden/run/generics.hero"
    h4_i0 = t3;
#line 25 "tests/golden/run/generics.hero"
    goto bb1;
#line 25 "tests/golden/run/generics.hero"
bb1:
#line 25 "tests/golden/run/generics.hero"
    t4 = h4_i0;
#line 25 "tests/golden/run/generics.hero"
    t5 = h3_xs0;
#line 25 "tests/golden/run/generics.hero"
    t6 = hero_array_len(t5);
#line 25 "tests/golden/run/generics.hero"
    t7 = t4 < t6;
#line 25 "tests/golden/run/generics.hero"
    if (t7) goto bb2; else goto bb4;
#line 25 "tests/golden/run/generics.hero"
bb2:
#line 25 "tests/golden/run/generics.hero"
    t8 = h3_xs0;
#line 25 "tests/golden/run/generics.hero"
    t9 = h4_i0;
#line 25 "tests/golden/run/generics.hero"
    t10 = *(int64_t const *)hero_array_at(t8, t9);
#line 25 "tests/golden/run/generics.hero"
    h5_x = t10;
#line 26 "tests/golden/run/generics.hero"
    t12 = h1_f;
#line 26 "tests/golden/run/generics.hero"
    t13 = h5_x;
#line 26 "tests/golden/run/generics.hero"
    t14 = t12(t13);
#line 26 "tests/golden/run/generics.hero"
    t23 = h7_own7;
#line 26 "tests/golden/run/generics.hero"
    h7_own7 = t14;
#line 873 "generics.c"
    hero_str_decref(t23);
#line 26 "tests/golden/run/generics.hero"
    hero_array_push_owned(&h2_out, &t14);
#line 26 "tests/golden/run/generics.hero"
    goto bb3;
#line 26 "tests/golden/run/generics.hero"
bb3:
#line 25 "tests/golden/run/generics.hero"
    t16 = h4_i0;
#line 25 "tests/golden/run/generics.hero"
    t17 = INT64_C(1);
#line 25 "tests/golden/run/generics.hero"
    if (__builtin_add_overflow(t16, t17, &t18)) hero_panic_overflow();
#line 25 "tests/golden/run/generics.hero"
    h4_i0 = t18;
#line 25 "tests/golden/run/generics.hero"
    goto bb1;
#line 25 "tests/golden/run/generics.hero"
bb4:
#line 27 "tests/golden/run/generics.hero"
    t19 = h2_out;
#line 895 "generics.c"
    hero_array_incref(t19);
#line 27 "tests/golden/run/generics.hero"
    t24 = h2_out;
#line 899 "generics.c"
    hero_array_decref(t24);
#line 27 "tests/golden/run/generics.hero"
    t25 = h3_xs0;
#line 903 "generics.c"
    hero_array_decref(t25);
#line 27 "tests/golden/run/generics.hero"
    t26 = h6_own6;
#line 907 "generics.c"
    hero_array_decref(t26);
#line 27 "tests/golden/run/generics.hero"
    t27 = h7_own7;
#line 911 "generics.c"
    hero_str_decref(t27);
    return t19;
}

#line 16 "tests/golden/run/generics.hero"
/* first<[str]> */
#line 16 "tests/golden/run/generics.hero"
HERO_TU_LOCAL HeroArrayHeader * h_generics_first_4ce7463f(HeroArrayHeader * h0_xs) {
#line 920 "generics.c"
    HeroArrayHeader * t1 = {0};
    int64_t t2;
    HeroArrayHeader * t3 = {0};
    goto bb0;
bb0:
#line 17 "tests/golden/run/generics.hero"
    t1 = h0_xs;
#line 17 "tests/golden/run/generics.hero"
    t2 = INT64_C(0);
#line 17 "tests/golden/run/generics.hero"
    t3 = *(HeroArrayHeader * const *)hero_array_at(t1, t2);
#line 932 "generics.c"
    hero_array_incref(t3);
    return t3;
}
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_generics_main();
    hero_runtime_check_leaks();
    return 0;
}
