/* Generated by heroes 0.2.0 from tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero. Do not edit. */
#include "heroes_runtime.h"
#include <math.h>
#include <hero_os.h>
#include <heroes_runtime.h>
#include "heroes_guard_open.h"
#include <dead-address-copy-made-before-the-end-reaches-c.h>
#include "heroes_guard_close.h"

_Static_assert(HERO_RUNTIME_ABI == 30, "heroes_runtime.h is from another compiler");
#define HERO_TU_LOCAL
#define HERO_TU_QUIET

#define HERO_RET_INT(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 8 : sizeof(c) <= 8))
#define HERO_C_INTEGER(c) _Generic((c), _Bool:1, char:1, signed char:1, short:1, int:1, long:1, long long:1, unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, default:0)
#define HERO_C_UNSIGNED(c) _Generic((c), unsigned char:1, unsigned short:1, unsigned int:1, unsigned long:1, unsigned long long:1, _Bool:1, char:((char)-1 > 0), signed char:0, short:0, int:0, long:0, long long:0, default:0)
#define HERO_RET_I8(c) (HERO_C_INTEGER(c) && (_Generic((c), _Bool:1, default:0) || (!HERO_C_UNSIGNED(c) && sizeof(c) == 1)))
#define HERO_RET_I16(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 2 : sizeof(c) <= 2))
#define HERO_RET_I32(c) (HERO_C_INTEGER(c) && (HERO_C_UNSIGNED(c) ? sizeof(c) < 4 : sizeof(c) <= 4))
#define HERO_RET_U8(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) == 1)
#define HERO_RET_U16(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 2)
#define HERO_RET_U32(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 4)
#define HERO_RET_U64(c) (HERO_C_INTEGER(c) && HERO_C_UNSIGNED(c) && sizeof(c) <= 8)
#define HERO_RET_F32(c) _Generic((c), float:1, default:0)
#define HERO_RET_F64(c) _Generic((c), float:1, double:1, long double:(__LDBL_MANT_DIG__ <= __DBL_MANT_DIG__ && __LDBL_MAX_EXP__ <= __DBL_MAX_EXP__ && __LDBL_MIN_EXP__ >= __DBL_MIN_EXP__), default:0)
#define HERO_RET_BOOL(c) _Generic((c), _Bool:1, default:0)
#define HERO_RET_STR(c) _Generic((c), HeroStr:1, default:0)
#define HERO_RET_UNIT(c) __builtin_types_compatible_p(__typeof__(c), void)
#define HERO_RET_PTR(c) (__builtin_classify_type(c) == 5)
#define HERO_RET_RECORD(c, T) __builtin_types_compatible_p(__typeof__(c), T)
#define HERO_RET_CSTR(c) _Generic((c), char *:1, const char *:1, signed char *:1, const signed char *:1, unsigned char *:1, const unsigned char *:1, default:0)
_Static_assert(HERO_RET_RECORD(node_new(), node *), "heroes-ffi-return node_new Node");
_Static_assert(HERO_RET_UNIT(node_free((node *){0})), "heroes-ffi-return node_free ()");
_Static_assert(HERO_RET_INT(node_value((node *){0})), "heroes-ffi-return node_value i64");
_Static_assert(HERO_RET_INT(HERO_OS_OK), "heroes-ffi-return HERO_OS_OK i64");
_Static_assert(__builtin_constant_p(HERO_OS_OK), "heroes-ffi-const HERO_OS_OK");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_FOUND), "heroes-ffi-return HERO_OS_NOT_FOUND i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_FOUND), "heroes-ffi-const HERO_OS_NOT_FOUND");
_Static_assert(HERO_RET_INT(HERO_OS_NOT_TEXT), "heroes-ffi-return HERO_OS_NOT_TEXT i64");
_Static_assert(__builtin_constant_p(HERO_OS_NOT_TEXT), "heroes-ffi-const HERO_OS_NOT_TEXT");
_Static_assert(HERO_RET_INT(HERO_OS_BAD_NAME), "heroes-ffi-return HERO_OS_BAD_NAME i64");
_Static_assert(__builtin_constant_p(HERO_OS_BAD_NAME), "heroes-ffi-const HERO_OS_BAD_NAME");
_Static_assert(HERO_RET_STR(hero_file_read_str((HeroStr){0}, 0)), "heroes-ffi-return hero_file_read_str str");
_Static_assert(HERO_RET_INT(hero_file_write_str((HeroStr){0}, (HeroStr){0})), "heroes-ffi-return hero_file_write_str i64");
_Static_assert(HERO_RET_INT(hero_args_count()), "heroes-ffi-return hero_args_count i64");
_Static_assert(HERO_RET_STR(hero_args_at((int64_t)0)), "heroes-ffi-return hero_args_at str");
_Static_assert(HERO_RET_CSTR(hero_args_raw((int64_t)0)), "heroes-ffi-return hero_args_raw cstr");
_Static_assert(HERO_RET_UNIT(hero_exit((int64_t)0)), "heroes-ffi-return hero_exit ()");
_Static_assert(HERO_RET_INT(HERO_STR_OK), "heroes-ffi-return HERO_STR_OK i64");
_Static_assert(__builtin_constant_p(HERO_STR_OK), "heroes-ffi-const HERO_STR_OK");
_Static_assert(HERO_RET_STR(hero_str_try_from_cstr(0, 0)), "heroes-ffi-return hero_str_try_from_cstr str");

#line 54 "deadaddresscopymadebeforetheendreachesc.c"
typedef struct h_0opt_f87774a {
    int64_t tag;
    union {
        HeroStr ok;
        HeroFailure err;
    } as;
} h_0opt_f87774a;

typedef struct h_0opt_a8ea2 {
    int64_t tag;
    union {
        HeroFailure err;
    } as;
} h_0opt_a8ea2;

#pragma clang diagnostic push
#pragma clang diagnostic error "-Wdouble-promotion"
#pragma clang diagnostic error "-Wimplicit-float-conversion"
#pragma clang diagnostic error "-Wfloat-conversion"
#pragma clang diagnostic error "-Wimplicit-int-conversion"
#line 18 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
__attribute__((unused)) static void hero_ffi_probe_h_deadaddresscopymadebeforetheendreachesc_node_free(node * a0) { (void)(node_free)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_deadaddresscopymadebeforetheendreachesc_node_value(node * a0) { (void)(node_value)(a0); }
#line 113 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_read_str(HeroStr a0, int64_t * a1) { (void)(hero_file_read_str)(a0, (void *)a1); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_file_write_str(HeroStr a0, HeroStr a1) { (void)(hero_file_write_str)(a0, a1); }
#line 116 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_at(int64_t a0) { (void)(hero_args_at)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_args_raw(int64_t a0) { (void)(hero_args_raw)(a0); }
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_exit(int64_t a0) { (void)(hero_exit)(a0); }
#line 124 "<heroes library>"
__attribute__((unused)) static void hero_ffi_probe_h_library_hero_str_try_from_cstr(const char * a0, int64_t * a1) { (void)(hero_str_try_from_cstr)(a0, (void *)a1); }
#line 87 "deadaddresscopymadebeforetheendreachesc.c"
#pragma clang diagnostic pop

HERO_TU_LOCAL bool h_deadaddresscopymadebeforetheendreachesc_Node_eq(node * const *a, node * const *b);
HERO_TU_LOCAL uint64_t h_deadaddresscopymadebeforetheendreachesc_Node_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v);
HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v);
HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b);
HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem);
HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v);
HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v);
HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b);
HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem);

void h_deadaddresscopymadebeforetheendreachesc_main(void);

#line 21 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
void h_deadaddresscopymadebeforetheendreachesc_main(void) {
#line 21 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    node * h0_a; node * h1_keep; node * t1; node * t2; node * t3; node * t4; int64_t t5; goto bb0;
#line 21 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
bb0:
    t1 = node_new();
#line 22 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    hero_handle_acquired(t1, "node_free");
#line 22 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    h0_a = t1;
    t2 = h0_a;
#line 23 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    h1_keep = t2;
    t3 = h0_a;
#line 24 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    {
#line 24 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    hero_handle_alive(t3, "the argument `n` of `node_free`");
#line 24 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    uint64_t hero_life_0_0 = hero_handle_ending(t3, "node_free", NULL);
#line 24 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    (void)node_free(t3);
#line 24 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    if (hero_handle_ended(t3, hero_life_0_0) && h0_a == t3) h0_a = hero_handle_dead();
#line 24 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    }
    t4 = h1_keep;
#line 25 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    hero_handle_alive(t4, "the argument `n` of `node_value`");
#line 25 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    t5 = node_value(t4);
#line 25 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    hero_print_int(t5);
#line 25 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    hero_print_end();
#line 25 "tests/golden/run/dead-address-copy-made-before-the-end-reaches-c.hero"
    return;
#line 141 "deadaddresscopymadebeforetheendreachesc.c"
}
HERO_TU_LOCAL bool h_deadaddresscopymadebeforetheendreachesc_Node_eq(node * const *a, node * const *b) {
    return hero_handle_eq(*a, *b);
}

HERO_TU_LOCAL uint64_t h_deadaddresscopymadebeforetheendreachesc_Node_hash(const void *elem) {
    node * const *v = elem;
    uint64_t h = UINT64_C(0xcbf29ce484222325);
    h = (h ^ (uint64_t)(uintptr_t)*v) * UINT64_C(0x100000001b3);
    return h;
}

HERO_TU_LOCAL void h_0opt_f87774a_retain(const h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_incref(v->as.ok);
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_f87774a_release(h_0opt_f87774a *v) {
    if (v->tag == INT64_C(0)) {
        hero_str_decref(v->as.ok);
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_f87774a_eq(const h_0opt_f87774a *a, const h_0opt_f87774a *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return (&hero_desc_str)->eq(&a->as.ok, &b->as.ok);
}

HERO_TU_LOCAL uint64_t h_0opt_f87774a_hash(const void *elem) {
    const h_0opt_f87774a *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return (h ^ (&hero_desc_str)->hash(&v->as.ok)) * UINT64_C(0x100000001b3);
}

HERO_TU_LOCAL void h_0opt_a8ea2_retain(const h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_retain(&v->as.err);
    }
}

HERO_TU_LOCAL void h_0opt_a8ea2_release(h_0opt_a8ea2 *v) {
    if (v->tag == INT64_C(0)) {
        return;
    } else {
        hero_failure_release(&v->as.err);
    }
}

HERO_TU_LOCAL bool h_0opt_a8ea2_eq(const h_0opt_a8ea2 *a, const h_0opt_a8ea2 *b) {
    if (a->tag != b->tag) return false;
    if (a->tag != INT64_C(0)) return hero_failure_eq(&a->as.err, &b->as.err);
    return true;
}

HERO_TU_LOCAL uint64_t h_0opt_a8ea2_hash(const void *elem) {
    const h_0opt_a8ea2 *v = elem;
    uint64_t h = (UINT64_C(0xcbf29ce484222325) ^ (uint64_t)v->tag)
        * UINT64_C(0x100000001b3);
    if (v->tag != INT64_C(0)) {
        return (h ^ hero_failure_hash(&v->as.err)) * UINT64_C(0x100000001b3);
    }
    return h;
}


int main(int argc, char **argv) {
    hero_args_set(argc, argv);
    h_deadaddresscopymadebeforetheendreachesc_main();
    hero_runtime_check_leaks();
    return 0;
}
